### DISCUSSION TITLE
[Feature] Option to edit liveness/readiness probe of oap in helm chart

### DISCUSSION THREAD

**Discussion by zshrine** [apache/skywalking#10064] [Q&A] [answered]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The first replica of the oap container can take quite a while to startup. I have tried modifying the jvm options to a higher memory but the problem still persist. We can edit the deployment after doing a helm install/upgrade but would be much preferable if we can edit it directly as value. 

Also, is there any suggestions on how we can speed up the startup ? Or could it be some setting on our end that is causing the slow startup?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment, marked as answer]
At the very first run, OAP needs to wait for OAP init job to finish, while the init job needs to wait for the storage's readiness. 

What do you mean it's slow? Do you measure from the OAP is running or from the OAP is created?

**Reply by zshrine** [reply]
This is after the init job's finish. I mean subsequent upgrade of the helm chart. 

The pod takes very long to be ready and the liveness/readiness probe will fail 3 times, and the pod will restart. I have to adjust the InitialDelaySeconds in order for the pod to be ready.  Does the amount of data we have in elasticsearch affects how long the pod takes to be ready?

**Reply by zshrine** [reply]
I have attached my startup log. [oap_server.log](https://github.com/apache/skywalking/files/10129610/oap_server.log) My pod started at 02:47:59 and was only fully ready at 02:49:21. So it took a total of 82 seconds. 

The default probes is considered as follows:
```
image: {{ .Values.oap.image.repository }}:{{ required "oap.image.tag is required" .Values.oap.image.tag }}
imagePullPolicy: {{ .Values.oap.image.pullPolicy }}
livenessProbe:
  tcpSocket:
    port: 12800
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  tcpSocket:
    port: 12800
  initialDelaySeconds: 15
  periodSeconds: 20
```

So the container only has 15 + (3 *20) = 75 seconds to get ready. So either we will need to be able to edit the probes or make the oap server startup faster.
