### DISCUSSION TITLE
how to enable Self-Observability in version-9.3.0?

### DISCUSSION THREAD

**Discussion by xiongshiyan** [apache/skywalking#10155] [Q&A]
I can enable Self-Observability through doing some configs like below in config/application.yml when I use Skywalking version 8

```
telemetry:
  selector: ${SW_TELEMETRY:prometheus}
  none:
  prometheus:
    host: ${SW_TELEMETRY_PROMETHEUS_HOST:0.0.0.0}
    port: ${SW_TELEMETRY_PROMETHEUS_PORT:1234}

prometheus-fetcher:
  selector: ${SW_PROMETHEUS_FETCHER:default}
  default:
    active: ${SW_PROMETHEUS_FETCHER_ACTIVE:true}
```
but I can't find the option of 'prometheus-fetcher' in config/application.yml and Self-Observability UI is blank when I use Skywalking version 9, how can I enable Self-Observability ?

thanks !!
