### DISCUSSION TITLE
how to enable Self-Observability in version-9.3.0?

### DISCUSSION THREAD

**Discussion by xiongshiyan** [apache/skywalking#10154] [Q&A]
I can enable Self-Observability through doing some configs like below in config/application.yml when I use Skywalking version 8

```
telemetry:
  selector: ${SW_TELEMETRY:prometheus}
  none:
  prometheus:
    host: ${SW_TELEMETRY_PROMETHEUS_HOST:0.0.0.0}
    port: ${SW_TELEMETRY_PROMETHEUS_PORT:1234}

prometheus-fetcher:
  selector: ${SW_PROMETHEUS_FETCHER:default}
  default:
    active: ${SW_PROMETHEUS_FETCHER_ACTIVE:true}
```
but I can't find the option of 'prometheus-fetcher' in config/application.yml when I use Skywalking version 9, how can I enable Self-Observability ?

thanks !!

**Comment by wu-sheng** [comment]
Where does the doc say anything about `prometheus-fetcher`? Don't read a 3rd party blog and ask for the community.
Every version has its document. Read the official docs, and post the link of the doc if you have any question about this.

**Comment by hnxydq** [comment]
As the doc v9.3.0 describe below.
For the step 2 "Set up OpenTelemetry to scrape the metrics from OAP telemetry", i found the  test case( https://github.com/apache/skywalking/blob/7ad04062b20ecf2bdb0afc4ba8c6ce353e5ae4d8/test/e2e-v2/cases/so11y/otel-collector-config.yaml ), but which directory should we put the yaml? any demo for more details ?

![image](https://user-images.githubusercontent.com/9302530/211827987-6ccfabe7-f52c-4f93-a13f-25d401c82eaf.png)

**Reply by wu-sheng** [reply]
Showcase demos most key features, https://skywalking.apache.org/docs/skywalking-showcase/next/readme/

**Reply by hnxydq** [reply]
According to the source code,  I found the way to enable Self-Observability in version-9.3.0 when we just use in local windows for test as follows:
1.set up prometheus telemetry as describe in doc v9.3.0
```
telemetry:
  selector: ${SW_TELEMETRY:prometheus}
  none:
  prometheus:
    host: ${SW_TELEMETRY_PROMETHEUS_HOST:0.0.0.0}
    port: ${SW_TELEMETRY_PROMETHEUS_PORT:1234}
    sslEnabled: ${SW_TELEMETRY_PROMETHEUS_SSL_ENABLED:false}
    sslKeyPath: ${SW_TELEMETRY_PROMETHEUS_SSL_KEY_PATH:""}
    sslCertChainPath: ${SW_TELEMETRY_PROMETHEUS_SSL_CERT_CHAIN_PATH:""}
```
the default host and port can be found in file:
```
public class PrometheusConfig extends ModuleConfig {
    private String host = "0.0.0.0";
    private int port = 1234;
    private boolean sslEnabled = false;
    private String sslKeyPath;
    private String sslCertChainPath;
}
```
2.download opentelemetry-collector according to your operation system:
[opentelemetry-collector-releases](https://github.com/open-telemetry/opentelemetry-collector-releases/releases)

3.run the collector with yaml config file ([otel-collector-config.yaml](https://github.com/apache/skywalking/blob/master/test/e2e-v2/cases/so11y/otel-collector-config.yaml)):
```
receivers:
  prometheus:
    config:
     scrape_configs:
       - job_name: 'skywalking-so11y'
         scrape_interval: 5s
         static_configs:
           - targets: ['localhost:1234']
             labels:
               host_name: http://localhost:1234
               service: oap-server
processors:
  batch:

exporters:
  ####################################################################################
  # If you want to use otlp exporter please ensure that your OAP version is >= 9.2.0 #
  # or you can use oc exporter, The config format should be:                         #
  # opencensus:                                                                      #
  #   endpoint: "oap:11800"                                                          #
  #   tls:                                                                           #
  #      insecure: true                                                              #
  ####################################################################################
  otlp:
    endpoint: localhost:11800
    tls:
      insecure: true
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      processors:
      - batch
      exporters:
      #########################################
      # oc exporter config format:            #
      # - opencensus                          #
      #########################################
      - otlp
      - logging
```

run with command: 
```
otelcol-contrib --config=file:D:/deploy/skywalking/otelcol-contrib_0.69.0_windows_amd64/otel-collector-config.yaml
```

4. restart the oapService.bat then refresh the UI.
