### DISCUSSION TITLE
Why Skywalking can‘t show the adress of the Linux when I use the feature of Linux Monitoring?

### DISCUSSION THREAD

**Discussion by BoydenYubin** [apache/skywalking#10201] [Q&A]
###  The vm instance shows the vm:null
- Docker: =>  Runing the lastest version of skywalking-oap-server and same version of skywalking-ui cotainer
- Raspberry => The linux system to be watched (node_exporter and collector)

We can find all the metric data in the ui, but can't the real ip of the linux system
The vm.yaml will be as as below:

```yaml
filter: "{ tags -> tags.job_name == 'vm-monitoring' }" # The OpenTelemetry job name
expSuffix: tag({tags -> tags.node_identifier_host_name = 'vm::' + tags.node_identifier_host_name}).service(['node_identifier_host_name'])
metricPrefix: meter_vm
metricsRules:
  ......
```

UI shows the null name of the system as below:

 ![sample](https://raw.githubusercontent.com/BoydenYubin/PicGoHub/master/vm%20null.JPG)
