### DISCUSSION TITLE
How to alert about only some services?

### DISCUSSION THREAD

**Discussion by Jedore** [apache/skywalking#10264] [Q&A] [answered]
I want to alert only one service, and other services don't need to be alerted. Can skywalking support it? Thanks.

**Comment by pg-yang** [comment]
https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-alarm/

**Reply by Jedore** [reply]
Thanks very much @pg-yang. I have read the doc, but I can't make the solution. I have two services `K::A` and `K::B`, I want to alert about `K::A` but exclude `K::B`. Can you give me some more tips?  Btw, skywalking 9.3.0.

**Reply by wu-sheng** [reply]
Include the sepcific service name with required metric names.

**Reply by Jedore** [reply]
Thanks.

**Comment by Jedore** [comment, marked as answer]
It's my solution:
1. modify metrics in `config/oa/*.oal`:
    as https://skywalking.apache.org/docs/main/next/en/guides/backend-oal-scripts/ said.
    >  From 8.0.0, you may find the OAL script at /config/oal/*.oal of the SkyWalking dist. You could change it, such as by adding filter 
    conditions or new metrics. Then, reboot the OAP server, and it will come into effect.
    All metrics named in this script could be used in alarm and UI query.
   
    I add a new metrics in `config/oal/core.oal` to distinguish different services:
    ```
    kg_service_resp_time = from(Service.latency).filter(name in ["kg-graph::prod", "kg-graph::pre", "kg-graph::test", "kg-graph::dev"]).longAvg();
    ```

2. modify `alarm-settings.yml`:
    use updated or new metrics:

    ```
    rules:                                                                                                                                                                                                                                         
      service_resp_time_rule:
        metrics-name: kg_service_resp_time
        op: ">" 
        threshold: 1000
        period: 10
        count: 3
        silence-period: 5
        message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
    ```

And thanks for the tips of @pg-yang  and @wu-sheng .
