### DISCUSSION TITLE
skywalking-agent-test-tool example

### DISCUSSION THREAD

**Discussion by Jedore** [apache/skywalking#10723] [Q&A]
Is there any example about how to use [`end with`](https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/plugin-test/#expecteddatayaml) operator for string  in [skywalking-agent-test-tool](https://github.com/apache/skywalking-agent-test-tool)?
I write as:
```yaml
      - timestamp: gt 0
        endpoint: '/users'
        body:
          type: 'text'
          content:
             text: end with Logging-error-reported.
```
The actual text is `2023-04-23 18:42:30,187 [MainThread] ERROR root - Logging-error-reported.`

And always test failed ... 😢 
Thanks a lot !
