### DISCUSSION TITLE
How to know if a zipkin receiver is enabled ?

### DISCUSSION THREAD

**Discussion by amrih-pg** [apache/skywalking#10738] [Q&A] [answered]
I was trying to following this : https://github.com/apache/skywalking/blob/06558fcf5ab6afc6eaf3b30aa0ca541545e2d3ea/docs/en/setup/zipkin/tracing.md

below are something that i have setup on my minikube:
```
export SKYWALKING_RELEASE_VERSION=4.4.0 
export SKYWALKING_RELEASE_NAME=skywalking
export SKYWALKING_RELEASE_NAMESPACE=default

helm install "${SKYWALKING_RELEASE_NAME}" \
  oci://registry-1.docker.io/apache/skywalking-helm \
  --version "${SKYWALKING_RELEASE_VERSION}" \
  -n "${SKYWALKING_RELEASE_NAMESPACE}" \
	--set ui.image.tag=9.2.0 \
  --set oap.image.tag=9.2.0 \
  --set oap.storageType=elasticsearch \
  --set elasticsearch.replicas=1 \
  --set oap.replicas=1 \
  --set env.SW_RECEIVER_ZIPKIN=default
```

the pods running: 
![image](https://user-images.githubusercontent.com/126761683/234790034-526bbddb-2743-40da-a099-838d2ca6b679.png)

Anything that i should look for ? e.g., oap logs

**Comment by amrih-pg** [comment]
You could see that i have a zipkin pod above. That's just a separate zipkin server for me to verify how to send to a zipkin endpoint e.g:

```
curl --location 'http://localhost:9411/api/v2/spans' \
--header 'Content-Type: application/json' \
--data '[
  {
    "traceId": "a03ee8fff1dcd9b9",
    "parentId": "f5f268651b2a2b34",
    "id": "15fc03927f0f68df",
    "kind": "CLIENT",
    "name": "post",
    "timestamp": 1571896375322000,
    "duration": 14000,
    "localEndpoint": {
      "serviceName": "mobile_api"
    },
    "remoteEndpoint": {
      "serviceName": "blt",
      "port": 31882
    },
    "tags": {
      "client_status_code": "200",
      "http.uri.client": "/visits",
      "request_budget": "9980",
      "tracer": "syslog2scribe.haproxy-synapse"
    }
  }
]'
```

I was trying to open port-forward of the OAP for 9411 port and hit the same endpoint. I couldn't get `202 Accepted` status

**Comment by wu-sheng** [comment]
OAP logs would say zipkin receiver module is on with default provider.

**Reply by amrih-pg** [reply]
I will retry the installation. 

I noticed that the "zipkin" port is not exposed:
![image](https://user-images.githubusercontent.com/126761683/234796551-e022a901-80cf-4621-9520-74ab1427f989.png)

Anything I missed here ?

**Reply by wu-sheng** [reply]
@wankai123

**Reply by wankai123** [reply, marked as answer]
The port is not exposed by default, you need to expose it by the Helm install --set.

https://github.com/apache/skywalking-kubernetes/blob/6df69f01882b4d58367687a661267d01e30e573c/chart/skywalking/values.yaml#L43

**Reply by amrih-pg** [reply]
Thanks @wankai123 .. will try this as well

**Comment by lxx95** [comment]
Hi all, 

Trying to do something like @amrih-pg (as suggested [here](https://github.com/apache/skywalking/discussions/10747#discussioncomment-5770493) by @wu-sheng), exporting Zipkin traces starting from OTLP receiver.
Here my values.yaml to start the helm deployment:
```
oap:
  name: oap
  replicas: 1
  env:
    SW_OTEL_RECEIVER: default
    SW_RECEIVER_ZIPKIN: default
    SW_ZIPKIN_HTTP_COLLECTOR_ENABLED: true
    SW_OTEL_RECEIVER_ENABLED_HANDLERS: "oc, otlp"
  image:
    repository: skywalking.docker.scarf.sh/apache/skywalking-oap-server
    tag: 9.4.0  # Must be set explicitly
    pullPolicy: IfNotPresent
  storageType: "elasticsearch"
  ports:
    # add more ports here if you need, for example
    zipkin: 9411

ui:
  image:
    tag: 9.4.0

elasticsearch:
  imageTag: 7.5.1
  replicas: 1
  minimumMasterNodes: 1
  maxUnavailable: 0

fullnameOverride: "skywalking"

```
And my otel-collector:
```
receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      zipkin:
        endpoint: "skywalking-oap.skywalking.svc.cluster.local:9411"
        tls:
          insecure: true
      logging:
processors:
      batch:
service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin, logging]
```
This error message has been shown for exporting phase (from otel-collector):
`2023-05-04T14:56:27.171Z        error   exporterhelper/queued_retry.go:175      Exporting failed. No more retries left. Dropping data.  {"kind": "exporter", "data_type": "traces", "name": "zipkin", "error": "max elapsed time expired failed to push trace data via Zipkin exporter: Post \"skywalking-oap.skywalking.svc.cluster.local:9411\": unsupported protocol scheme \"skywalking-oap.skywalking.svc.cluster.local\"", "dropped_items": 5}`

The zipkin Skywalking OAP port was fine:
`skywalking-oap                             ClusterIP   10.99.240.73     <none>        11800/TCP,12800/TCP,9411/TCP   27m`

Thank you,
Luigi
