### DISCUSSION TITLE
Problems during exporting to OAP endpoint in OTLP gRPC format

### DISCUSSION THREAD

**Discussion by lxx95** [apache/skywalking#10747] [Q&A] [answered]
Hi all,

I have a problem during exporter, my Otel collector shows logs like:

> 2023-04-29T15:10:47.486Z        error   exporterhelper/queued_retry.go:401      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.trace.v1.TraceService/Export", "dropped_items": 50}
> 2023-04-29T15:10:49.788Z        error   exporterhelper/queued_retry.go:401      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "logs", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.logs.v1.LogsService/Export", "dropped_items": 3}

My goal is to configure the metrics/traces/logs exporting (gRPC) from the [Otel Demo](https://opentelemetry.io/docs/demo/kubernetes-deployment/) to Skywalking (that support [otlp gRPC](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/)).

Here my collector configuration:

> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: opentelemetry-demo-otelcol
>   labels:
>     app.kubernetes.io/name: otelcol
>     app.kubernetes.io/instance: opentelemetry-demo
>     app.kubernetes.io/version: "latest"
> data:
>   relay: |
>     exporters:
>       logging: {}
>       otlp:
>         endpoint: 'skywalking-oap.skywalking.svc.cluster.local:11800'
>         tls:
>           insecure: true
>       skywalking:
>         endpoint: 'skywalking-oap.skywalking.svc.cluster.local:11800'
>         tls:
>           insecure: true
>       prometheus:
>         enable_open_metrics: true
>         endpoint: 0.0.0.0:9464
>         resource_to_telemetry_conversion:
>           enabled: true
>     extensions:
>       health_check: {}
>       memory_ballast:
>         size_in_percentage: 40
>     processors:
>       resource/job-name:
>         attributes:
>         - key: job_name   
>           value: otel-demo
>           action: insert
>     receivers:
>       jaeger:
>         protocols:
>           grpc:
>             endpoint: ${MY_POD_IP}:14250
>           thrift_compact:
>             endpoint: ${MY_POD_IP}:6831
>           thrift_http:
>             endpoint: ${MY_POD_IP}:14268
>       otlp:
>         protocols:
>           grpc:
>             endpoint: ${MY_POD_IP}:4317
>       prometheus:
>         config:
>           scrape_configs:
>           - job_name: opentelemetry-collector
>             scrape_interval: 10s
>             static_configs:
>             - targets:
>               - ${MY_POD_IP}:8888
>       zipkin:
>         endpoint: ${MY_POD_IP}:9411
>     service:
>       extensions:
>       - health_check
>       - memory_ballast
>       pipelines:
>         logs:
>           exporters:
>           - otlp
>           - logging
>           processors:
>           - resource/job-name
>           receivers:
>           - otlp
>         metrics:
>           exporters:
>           - otlp
>           - logging
>           processors:
>           - resource/job-name
>           receivers:
>           - otlp
>         traces:
>           exporters:
>           - otlp
>           - logging
>           processors:
>           - resource/job-name
>           receivers:
>           - otlp
>       telemetry:
>         metrics:
>           address: ${MY_POD_IP}:8888

All the others components (pods/services/deployments) are the default (otel demo) one.
The Skywalking endpoint is fine, and it retrieves data from the own agent to the same endpoint.

Note: I have also tried with other demos like [Online Botique with OTLP](https://github.com/julianocosta89/opentelemetry-microservices-demo) the same errors were shown.

Other discussion on this topic was opened (by me) on [OTLP exporter Method not found: "opentelemetry.proto.collector.logs.v1.LogsService/Export" and "opentelemetry.proto.collector.trace.v1.TraceService/Export"](https://github.com/open-telemetry/opentelemetry-collector/discussions/7585).

Hope that all is clear.

Thank you,
Luigi

**Comment by wu-sheng** [comment, marked as answer]
AFAIK, we don't support otlp log format for now.
Ref doc https://skywalking.apache.org/docs/main/next/en/setup/backend/log-analyzer/#opentelemetry

You should use the exporter of skywalking

Of course, this log format could be supported by SkyWalking OAP.Just no one added it yet.
If you would like to contribute, welcome

**Comment by lxx95** [comment]
Hi @wu-sheng, Thank you for the quick response.

It was not clear for me, Basing on [this page](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/) I didn't found information about what is supported (and what not supported) on OTLP gRPC protocol.

So, this means that also for metrics and traces there is no support? 

I see that the skywalking exporter is on beta version for logs and metrics.

Thank you.

**Reply by wu-sheng** [reply]
Take a look at the the menu structure, it is about metrics.
Generally, this is OTLP metric format receiver.

**Reply by wu-sheng** [reply]
> I see that the skywalking exporter is on beta version for logs and metrics.

That is also contributed from the community. Whether beta or not, it is the original author call.

**Reply by lxx95** [reply]
Okay, thank you again.
This means that the table [listed here](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/) shows the metrics supported by OTLP gRCP (and the expected flow like: Istio Control Plane -> OpenTelemetry Collector – OC/OTLP exporter –> SkyWalking OAP Server). Everything else, in order to be compatible with OAP server, should be translated/converted with a particular exporter (for this reason the necessity to build the [skywalking exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter) in the opentelemetry-collector github repo).

Thank you, of course if a create some custom changes to guarantee the flow I will contibute to the skywalking repo.

**Reply by wu-sheng** [reply]
It doesn't have to be this way. This is just how it is due to historic reason. The previous contibutors made this.
OTLP log format had been discussed, if someone want to contribute, we are OK to accept.

Notice, about tracea, otlp trace format is not discussed, as mainly, we only analysis our native trace format.
Zipkin trace is supported, but not analysis, due to our STAM theory.

**Reply by lxx95** [reply]
Hi @wu-sheng, referring to [OpenTelemetry metrics receiver (with otlp gRPC protocol)](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/):

-  Can we expect from Skywalking OAP that all the metrics received in that format could be fine and shown in the Skywalking UI interface?
-  Starting from [OTEL Demo Architecture](https://opentelemetry.io/docs/demo/architecture/) and following the flow: OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, **exporter: otlp**) -> SkywalkingOAP:11800, can we expect all [these "completed" metrics ](https://opentelemetry.io/docs/demo/metric-features/)
-  Referring to [gRPC Skywalking Exporter](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/backend-meter/#opentelemetry-exporter), can we guarantee also the following flow: OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, **exporter: skywalking**) -> SkywalkingOAP:11800?

Unfortunately, based on documentation pages, it's not clear for me what can be expected from the two different flows and if there are any differences with the two adoptions.

Thank you.

**Reply by wu-sheng** [reply]
> Referring to [gRPC Skywalking Exporter](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/backend-meter/#opentelemetry-exporter), can we guarantee also the following flow: OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, exporter: skywalking) -> SkywalkingOAP:11800?

This is another receiver for SkyWalking native metric format, such as reporting by SkyWalking's agents. This is NOT for exporting.

____
Meanwhile, exporter docs are what you should take a look. https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/exporter/

gRPC channel is for metrics. But notice, there is no OTEL format converter as we are using sub/pub model to do the exporting. So, if you insist it has to be a kind of OTLP metrics, you have to build an extra layer.

**Reply by lxx95** [reply]
Probably my explanation was not clear:

"This is another receiver for SkyWalking native metric format, such as reporting by SkyWalking's agents. This is NOT for exporting."
- I need: Exporting from OTEL collector to Skywalking OAP with [SkyWalking gRPC Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/skywalkingexporter/README.md#skywalking-grpc-exporter)

**The goal is to use Skywalking like an APM, starting from OTLP** (and not metrics/traces/logs from Skywalking agents).
**I'm not interested to export data from Skywalking to other tools.**

Please see again these two flows:
- OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, exporter: otlp) -> SkywalkingOAP:11800
- OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, exporter: skywalking) -> SkywalkingOAP:11800

**Reply by wu-sheng** [reply]
That is what you were referring, 

> referring to [OpenTelemetry metrics receiver (with otlp gRPC protocol)](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/):

What exactly is your question? I am confused.

**Reply by lxx95** [reply]
[Here](https://skywalking.apache.org/docs/main/v9.4.0/en/setup/backend/opentelemetry-receiver/) the documentation refers to metric ingestion (to Skywalking) from the OTEL gRPC protocol, because Skywalking provide a OpenTelemetry receiver for metrics. -> **please correct this sentence if something is wrong.**

With an OTEL Collector we can receive metrics in some formats and export them into another format.
With the following flow we use the OTEL collector just to withdraw metrics and export in the Skywalking OAP component
- OTEL Demo -> gRPC OTLP -> OTEL Collector (receiver: otlp, exporter: otlp) -> SkywalkingOAP:11800

So, because in the OTEL Demo documentation we have [these metrics](https://opentelemetry.io/docs/demo/metric-features/) I should expect them in the Skywalking UI. 

The other point was related to another OTEL exporter, the [SkyWalking gRPC Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/skywalkingexporter/README.md#skywalking-grpc-exporter)
In that case:
- Is also valide the point above, can we expect the OTEL Demo metrics? What are the differences if we export with OTLP gRPC protocol or with the native Skywalking format (with the skywalking exporter on OTEL Collector)?

Hope that now is clear.

**Reply by wu-sheng** [reply]
> So, because in the OTEL Demo documentation we have [these metrics](https://opentelemetry.io/docs/demo/metric-features/) I should expect them in the Skywalking UI.

That has a precondition, you need to write MAL. Notice this statement in the doc
> The rule file should be in YAML format, defined by the scheme described in [MAL](https://skywalking.apache.org/docs/main/v9.4.0/en/concepts-and-designs/mal). Note: receiver-otel only supports the group, defaultMetricLevel, and metricsRules nodes of the scheme due to its push mode.

Then you could set up UI for the new metrics declared in the MAL script.

SkyWalking is not sampling saving metrics, but run a slow query in the query stage. It does most the pre-calculation and persistent the final results per time bucket.

___
> The other point was related to another OTEL exporter, the [SkyWalking gRPC Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/skywalkingexporter/README.md#skywalking-grpc-exporter)

This is an alternative only. SkyWalking as an APM, we don't want to limit users' choices. So, you could use SkyWalking exporter in OTEL collector, or forward OTEL metrics format data directly to OAP. In both ways, you need to write MAL as I mentioned.

**Comment by wu-sheng** [comment]
@lxx95 I started this https://github.com/apache/skywalking/issues/10752. Notice this is for logging only.

**Comment by zjj1002** [comment]
BUT SkyWalking exporter only supported log and metrics , tracing is most important for most user  
Any chance otel tracing would support officially?


[beta](https://github.com/open-telemetry/opentelemetry-collector#beta): metrics, logs

**Reply by wu-sheng** [reply]
This asking generally makes no sense. 
You didn't read previous discussions, and don't analysis why it doesn't, but only say it's important.

If it is, why no one did? It is a totally joke.

**Comment by abunet** [comment]
HI to everyone. I have very similar problems. 
In my opinion, you should add a specific topic in documentation sample on howto configure a collector to receive opentelemetry metrics, logs, and traces and send them to skywalking.

I have an app written in dotnet core. 
Metrics, Logs and Traces are generated using [opentelemetry dotnet](https://github.com/open-telemetry/opentelemetry-dotnet). I don't want to use specific agent libraries like SkyAPM, because I need to keep the app more interchangeable as possible.
My questions are:
1) Can I send my Metrics, Logs and Traces directly to the Sywalking Server via gRPC port 11800?
2) Anyone have a sample of an opentelemetry-collector configuration that can achieve the same objective?

I've tried two other opensource APM: SigNoz and Uptrace. Both of them support directly publishing in OpenTelemetry format.
I'm interested in Apache Skywalking for its architecture (Elastic backend, distributed telemetry with Satellite ...)
Thanks

**Reply by wu-sheng** [reply]
Most major features have provided otel collector configuration through e2e and documented in every page. I am not sure what you mean.
For integrated metrics, such as monitoring PostgreSQL, the root page provides a link to the doc, and the doc has relative part.
If you ask for general otel docs, it is not our scope.

> Can I send my Metrics, Logs and Traces directly to the Sywalking Server via gRPC port 11800?

Yes, of course, but you need to write MAL for metrics and LAL for logs, open Zipkin lens UI for otlp traces without analysis metrics from otlp traces.

**Reply by wu-sheng** [reply]
Once you are only using otep agent, with otlp metrics for your own app, rather than our supported, you need to read all relative docs.

For an APM, not just metrics, traces, and logs matter. We have wider support especially in native agents and official dashboards.

**Reply by abunet** [reply]
Thanks in advance for the quick reply.

> Most major features have provided otel collector configuration through e2e and documented in every page. I am not sure what you mean.

The suggestion is to add a dedicated topic in getting started on how to achive this for metrics, logs and traces. 

> Yes, of course, but you need to write MAL for metrics and LAL for logs, open Zipkin lens UI for otlp traces without analysis metrics from otlp traces.

Sorry, but In my opinion the question is quite clear: I have metrics logs and traces sent by an app in otlp. 
What I have to do in the backend to display my data? 
As I've already said, I'm very interested on the product, but it's not clear what I have to do. 

With Uptrace and SigNoz I've bootstrapped a test project in 0 seconds. I know that the APM landscape is very wide and this is only the starting point. And in my opinion this is a very common use case.

I've tried to configure a docker stack with opentelemetry collector that receives from opentelemetry and exports to metrics and logs with skywalking exporter and traces with zipkin exporter to skywalking 

**docker-compose.yaml**
```
version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  oap:
    image: ${OAP_IMAGE}
    container_name: oap
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    ports:
      - "11800:11800"
      - "12800:12800"
      - "9411:9411"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_RECEIVER_ZIPKIN: default
      SW_OTEL_RECEIVER: default
      SW_QUERY_ZIPKIN: default
      JAVA_OPTS: "-Xms2048m -Xmx2048m"

  ui:
    image: ${UI_IMAGE}
    container_name: ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8081:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./opentelemetry-collector-config.yaml:/etc/otelcol-contrib/config.yaml  # Collega il tuo file di configurazione YAML al container
    ports:
      - 4317:4317 
      - 4318:4318
    depends_on:
      - oap
```

**opentelemetry-collector-config.yaml**
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  zipkin/nontls:
    endpoint: "http://oap:9411/api/v2/spans"
    format: proto
    default_service_name: unknown-service
  skywalking:
    endpoint: "oap:11800"
    tls:
      insecure: true
service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,zipkin/nontls]
    metrics:
      receivers: [otlp]
      exporters: [logging,skywalking]
    logs:
      receivers: [otlp]
      exporters: [logging,skywalking]
```

In oap ui I can see my logs, but I cannot see metrics. 
The oap container log gives many _receive many java.lang.IllegalArgumentException: Malformed reading List<Span>_ for traces

Is there a way to achive what I'm trying to do with Apache Skywalking?
