### DISCUSSION TITLE
OAP Zipkin receiver problem - connection refused to :9411

### DISCUSSION THREAD

**Discussion by lxx95** [apache/skywalking#10787] [Q&A] [answered]
Hi all,

We have a problem with Zipkin receiver, an error log was displayed while exporting from the OTEL collector:
`2023-05-10T13:18:14.550Z        info    exporterhelper/queued_retry.go:434      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "traces", "name": "zipkin/2", "error": "failed to push trace data via Zipkin exporter: Post \"http://skywalking-oap.skywalking.svc.cluster.local:9411/api/v2/spans\": dial tcp 10.101.84.18:9411: connect: connection refused", "interval": "34.202773678s"}`

Here my values.yaml used to start the Skywalking helm deployment:
```
oap:
  name: oap
  replicas: 1
  env:
    SW_OTEL_RECEIVER: default
    SW_RECEIVER_ZIPKIN: default
    SW_ZIPKIN_HTTP_COLLECTOR_ENABLED: true
    SW_OTEL_RECEIVER_ENABLED_HANDLERS: "oc, otlp"
  image:
    repository: skywalking.docker.scarf.sh/apache/skywalking-oap-server
    tag: 9.4.0  # Must be set explicitly
    pullPolicy: IfNotPresent
  storageType: "elasticsearch"
  ports:
    # add more ports here if you need, for example
    zipkin: 9411

ui:
  image:
    tag: 9.4.0

elasticsearch:
  imageTag: 7.5.1
  replicas: 1
  minimumMasterNodes: 1
  maxUnavailable: 0

fullnameOverride: "skywalking"
```

And, my otel-collector config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-demo-otelcol
data:
  relay: |
    receivers:
      otlp:
        protocols:
          http:
    exporters:
      otlp:
        endpoint: "http://skywalking-oap.skywalking.svc.cluster.local:11800"
        tls:
          insecure: true
      skywalking:
        endpoint: "http://skywalking-oap.skywalking.svc.cluster.local:11800"
        tls:
          insecure: true
      zipkin:
        endpoint: "http://zipkin.zipkin.svc.cluster.local:9411/api/v2/spans"
        format: json
        tls:
          insecure: true
      zipkin/2:
        endpoint: "http://skywalking-oap.skywalking.svc.cluster.local:9411/api/v2/spans"
        format: json
        tls:
          insecure: true
      logging:
        verbosity: detailed
    processors:
      batch:
      filter:
        metrics:
          exclude:
            match_type: strict
            metric_names:
              - queueSize
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin, zipkin/2]
```

Note: the zipkin pipeline points to zipkin BE, the zipkin/2 pipeline points to Skywalking OAP endpoint to port 9411 that is opened
![image](https://github.com/apache/skywalking/assets/57501699/a5ab0bbf-56e3-43ce-8c4c-d06ea6e7ce37)

Now we have confirmation that the problem is related to Skywalking Zipkin receiver or bad configuration, because as you can see below, the zipkin backend is fine and traces were shown.
![image](https://github.com/apache/skywalking/assets/57501699/d7128318-1431-4cc8-a598-91a780c33267)

Thank you,
Luigi
