### DISCUSSION TITLE
Include my MAL configuration (otel-rules/) file during HELM deploy in values.yaml

### DISCUSSION THREAD

**Discussion by lxx95** [apache/skywalking#10960] [Q&A] [answered]
Hi,

My purpose is to **send Open-Telemetry metrics into OAP via OTLP receiver**.
As mentioned in the documentation, we need a MAL file to use the metrics for the OAP server and show the results in the UI.

**I tried to use the values.yaml file during HELM deploy in order to **create and add** my MAL file to /otel-rules directory** and start the OAP server with my new rules (adservice.yaml).

Here my OAP values.yaml configuration.
```
oap:
  antiAffinity: soft
  dynamicConfigEnabled: false
  envoy:
    als:
      enabled: false
  initEs: true
  javaOpts: -Xmx2g -Xms2g
  name: oap
  nodeAffinity: {}
  nodeSelector: {}
  ports:
    grpc: 11800
    rest: 12800
    zipkin: 9411
  replicas: 1
  resources: {}
  service:
    type: ClusterIP
  tolerations: []
  env:
    SW_OTEL_RECEIVER: default
    SW_RECEIVER_ZIPKIN: default
    SW_ZIPKIN_HTTP_COLLECTOR_ENABLED: true
    SW_OTEL_RECEIVER_ENABLED_HANDLERS: "otlp"
    SW_OTEL_RECEIVER_ENABLED_OTEL_RULES: "istio-controlplane,oap,vm,k8s/k8s-cluster,k8s/k8s-service,k8s/k8s-node,k8s/k8s-instance,adservice"
    SW_RECEIVER_METER: default
  config:
    otel-rules:
      adservice.yaml: |
        filter: "{ service.name == 'adservice' }" # The OpenTelemetry job name
        expSuffix: process.runtime.jvm
        metricPrefix: meter_vm
        metricsRules:
          #node cpu
          - name: cpu_total_percentage
            exp: (system.cpu.utilization * 100).rate('PT1M')
          - name: cpu_load1
            exp: system.cpu.load_1m * 100
          #node Memory
          - name: memory_used
            exp: memory.usage
  image:
    repository: skywalking.docker.scarf.sh/apache/skywalking-oap-server
    tag: 9.4.0  # Must be set explicitly
    pullPolicy: IfNotPresent
  storageType: "elasticsearch"
```

**The elasticsearch pod and OAP server pod failed to start because the adservice.yaml file is not found.**

I have alse tried with:

```
...
config:
    otel-rules/adservice.yaml: |
...
```

The same behavior was shown.

Thank you,
Luigi

**Comment by kezhenxu94** [comment]
Hi @lxx95 , your first attempt is correct, but because of how the Helm Chart mounts the files, the file name should become something like `otel-rules-adservice.yaml`, however, you can confirm this by looking into the generated manifests.

**Comment by lxx95** [comment]
Hi @kezhenxu94, thank you for the feedback..
You mean:
```
...
SW_OTEL_RECEIVER_ENABLED_OTEL_RULES: "istio-controlplane,oap,vm,k8s/k8s-cluster,k8s/k8s-service,k8s/k8s-node,k8s/k8s-instance,otel-rules-adservice"
    SW_RECEIVER_METER: default
  config:
    otel-rules:
      otel-rules-adservice.yaml: |
...
```
Same behavior:
```
2023-06-19 09:06:52,508 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 57 [main] ERROR [] - [9.5.0-d47165d] Some configuration files of enabled rules are not found, enabled rules: [otel-rules-adservice{.yaml,.yml}]
org.apache.skywalking.oap.server.core.UnexpectedException: Some configuration files of enabled rules are not found, enabled rules: [otel-rules-adservice{.yaml,.yml}]
```
Thank you.
