### DISCUSSION TITLE
skywalking monitor linux

### DISCUSSION THREAD

**Discussion by zz-zhi54** [apache/skywalking#11259] [Q&A] [answered]
https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-vm-monitoring/

I can't find in this document what should I do next

otelcol/prometheusreceiver 0.83.0： 
```log
2023-08-24T08:34:19.780Z        info    exporterhelper/queued_retry.go:423      Exporting failed. Will retry the request after interval.       {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.171:11800: i/o timeout\"", "interval": "6.662295239s"}
2023-08-24T08:34:23.518Z        info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 318, "data points": 875}
```

skywalking

```docker
 docker run --name oap --restart always -d \
 -e SW_STORAGE=elasticsearch -e LANG=zh_CN.UTF-8 -e LANGUAGE=zh_CN:en -e LC_ALL=zh_CN.UTF-8 \
 -p 11800:11800 -p 12800:12800 -m 1024m  \
 -e SW_STORAGE_ES_CLUSTER_NODES=192.168.1.173:9200 apache/skywalking-oap-server:9.5.0
```

What does this paragraph in the document want to express
```
receiver-otel:
  selector: ${SW_OTEL_RECEIVER:default}
  default:
    enabledHandlers: ${SW_OTEL_RECEIVER_ENABLED_HANDLERS:"otlp-metrics"}
    enabledOtelMetricsRules: ${SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES:"istio-controlplane"}
```

**Comment by zz-zhi54** [comment]
The first and second steps are fine. What should I do with the third part. can anyone help me

**Comment by zz-zhi54** [comment]
The default configuration I see is this. I don't understand the meaning of this at all, I can only rely on my guess

```yaml
receiver-otel:
  selector: ${SW_OTEL_RECEIVER:default}
  default:
    enabledHandlers: ${SW_OTEL_RECEIVER_ENABLED_HANDLERS:"otlp-metrics,otlp-logs"}
    enabledOtelMetricsRules: ${SW_OTEL_RECEIVER_ENABLED_OTEL_RULES:"apisix,k8s/*,istio-controlplane,vm,mysql/*,postgresql/*,oap,aws-eks/*,windows,aws-s3/*,aws-dynamodb/*,aws-gateway/*,redis/*,elasticsearch/*,rabbitmq/*"}
```
