### DISCUSSION TITLE
Support inject bootstrap-plugins by swck.

### DISCUSSION THREAD

**Discussion by weixiang1862** [apache/skywalking#11276] [Ideas]
swck now support inject optional-plugins and optional-report-plugins by SwAgent CRD or workload annotations. I want add supporting for bootstrap-plugins:

**SwAgent**
```
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: SwAgent
...
  optionalPlugins:
    - "webflux"
  bootstrapPlugins:          <-------------
    - "threadpool"
```
**workload annotation**
```
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      annotations:
        optional.skywalking.apache.org: "webflux"
        bootstrap.skywalking.apache.org: "threadpool"        <-------------
```
