### DISCUSSION TITLE
Add persistence option for storage crd in swck.

### DISCUSSION THREAD

**Discussion by weixiang1862** [apache/skywalking#11359] [Ideas]
Now es storage does not support data persistence, I want add persistence option for storage crd:
- persistence.path: the volumn mount path
- persistence.template: the volumeClaimTemplates of statefulset, define by corev1.PersistentVolumeClaimSpec

```
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: Storage
metadata:
  name: sample
spec:
  type: elasticsearch
  connectType: internal
  version: 7.5.1
  instances: 3
  image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  security:
    user:
      secretName: default
    tls: true
#----new add----#
  persistence:
    path: /usr/share/elasticsearch/data
    template:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
#----new add----#
```

after reconcile by controller, it will be apply as:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-elasticsearch
  namespace: default
spec:
  template:
    spec:
      containers:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/storage.p12
          name: cert
          subPath: storage.p12
#----new add----# 
        - mountPath: /usr/share/elasticsearch/data
          name: storage
#----new add----#
...
...
#----new add----#
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
      volumeMode: Filesystem
#----new add----#
```
