### DISCUSSION TITLE
skywalking  alarm settings MQE

### DISCUSSION THREAD

**Discussion by brave-programmer** [apache/skywalking#11422] [Q&A] [answered]
The same expression(MQE)：aggregate_labels(meter_vm_cpu_average_used,sum)
can obtain correct results on the dashboard, but errors occur in alarm configuration.

```yaml
rule config:
  cpu_average_used_rule:
    expression: sum(aggregate_labels(meter_vm_cpu_average_used{_='user'},sum) > 100) > 3
    period: 10
    count: 3
    silence-period: 5
    message: The cpu_average_used test.
```

error:
java.lang.IllegalArgumentException: org.apache.skywalking.mqe.rt.exception.IllegalExpressionException: Expression: sum(aggregate_labels(meter_vm_cpu_average_used{_='user'},sum) > 100) > 3 error: The result of expression [meter_vm_cpu_average_used{_='user'}] is not a labeled result.
