### DISCUSSION TITLE
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

### DISCUSSION THREAD

**Discussion by Charlotte3240** [apache/skywalking#11449] [General]
## env
mac m1 
mac os 14.0 (23A344)

## skywalking backend  docker compose
```yml
# https://skywalking.apache.org/downloads/
# /usr/local/bin/docker-compose -f /docs/dev-ops/skywalking/skywalking-docker-compose.yml up -d
version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - ./data/es_data:/usr/share/elasticsearch/data

  oap:
    image: apache/skywalking-oap-server:8.9.0
    container_name: oap
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms1024m -Xmx1024m"

  skywalking-ui:
    image: apache/skywalking-ui:8.9.0
    container_name: skywalking-ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "9090:8080"
    environment:
      SW_OAP_ADDRESS: http://10.93.149.13:12800
```

## python agent source code
```python
import argparse

from flask import Flask, request, jsonify
from skywalking import config as sw_config, agent
import logging

sw_config.init(
            # agent_collector_backend_services='docker.for.mac.localhost:11800',
            # agent_collector_backend_services='10.93.149.13:12800',
            agent_collector_backend_services='docker.for.mac.localhost:11800',
            agent_protocol='grpc',
            agent_authentication='',
            agent_name='dm-local-test',
            agent_meter_reporter_active=False,
            agent_log_reporter_active=False)
app = Flask(__name__)

agent.start()

logger = logging.getLogger("http")


@app.route('/test', methods=['GET'])
def test():
    logger.info("----------- hello world")
    return 'Hello, World!'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="localhost")
    parser.add_argument("--port", type=int, default=10000)

    args = parser.parse_args()


    app.run(debug=False, host=args.host, port=args.port)


```

## error
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:10000
Press CTRL+C to quit
2023-10-23 17:58:29,392 skywalking [pid:86409] [HeartbeatThread] [ERROR] Exception in heartbeat service in pid 86409, retry in 60 seconds
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/skywalking/agent/__init__.py", line 54, in backoff_wrapper
    flag = func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/skywalking/agent/__init__.py", line 310, in __heartbeat
    self.__protocol.heartbeat()
  File "/opt/homebrew/lib/python3.11/site-packages/skywalking/agent/protocol/grpc.py", line 79, in heartbeat
    self.service_management.send_instance_props()
  File "/opt/homebrew/lib/python3.11/site-packages/skywalking/client/grpc.py", line 43, in send_instance_props
    self.service_stub.reportInstanceProperties(InstanceProperties(
  File "/opt/homebrew/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for oap_host:oap_port: UNKNOWN: nodename nor servname provided, or not known"
        debug_error_string = "UNKNOWN:DNS resolution failed for oap_host:oap_port: UNKNOWN: nodename nor servname provided, or not known {created_time:"2023-10-23T17:58:29.389894+08:00", grpc_status:14}"
>
