### DISCUSSION TITLE
The remove stage is skipped

### DISCUSSION THREAD

**Discussion by abelzha** [apache/skywalking#11578] [Q&A]
![image](https://github.com/apache/skywalking/assets/32270905/18641fd7-854d-49c9-9f9a-01cf7adba226)

Version of OAP: 9.6.0-fb61128

In the cluster mode of k8s, the IP of the current Pod is 100.106.14.106, but it will still prompt The selected first getAddress is 100.106.14. 106_ 11800. The remove stage is skipped.

https://github.com/apache/skywalking/discussions/9634
I looked at this discussion, and the version I'm using has fixed the bug, so what do I need to check next?

**Comment by wu-sheng** [comment]
That was fixed long time ago.

Which coordinator are you using? I think you need to check the codes.

**Reply by abelzha** [reply]
```
          env:
            - name: SW_CLUSTER
              value: kubernetes
            - name: SW_CLUSTER_K8S_NAMESPACE
              value: 339-apm
            - name: SW_CLUSTER_K8S_LABEL
              value: k8s-app=skyoap
```
use k8s coordinator for k8s deployment.
base docker image: docker.io/apache/skywalking-oap-server:9.6.0

**Reply by wu-sheng** [reply]
I am not following. K8s coordinator should use UID rather than IP.

@hanahmily Any comment?

**Comment by kezhenxu94** [comment]
@abelzha how did you deploy the OAP cluster? Did you deploy with our Helm Chart?

**Reply by abelzha** [reply]
1.  I didn't use your Helm Chart.
2.  for some reason I made our own image based on this base image: docker.io/apache/skywalking-oap-server:9.6.0
3.  to configure some ENVs in k8s, set up the cluster of oap and the configuration of ES. and start 3 pod in k8s.

The configuration is as follows:
```
env:
  - name: SW_CLUSTER
    value: kubernetes
  - name: SW_CLUSTER_K8S_NAMESPACE
    value: 339-apm
  - name: SW_CLUSTER_K8S_LABEL
    value: k8s-app=skyoap
  - name: SW_STORAGE
    value: elasticsearch
  - name: SW_STORAGE_ES_CLUSTER_NODES
    value: elasticsearch*********.cn:9200
  - name: TZ
    value: Asia/Shanghai
  - name: SKYWALKING_COLLECTOR_UID
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.uid
  - name: SW_STORAGE_ES_CONNECT_TIMEOUT
    value: "20000"
  - name: SW_STORAGE_ES_RESPONSE_TIMEOUT
    value: "20000"
```
