### DISCUSSION TITLE
why my go project can not be trace

### DISCUSSION THREAD

**Discussion by cnzackliu** [apache/skywalking#11593] [Q&A] [answered]
```shell
go build -toolexec=/Users/zackliu/env/apache-skywalking-go-0.3.0-bin/bin/skywalking-go-agent-0.3.0-darwin-amd64 -a -o demo
export SW_AGENT_NAME=demo_20231127
./demo
```

Service has listed the demo，but page has no data when I click the search button .
Do I need to configure anything else?

<img width="1440" alt="image" src="https://github.com/apache/skywalking/assets/41176668/21acb1ea-4238-4aa0-935b-aaf4d06e9291">

main.go
```golang
package main

import (
	_ "github.com/apache/skywalking-go"
	"net/http"
)

func main() {
	http.HandleFunc("/hello", func(writer http.ResponseWriter, request *http.Request) {
		writer.Write([]byte("Hello World"))
	})
	err := http.ListenAndServe(":8000", nil)
	if err != nil {
		panic(err)
	}
}
```

docker-compose.yml
```yml
version: "3.7"

networks:
  skywalking:
    driver: bridge

services:
  elasticsearch:
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    # restart: always
    image: elasticsearch:7.6.2
    networks:
      - skywalking
    privileged: true
    ports:
      - 9200:9200
      - 9300:9300

  oap:
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    container_name: oap
    # restart: always
    image: apache/skywalking-oap-server:9.2.0
    networks:
      - skywalking
    privileged: true
    ports:
      - 11800:11800
      - 12800:12800

  oap-ui:
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
    container_name: oap-ui
    restart: always
    image: apache/skywalking-ui
    networks:
      - skywalking
    privileged: true
    ports:
      - 8080:8080
```

**Comment by wu-sheng** [comment, marked as answer]
You are using the 8.x, which is very old. Please pick the latest.
The error you posted looks like mismatch versions of UI and OAP servers.

**Reply by cnzackliu** [reply]
I pull the oap-server lastest image and change the elasticsearch , all the best !

```yml
version: "3.7"

networks:
  skywalking:
    driver: bridge

services:
  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    container_name: elasticsearch
    # restart: always
    image: elasticsearch:7.17.15
    networks:
      - skywalking
    privileged: true
    ports:
      - 9200:9200
      - 9300:9300

  oap:
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    container_name: oap
    # restart: always
    image: apache/skywalking-oap-server
    networks:
      - skywalking
    privileged: true
    ports:
      - 11800:11800
      - 12800:12800

  oap-ui:
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
    container_name: oap-ui
    restart: always
    image: apache/skywalking-ui
    networks:
      - skywalking
    privileged: true
    ports:
      - 8080:8080
```
