### DISCUSSION TITLE
I upgraded from 9.5 to 9.7, but the alarm silence period seems to be out of order

### DISCUSSION THREAD

**Discussion by Spinestars** [apache/skywalking#11690] [Q&A]
```yaml:
  endpoint_relation_resp_time_rule:
    expression: sum(endpoint_relation_resp_time > 5000) >= 2
    period: 10
    silence-period: 4320
    message: <font color=#FF0000> {name} </font> endpoint is too slow,  response > 5000ms，It will not trigger for 3 days.
    hooks:
      - "dingtalk.myding001"
```
As shown above, I set silence-period: 4320. But it didn't take effect, and just 1-2 hours later, the same endpoint triggered the alarm notification again.
