### DISCUSSION TITLE
In 9.7, how can the custom Webhook mode be configured in alarm-settings?

### DISCUSSION THREAD

**Discussion by Spinestars** [apache/skywalking#11722] [Q&A] [answered]
https://skywalking.apache.org/docs/main/v9.7.0/en/setup/backend/backend-alarm/#webhook
---
In the above document, only the json data format is mentioned, not the configuration writing.
---
I copied Slack Chat and modify. But it(http://myalert.xyz.com) did not receive any requests.

```yaml
rules:
  endpoint_abnormal_500_rule:
    expression: sum(endpoint_abnormal_count_500 >= 3) >= 2
    period: 2
    silence-period: 600
    message: {name} is 500.
    tags:
      level: WARNING
    hooks:
      - "webhook.myalert001"
hooks:
  webhook:
    myalert001:
      is-default: false
      webhooks:
      - http://myalert.xyz.com
```
