### DISCUSSION TITLE
How should map structure be written in yaml file of e2e test verification?

### DISCUSSION THREAD

**Discussion by xiaokuncom** [apache/skywalking#11811] [Q&A]
I wrote an e2e test with reference to the test case of skywalking, but I didn't find the corresponding writing method after encountering the map structure. How to write this?
The following is about the map part.
```
    expandMap:
    {{- contains .expandMap }}
    - key: title
      value: {{ regexp .value ".*test.*" }}
    - key: content
      value: {{ regexp .value ".*test.*" }}
    {{- end }}
```
But this is the wrong way to write.
```
executing "test" at <.value>: can't evaluate field value in type interface {}
```
