### DISCUSSION TITLE
Skywalking go: click `相关的日志` , throw `Exception while fetching data (/queryLogs) : null`

### DISCUSSION THREAD

**Discussion by fzdwx** [apache/skywalking#11826] [Q&A] [answered]
I started two go services and registered them on skywalking. One of the services will call the other service and print some logs in the process. When I click on `相关的日志`, an `Exception while fetching data will be thrown. (/queryLogs) : null`

env:
```shell
zap v1.26.0
skywalking-go v0.3.0
gin v1.9.1
kratos/v2 v2.7.0
```
trace id : `9b07ea97ba5511eea058581122d149f6.22.39178123900080001`

![image](https://github.com/apache/skywalking/assets/65269574/c0bd5e08-d7a6-488c-bf99-65b41d4280e1)
![image](https://github.com/apache/skywalking/assets/65269574/a39548d6-ab0e-4faf-be9c-33a304649dec)

log tab:

![image](https://github.com/apache/skywalking/assets/65269574/882596d0-9e2a-4b3a-94f7-f18e021d93a1)

![image](https://github.com/apache/skywalking/assets/65269574/8075f2b2-6826-4a37-a1b3-5259b1639e84)

[code](https://github.com/fzdwx/go-skywalking-sample)

```sh
curl localhost:8888/helloworld/go-agent
```

**Comment by fzdwx** [comment]
docker-compose.yaml

```yaml
version: '3.3'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
 
  skywalking-oap:
    image: apache/skywalking-oap-server:9.7.0
    container_name: skywalking-oap
    restart: always
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_CORE_RECORD_DATA_TTL: 7 #记录数据的有效期，单位天
      SW_CORE_METRICS_DATA_TTL: 7 #分析指标数据的有效期，单位天
      SW_ENABLE_UPDATE_UI_TEMPLATE: "true" # 开启dashboard编辑修改功能
      SW_HEALTH_CHECKER: default
      TZ: Asia/Shanghai
      SW_STORAGE: postgresql
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
      #SW_STORAGE: elasticsearch7
      SW_JDBC_URL: "jdbc:postgresql://postgresql:5432/skywalking"
    #volumes:
      #- ./config:/skywalking/config
 
  skywalking-ui:
    image: apache/skywalking-ui:9.3.0
    #image: apache/skywalking-ui:9.0.0
    container_name: skywalking-ui
    restart: always
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    ports:
      - 18080:8080
    environment:
      TZ: Asia/Shanghai
      SW_HEALTH_CHECKER: default
      SW_OAP_ADDRESS: http://skywalking-oap:12800
```
