### DISCUSSION TITLE
Unable to send OTEL traces from OTEL Collector (OTEL-Contrib) to SkyWalking using OTLP or SkyWalking Exporter

### DISCUSSION THREAD

**Discussion by AmythD** [apache/skywalking#11873] [Q&A] [answered]
Hello,

I am attempting to send native OTEL traces from my application to SkyWalking through an OpenTelemetry Collector. I have tested using two different exporters to send traces to SkyWalking backend but still observing errors on the collector logs. Any ideas on how I can send native OTEL traces to SkyWalking backend and what exporters I should be using?

**Using OTLP exporter :**

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
   
exporters:
  otlp:    
    endpoint: "x.x.x.x:11800"
    tls:
     insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]
```
**ERROR:**

`2024-02-06T05:13:30.744Z        error        exporterhelper/common.go:95        Exporting failed. Dropping data.        {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.trace.v1.TraceService/Export", "dropped_items": 1}`

**Using SkyWalking Exporter:**

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
   
exporters:
  skywalking:
    endpoint: "10.223.16.116:11800"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [skywalking]
      processors: [batch]
```

**ERROR OTEL Collector does not start:**

`2024/02/06 06:49:12 collector server run finished with error: failed to build pipelines: failed to create "skywalking" exporter for data type "traces": telemetry type is not supported`
