### DISCUSSION TITLE
alarm is inaccurate

### DISCUSSION THREAD

**Discussion by unihon** [apache/skywalking#11893] [Q&A]
skywalking version: 9.7.0
> alarm config
```
  service_resp_time_percentile_rule:
    expression: sum(service_percentile{_='3'} > 500) >= 3
    period: 10
    silence-period: 30
    message: Percentile response time of service `{name}` alarm in 3 minutes of last 10 minutes, due to more than one condition of p95 > 500ms
```

![企业微信截图_17083940024101](https://github.com/apache/skywalking/assets/42078581/fc340a4b-bb10-4d90-aeda-7cc5aed06484)
![企业微信截图_17083960816323](https://github.com/apache/skywalking/assets/42078581/6962a388-b82d-4a79-9cf0-36b32da1fc4f)

During the alarm duration, the delay of p95 did not reach 500ms.
