### DISCUSSION TITLE
OAP server run with mysql start failed.

### DISCUSSION THREAD

**Discussion by OrezzerO** [apache/skywalking#12158] [Q&A]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I try to run oap server in docker with mysql as storage. Here is my  docker  compose file:
```yml
version: '2.1'

services:
  oap:
    image: apache/skywalking-oap-server:9.6.0-java17
    networks:
      - skywalking
    environment:
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES: vm
      TZ: Asia/Shanghai
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://xxx:3306/sw
      SW_DATA_SOURCE_USER: xxxx
      SW_DATA_SOURCE_PASSWORD: xxxx
      JAVA_OPTS: -Xms4G -Xmx4G
    volumes:
      - ./mysql-connector-j-8.0.32.jar:/skywalking/oap-libs/mysql-connector-j-8.0.32.jar

    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"

  oap-ui:
    image: apache/skywalking-ui:9.6.0-java17
    networks:
      - skywalking
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      JAVA_OPTS: -Xms2G -Xmx2G
    ports:
      - "8080:8080"

networks:
  skywalking:

```
I create a database  `sw` in mysql . When i run   `docker compose up` , oap log says `SELECT command denied to user 'xxxx'@'xxx' for table 'xxxx'`. 

Each time when i run `docker compose up` table name changes.  I go to mysql and check. table exists.  It seems that select command is executed async and  before table is created. 

Now I am running  `docker compose up` and  `docker compose down`  repeatedly. Each round can create one or two new table .

### What you expected to happen

1. Tables can be created once .and i do not need to restart container.

### Logs Sample 
```
oap-1     | 2024-04-24 16:44:27,236 org.apache.skywalking.oap.server.starter.OAPServerBootstrap 57 [main] ERROR [] - [9.6.0-fb61128] SELECT command denied to user 'wattsonic_sw_op'@'172.20.45.165' for table 'tag_autocomplete_20240424'
oap-1     | java.sql.SQLSyntaxErrorException: SELECT command denied to user 'wattsonic_sw_op'@'172.20.45.165' for table 'tag_autocomplete_20240424'
oap-1     |     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2745) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2732) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2802) ~[mysql-connector-j-8.0.32.jar:8.0.32]
oap-1     |     at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCClient.indexExists(JDBCClient.java:155) ~[library-client-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.JDBCTableInstaller.createOrUpdateTableIndexes(JDBCTableInstaller.java:153) ~[storage-jdbc-hikaricp-plugin-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.JDBCTableInstaller.createTable(JDBCTableInstaller.java:99) ~[storage-jdbc-hikaricp-plugin-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.JDBCTableInstaller.createTable(JDBCTableInstaller.java:92) ~[storage-jdbc-hikaricp-plugin-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.core.storage.model.ModelInstaller.whenCreating(ModelInstaller.java:55) ~[server-core-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.core.storage.model.StorageModels.addModelListener(StorageModels.java:141) ~[server-core-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.storage.plugin.jdbc.common.JDBCStorageProvider.start(JDBCStorageProvider.java:247) ~[storage-jdbc-hikaricp-plugin-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:46) ~[library-module-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:60) ~[library-module-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-starter-9.6.0.jar:9.6.0]
oap-1     |     at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-9.6.0.jar:9.6.0]

```

### How to reproduce

run my docker compose 

### Question 
1.  What's wrong with it ?  Is it a bug ? 
2. How to deal with it? 
3. some table is related to date like `tag_autocomplete_20240424`,  is it possible that it can happen in every day ?
