### DISCUSSION TITLE
how to use process functon in MAL

### DISCUSSION THREAD

**Discussion by devin-wanghuixiong** [apache/skywalking#12313] [Q&A]
meter toolkit:
```
counter = MeterFactory.counter("biz_count")
                        .tag("schema", "s1")
                        .tag("module", "m1")
                        .tag("operation", "create")
                        .tag("result", "C0909")
                        .mode(Counter.Mode.INCREMENT)
                        .build();
counter.increment(1D);
```

add layer in server-core
```
CUSTOMER(101, true);
```

MAL:
```
expPrefix: tag({tags -> tags.service = tags['schema']}).tag({tags -> tags.instance = tags['module']}).tag({tags -> tags.layer='CUSTOMER'})
expSuffix: process(['service'], ['instance'], ['operation'], 'layer')
metricPrefix: meter_process
metricsRules:
  # 总请求数
  - name: biz_count
    exp: biz_count.sum(by=['service','instance','operation', 'layer']).increase("PT1M")
```

UI config
![image](https://github.com/apache/skywalking/assets/43465381/8ee6f43b-4cc6-4582-81f9-0a7a27c51b38)

problem：no data in PROCESS
![image](https://github.com/apache/skywalking/assets/43465381/a584dc88-0028-4bd3-bed8-8c4a82766694)
