### DISCUSSION TITLE
Consul is not working with Skywalking

### DISCUSSION THREAD

**Discussion by haider665** [apache/skywalking#12403] [Q&A]
I have a spring boot microservice with consul as service discovery. I tried to follow this [link](https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-cluster/#consul) to use consul with skywalking. When oap server is trying to register in consul, it shows this error message "Invalid service address". 

Here is the docker compose file and output screenshot

```
version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    healthcheck:
      test: "consul info | awk '/health_score/{if ($3 >=1) exit 1; else exit 0}'"
      interval: 10s
      timeout: 10s
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

  oap:
    image: apache/skywalking-oap-server:10.0.0
    container_name: oap
    depends_on:
      elasticsearch:
        condition: service_healthy
      consul:
        condition: service_healthy
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/11800" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      SW_CLUSTER: consul
      SW_SERVICE_NAME: oap
      SW_CLUSTER_CONSUL_HOST_PORT: consul:8500
      JAVA_OPTS: "-Xms2048m -Xmx2048m"

  ui:
    image: apache/skywalking-ui:10.0.0
    container_name: ui
    depends_on:
      oap:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      SW_ZIPKIN_ADDRESS: http://oap:9412
```

![consul-skywalk](https://github.com/apache/skywalking/assets/24691495/cf7e66a1-eeb2-4b75-88f4-fe24b21c387d)
