### DISCUSSION TITLE
Group Parameterized Endpoints NOT WORK on SwCallableWrapper

### DISCUSSION THREAD

**Discussion by yqjdcyy** [apache/skywalking#12524] [Q&A]
# What's happend

Oap(v9.4.0) write too much metric to es.
After analyze the mapping of `es.metrics` on the layers of service+ metric+ endpoint, `endpoint_`* metrics start with `SwCallableWrapper/pool-*` take up most.
Part of data for reference.
```sh
endpoint_cpm	                        6304941
instance_jvm_class_loaded_class_count	2862

## random data* 500 hit the prefix of `SwCallableWrapper/pool-`
U3dDYWxsYWJsZVdyYXBwZXIvcG9vbC0yMzg3MzYyMTktdGhyZWFkLTE=
    SwCallableWrapper/pool-238736219-thread-1
U3dDYWxsYWJsZVdyYXBwZXIvcG9vbC0xMTMwODMwNzQtdGhyZWFkLTE=
```

`Group Parameterized Endpoints/ Custom Configuration` seem works for me,but something wrong.

# How i try

Setting oap configuration work with nacos and init the setting `core.default.endpoint-name-grouping`
```yml
grouping:
 - service-name: test1::domain
   rules:
  #  pass by test EndpointGroupingRuleReaderTest#testReadingRule
     - endpoint-name: SwCallableWrapper-domain
       regex: .*SwCallableWrapper\/pool.*
     - endpoint-name: SwCallableWrapper-domain-2
       regex: SwCallableWrapper\/pool-.*
     - endpoint-name: management-actuator
       regex: .*\/management\/actuator\/.*
```

and `management-actuator` WORKS but `SwCallableWrapper-domain.*` DOES NOT.
follow the code about `NamingControl#formatEndpointName`, found that without limit or filters.

# Ask for Help
Do i miss something about it?
