### DISCUSSION TITLE
[Bug] Use Helm install Skywalking , but got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.

### DISCUSSION THREAD

**Discussion by freshgeek** [apache/skywalking#12602] [Q&A] [answered]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Use Helm install Skywalking  （ https://github.com/apache/skywalking-helm ）, but got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later. 

got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.  
and oap  server is   unavailable  

### What you expected to happen

According to the document, it can run step by step and the service is available

Or can you provide methods or ideas for me to solve on my own

### How to reproduce

my env :
- k8s v1.28.11
- rancher v2.9.1
- helm v3.15.2 

helm values : 

```
elasticsearch:
  config:
    password: hide
    user: admin
  ingress:
    enabled: true
    hosts:
      - es.hide
  persistence:
    enabled: true
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi    
oap:
  dynamicConfig:
    enabled: true
  image:
    repository: apache/skywalking-oap-server
    tag: 10.0.1
  storageType: elasticsearch
ui:
  image:
    repository: apache/skywalking-ui
    tag: 10.0.1
  ingress:
    enabled: true
    hosts:
      - sky-ui.hide

```

### Anything else

I searched for recent issues and discussions and found that it keeps mentioning init job. I observed that there was no init job generated and running during the installation process of helm (I cannot know if it failed to create or was created and then deleted)
- https://github.com/apache/skywalking/issues/11123
- https://github.com/apache/skywalking/issues/10540
- https://github.com/apache/skywalking/issues/10470
- https://github.com/apache/skywalking/issues/9486
- https://github.com/apache/skywalking/pull/8958
- https://github.com/apache/skywalking/discussions/9093

There is no mention of how to troubleshoot or solve the problem

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by freshgeek** [comment]
And I have tried again multiple times, but still the result is the same. I don't know how to solve or troubleshoot it

**Comment by wu-sheng** [comment]
As it was talked so many times, I don't know what to say, or what more you expected.

**Comment by wu-sheng** [comment]
You at least check pod logs, init container logs, how you run. Showcase provided very straightforward, and architecture is super simple.

**Comment by freshgeek** [comment]
Of course, these checks have been done, including es pod oap-pod、ui-pod）， I think these issues are not just one sentence, but contain various environmental information for reproduction.

For open source providers, it may be a simple knowledge, but for newcomers who are new to it, they may not know it. As a leader, they may need to identify the current situation caused by documents or other factors

**Reply by wu-sheng** [reply]
For open source, we don't have obligation. What you said only makes no sense.

We don't provide commercial service. We don't charge anything. Don't you should try your best to check what it is?
If you feel too much, why bother us.

**Reply by freshgeek** [reply]
> For open source, we don't have obligation. What you said only makes no sense.
> 
> We don't provide commercial service. We don't charge anything. Don't you should try your best to check what it is? If you feel too much, why bother us.

Perhaps you have negative emotions in communication

I believe that open source is about users providing positive feedback; Open source developers actively provide assistance;

 If you don't consider providing assistance, you can choose not to reply
 
Alse `too much` just means  `users providing positive feedback`

**Comment by kezhenxu94** [comment]
It might be that Rancher doesn’t respect the Helm hooks. We didn’t test on Rancher, please consult the Rancher community

**Comment by freshgeek** [comment, marked as answer]
There is a bug that cannot be executed here, and I have been researching for two days without finding it.

Since it cannot execute automatically, if needed in a short period of time, you can manually create a job to execute（ https://github.com/apache/skywalking-helm/blob/master/chart/skywalking/templates/oap-init.job.yaml ）

**Reply by freshgeek** [reply]
this is my demo：
```
apiVersion: batch/v1
kind: Job
metadata:
  name: skywalking-skywalking-helm-oap-job
  namespace: default
spec:
  selector:
    matchLabels:#  key: string
  template:
    metadata:
      namespace: default
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: init-job
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
          _init: false
          __active: true
          image: harbor.nb.xingyunyfs.com/docker/apache/skywalking-oap-server:10.0.0
          env:
            - name: JAVA_OPTS
              value: '-Dmode=init -Xmx2g -Xms2g'
            - name: SW_STORAGE
              value: elasticsearch
            - name: SW_STORAGE_ES_CLUSTER_NODES
              value: es-kibana-elasticsearch:9200
      affinity:
      imagePullSecrets:
      initContainers:
      restartPolicy: Never
      serviceAccount: skywalking-skywalking-helm-oap
      serviceAccountName: skywalking-skywalking-helm-oap
      volumes:
  replicas: 1

```
