### DISCUSSION TITLE
[Bug] Unable to register Log4j shutdown hook

### DISCUSSION THREAD

**Discussion by qianghong000** [apache/skywalking#12810] [Q&A]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

The OAP service restarts frequently many times before it returns to the normal state
The OAP service logs are as follows：
2024-11-29 07:30:29,578 Thread-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

### What you expected to happen

The OAP service can be in the READY status without restarting

### How to reproduce

Deploy via the https://github.com/apache/skywalking-helm/tree/master link

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
This is just a warning, it would not affect the booting.

**Comment by qianghong000** [comment]
The restart event is：Container oap failed liveness probe, will be restarted

I tried to modify the health check time via the：` --set oap.livenessProbe.initialDelaySeconds=60 --set oap.livenessProbe.periodSeconds=60 `command argument, but it was useless

![image](https://github.com/user-attachments/assets/a548c7a6-a072-41d4-b7ba-ada3a8579ad0)

**Reply by wu-sheng** [reply]
You could change the log level of OAP to DEBUG, and see what is happening.

**Comment by qianghong000** [comment]
I modified the values.yaml configuration and couldn't change it to the DEBUG log level。
```
oap:
  name: oap
  image:
    tag: null
  storageType: elasticsearch
  ports:
    grpc: 11800
    rest: 12800
  replicas: 2
  nodeSelector:
    role: apm
  config:
    log4j2.xml: |
     <Configuration status="DEBUG">
       <!-- ... -->
     </Configuration>
```
