### DISCUSSION TITLE
Custom Metric Rule Not Triggering Despite Valid Values

### DISCUSSION THREAD

**Discussion by angryxie** [apache/skywalking#12932] [Q&A] [answered]
Description
I created a custom metric and confirmed that it is generating values correctly in the UI. However, the alarm rule associated with this metric does not trigger as expected. Below are the details of the configuration and observations:

Steps to Reproduce
metric define: `endpoint_latency_2s = from(Endpoint.*).filter(latency > 2000).count();`

rule define: 
``` 
    slow_request_rule:
    expression: sum(endpoint_latency_2s) >= 2
    period: 1
    silence-period: 1
    message: 请求节点1分钟大于2S的请求数达到5-{name}
    hooks:
      - "webhook.local-hook"
```

ensure configurations are loaded correctly
```
2025-01-06 06:33:57,012 org.apache.skywalking.oap.server.core.alarm.provider.AlarmRulesWatcher 134 [Apollo-Config-1] INFO  [] - Update alarm rules to Rules(rules=[AlarmRule(alarmRuleName=slow_request_rule, expression=sum(endpoint_latency_2s) >= 2, includeMetrics=[endpoint_latency_2s], includeNames=[], includeNamesRegex=, excludeNames=[], excludeNamesRegex=, period=1, silencePeriod=1, message=请求节点1分钟大于2S的请求数达到5-{name}, tags={}, hooks=[webhook.local-hook], maxTrendRange=0)]
```
Environment
+ OAP Version: 10.1.0
+ UI Version: 10.1.0
+ Java-agent: 8.16.0

Screenshots
<img width="745" alt="8AF279FB-1D70-4ABD-A7B6-C5AAB7730152" src="https://github.com/user-attachments/assets/393a0908-969c-4db9-a303-ab53027a4101" />
<img width="1872" alt="662D14AA-E38C-47AB-9FF4-41D18E652CF6" src="https://github.com/user-attachments/assets/22d4b570-93ec-42c4-b439-5b942a22c2a1" />

Thank You
Thank you for providing this powerful monitoring tool and for your support. Looking forward to your feedback!
