### DISCUSSION TITLE
How to customize alarm information

### DISCUSSION THREAD

**Discussion by FeiYuJun** [apache/skywalking#13001] [Q&A]
Similar to {name} in the example, I would like to add more information to the alarm, such as: TID. How to make the change?

## version
skywalking 9.2.0

## alarm-settings.yml
```yaml
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
...
```
