### DISCUSSION TITLE
Request for Updated Blogs on SkyWalking Rover for Kubernetes Application Profiling

### DISCUSSION THREAD

**Discussion by KHADEPALLAVI975** [apache/skywalking#13202] [Q&A]
Hi community,
I'm currently exploring CPU profiling for Kubernetes applications using Rover, and I'm particularly interested in integrating the latest version of Apache SkyWalking to enhance observability in production environments.
Based on concepts from Brendan Gregg's work, we're looking to implement:
On-CPU Profiling: Understanding where threads spend time actively running.
Off-CPU Profiling: Tracking time spent waiting (I/O, locks, timers, etc.).
We're also delving into eBPF-based profiling of Envoy, especially in service mesh setups like Istio, where Envoy acts as a sidecar proxy. Since performance issues in Envoy can impact all mesh traffic, this type of profiling is crucial for uncovering hidden bottlenecks.
What I need help with:
I'm looking for updated blogs, guides, or examples that demonstrate how to use the latest version of SkyWalking in conjunction with Rover for profiling in Kubernetes environments.
If anyone has:
Recent blog posts or tutorials
GitHub repos 
Real-world case studies or experience reports
…please share them here! I'd greatly appreciate any direction or resources you can offer 🙏
Thanks in advance!

**Comment by wu-sheng** [comment]
There may help.
- https://skywalking.apache.org/blog/2023-06-25-intruducing-continuous-profiling-skywalking-with-ebpf/
- https://skywalking.apache.org/blog/diagnose-service-mesh-network-performance-with-ebpf/
- https://skywalking.apache.org/blog/2022-07-05-pinpoint-service-mesh-critical-performance-impact-by-using-ebpf/

**Reply by KHADEPALLAVI975** [reply]
HI @wu-sheng  

These blogs are older which refers   `SkyWalking Rover version 0.3.0 ` 

Here we are trying with latest skywalking OAP - 10.1.0 which needs the SkyWalking Rover version 0.6.0 and upper 

With respect to that i am not able to find any blogs or guides

**Reply by wu-sheng** [reply]
There is no newer blog. Blogs are not written for every release/update.

**Reply by wu-sheng** [reply]
The UI interaction is similar, and showcase has all deployment automatically, as same as our demo.

I am not sure what you are looking, there is not much manually setup.

**Reply by wu-sheng** [reply]
https://skywalking.apache.org/docs/skywalking-showcase/next/readme/

These work on GCP k8s simply. All things are set.

**Reply by KHADEPALLAVI975** [reply]
I have tried every Helm setup as well as the SkyWalking showcase setup, but I am still unable to get the CPU profiling graphs using the latest version of SkyWalking Rover.

There are no clear guides or blogs that explain the dependencies or prerequisites. Additionally, there are no proper blogs related to the latest release of eBPF profiling, which makes it difficult to debug and understand the setup.


The Rover logs are attached here.
![image](https://github.com/user-attachments/assets/3817368e-887e-41b1-aacf-ec353f033da0)

**Reply by wu-sheng** [reply]
We don't do any extra step in the GCP env. We are still not sure why this happens at your end.

**Comment by wu-sheng** [comment]
The https://skywalking.apache.org#demo has the showcase deployment, and profiling is automatically triggered and running.

You could see details from this page(k8s service monitoring powered by Rover latest version).
https://demo.skywalking.apache.org/dashboard/MESH/Service/bWVzaC1zdnI6OnNvbmdzLnNhbXBsZS1zZXJ2aWNlcw==.1/Mesh-Service

`songs.sample-service` is being profiled a lot of times.
![image](https://github.com/user-attachments/assets/a24fcf72-3033-479b-a3aa-26a2dbeac87a)

**Reply by KHADEPALLAVI975** [reply]
I am currently using the following kernel and OS. Does this setup look suitable for SkyWalking profiling?
```
kernel - 6.8.0-57-generic
OS - 22.04.1-Ubuntu 
```
In the current setup, profiling jobs are not being triggered automatically. As a workaround, I am triggering them manually using the following command:
`kubectl create job --from=cronjob/ebpf-profiling-trgigger ebpf-trigger-manual-$(date +%s) -n sample-services`


I have attached the resource.yaml file, where we define rules for process discovery. Do we need to make any changes to identify the process related to the sample-services deployment? Currently, I am unable to see any processes associated with the songs deployment.

```
{{- if .Values.features.rover.enabled}}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rover-daemonset
  labels:
    app: rover
spec:
  selector:
    matchLabels:
      app: rover
  template:
    metadata:
      labels:
        app: rover
    spec:
      serviceAccountName: skywalking-rover-sa
      containers:
        - name: rover
          image: {{ .Values.features.rover.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
          env:
            - name: ROVER_LOGGER_LEVEL
              value: DEBUG
            - name: ROVER_PROCESS_DISCOVERY_KUBERNETES_ACTIVE
              value: "true"
            - name: ROVER_PROCESS_DISCOVERY_KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ROVER_BACKEND_ADDR
              value: {{ template "skywalking.collector.address" . }}
            - name: ROVER_PROCESS_DISCOVERY_KUBERNETES_ANALYZER_ISTIO_ENVOY_SERVICE_NAME
              value: mesh-svr::{{"{{"}}.Pod.LabelValue "service.istio.io/canonical-name,app.kubernetes.io/name,app" ""{{"}}"}}.{{"{{"}}.Pod.Namespace{{"}}"}}
            - name: ROVER_PROCESS_DISCOVERY_KUBERNETES_ANALYZER_ISTIO_APPLICATION_SERVICE_NAME
              value: mesh-svr::{{"{{"}}.Pod.LabelValue "service.istio.io/canonical-name,app.kubernetes.io/name,app" ""{{"}}"}}.{{"{{"}}.Pod.Namespace{{"}}"}}
            - name: ROVER_PROCESS_DISCOVERY_KUBERNETES_ANALYZER_K8S_SERVICE_NAME
              value: skywalking-showcase::{{"{{"}}.Pod.ServiceName{{"}}"}}.{{"{{"}}.Pod.Namespace{{"}}"}}
            - name: ROVER_HOST_MAPPING
              value: /host
            - name: ROVER_CORE_CLUSTER_NAME
              value: skywalking-showcase
            - name: ROVER_ACCESS_LOG_ACTIVE
              value: "false"
            - name: ROVER_ACCESS_LOG_EXCLUDE_NAMESPACES
              value: gmp-system,kube-system,{{.Release.Namespace}}
            - name: ROVER_ACCESS_LOG_EXCLUDE_CLUSTER
              value: mesh-svr
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: host
          hostPath:
            path: /
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory


{{- end }}
```
