### DISCUSSION TITLE
SkyWalking Go Agent fails to connect to OAP service due to version incompatibility

### DISCUSSION THREAD

**Discussion by fzr365** [apache/skywalking#13304] [Q&A] [answered]
# SkyWalking Go Agent fails to connect to OAP service due to version incompatibility

## Problem Description

The Go application using SkyWalking Go Agent fails to connect to the OAP service. Although network connectivity tests are successful, the Agent consistently attempts to connect to `127.0.0.1:11800` and throws the following error:

```
skywalking-go 2025/06/07 08:17:17 open stream error rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:11800: connect: connection refused"
```

## Environment Information

- SkyWalking OAP Version: 9.7.0
- SkyWalking Go Agent Version: 0.5.0
- Go Version: 1.23.0 (inside container)
- Docker Version: Latest
- OS: Windows 10 (host)

## Steps to Reproduce

1. Deploy SkyWalking OAP and UI services via Docker Compose:
```yaml
services:
  skywalking-oap:
    image: apache/skywalking-oap-server:9.7.0
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      - SW_REST_ENABLED=true
      - SW_STORAGE=h2
      - SW_H2_STORAGE_EMBEDDED=true
    volumes:
      - oap-data:/skywalking/oap-libs/h2

  skywalking-ui:
    image: apache/skywalking-ui:9.7.0
    ports:
      - "8081:8080"
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap:12800
    depends_on:
      - skywalking-oap

volumes:
  oap-data:
```

2. Build and deploy the Go application (Dockerfile):
```dockerfile
FROM apache/skywalking-go:0.5.0-go1.23

WORKDIR /app

ENV GOPROXY=https://goproxy.cn,direct

COPY . .

RUN env GOPROXY=$GOPROXY skywalking-go-agent -inject /app
RUN env GOPROXY=$GOPROXY go build -toolexec="skywalking-go-agent" -o my-app .

RUN rm -f skywalking.yaml skywalking_inject.go

EXPOSE 8080

CMD ["./my-app", "-agent.opts=-Dskywalking.oap.address=skywalking-oap:11800"]
```

3. After starting the services, the Go application continuously reports connection failure to `127.0.0.1:11800`.

### Go Application Logs
```
SW_OAP_ADDRESS: skywalking-oap:11800
Starting server on :8080
skywalking-go 2025/06/07 08:05:23 open stream error rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:11800: connect: connection refused"
skywalking-go 2025/06/07 08:05:23 report serviceInstance properties error rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:11800: connect: connection refused"
skywalking-go 2025/06/07 08:05:23 fetch dynamic configuration error rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:11800: connect: connection refused"
```

### Network Connectivity Test
```bash
# Test connectivity inside the container
ping skywalking-oap -c 3
# Output:
PING skywalking-oap (172.19.0.3) 56(84) bytes of data.
64 bytes from sky1-skywalking-oap-1.sky1_default (172.19.0.3): icmp_seq=1 ttl=64 time=0.138 ms

telnet skywalking-oap 11800
# Output:
Trying 172.19.0.3...
Connected to skywalking-oap.
```

## Possible Cause

Based on troubleshooting, the issue is likely caused by **version incompatibility**:
- SkyWalking OAP 9.7.0 requires Go Agent version >= 0.11.0
- The current Agent version (0.5.0) is incompatible with OAP 9.7.0

## Tried Solutions

1. Explicitly configured Agent startup parameters to specify the OAP address:
```dockerfile
CMD ["./my-app", "-agent.opts=-Dskywalking.oap.address=skywalking-oap:11800"]
```

2. Verified network connectivity, confirming service-to-service resolution and port connection.

3. Modified environment variables, cleared caches, reset Docker networks, etc.

## Expected Solutions

1. Clarify the version compatibility between SkyWalking OAP and Go Agent, and update official documentation.
2. Provide high-version Agent Docker images (e.g., `apache/skywalking-go:0.13.0-go1.23`) that include the latest Go version (e.g., go1.23).
3. Fix potential localhost hardcoding issues in lower-version Agents.

## Additional Information

- Does the `apache/skywalking-go` image on Docker Hub have tags for high versions (e.g., 0.13.0) that include go1.23?
- Does the official documentation have a version mapping table for OAP and Agent? Such a table was not found in current docs.

Thank you for your assistance!
