### DISCUSSION TITLE
V8.7: Logback collects fewer logs than local files

### DISCUSSION THREAD

**Discussion by xiaogangfighting** [apache/skywalking#7718] [Q&A]
Spirngboot + logback integrates the skywalking log system. It is found that the number of logs collected by skywalking does not match the number of local logs, skywalking records much less, and oapserver / agent does not report error information。
thanks & best regards.

![image](https://user-images.githubusercontent.com/5702303/133396998-841ed4af-9dd9-4050-a346-8fc4b14c29b6.png)

**Comment by wu-sheng** [comment]
I think this description is too abstract for us to response. It is better for you to use a simple codebase and verify which logs are missed.
We don't filter logs in default actually.

**Comment by xiaogangfighting** [comment]
The log is much less than it is
![image](https://user-images.githubusercontent.com/5702303/133540800-1b60f2d6-8b0f-430a-a596-87c28fe0252c.png)

agent.conf:
`plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:10.192.10.250}
plugin.toolkit.log.grpc.reporter.server_port=${SW_GRPC_LOG_SERVER_PORT:51800}
plugin.toolkit.log.grpc.reporter.max_message_size=${SW_GRPC_LOG_MAX_MESSAGE_SIZE:1048576000}
plugin.toolkit.log.grpc.reporter.upstream_timeout=${SW_GRPC_LOG_GRPC_UPSTREAM_TIMEOUT:30}`

**Reply by wu-sheng** [reply]
Comparing details, the page number is meaningless. We are even going to delete the whole page number, due to it is not accurate at all, especially for ElasticSearch.

**Reply by JerryGitHubAccount** [reply]
hi, i have done a test below with skywalking oap 10.0.1 ,agent 9.3.0 .
when log is bigger ,i can not find logs in skywalking ui.
can you give me any suggestions? thanks !

**Comment by JerryGitHubAccount** [comment]
@xiaogangfighting @wu-sheng 
I have done a test, with spring boot 3.3.2+ logback
agent.conf
`
plugin.toolkit.log.grpc.reporter.server_host=${SW_GRPC_LOG_SERVER_HOST:127.0.0.1}
plugin.toolkit.log.grpc.reporter.server_port=${SW_GRPC_LOG_SERVER_PORT:11800}
plugin.toolkit.log.grpc.reporter.max_message_size=${SW_GRPC_LOG_MAX_MESSAGE_SIZE:52428800}
plugin.toolkit.log.grpc.reporter.upstream_timeout=${SW_GRPC_LOG_GRPC_UPSTREAM_TIMEOUT:30}
`
oap application.yaml
```yaml
receiver-sharing-server:   
  default:    
    # 修改 maxMessageSize: ${SW_RECEIVER_GRPC_MAX_MESSAGE_SIZE:0}
    maxMessageSize: ${SW_RECEIVER_GRPC_MAX_MESSAGE_SIZE:52428800}
configuration:    
  grpc:    
    #修改 maxInboundMessageSize: ${SW_DCS_MAX_INBOUND_MESSAGE_SIZE:4194304}
    maxInboundMessageSize: ${SW_DCS_MAX_INBOUND_MESSAGE_SIZE:52428800}
core:       
  default:        
    # 修改 maxMessageSize: ${SW_CORE_GRPC_MAX_MESSAGE_SIZE:0}    
    maxMessageSize: ${SW_CORE_GRPC_MAX_MESSAGE_SIZE:52428800}    
```
java demo
```java
package com.skywalking.skywalking.test.controller;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
@RestController
@Slf4j
@RequestMapping("log")
public class LogController {
    @GetMapping()
    public String log() {

        String filePath = "D:\\Works\\IdeaProjects\\skywalking-test\\doc\\package.txt";

        StringBuilder contentBuilder = new StringBuilder();

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String sCurrentLine;

            while ((sCurrentLine = br.readLine()) != null) {
                contentBuilder.append(sCurrentLine).append("\n");
            }

            log.info(contentBuilder.toString());

        } catch (IOException e) {
            log.error("IOException: %s%n", e);
        }
        log.info("simple log info");
        return "success";
    }

}

```
my txt file is 588kb. 

"simple log info" is shown , but txt info is missing in skywalking.
![image](https://github.com/user-attachments/assets/559718aa-716c-4061-a434-3fa299e4bb9c)
![image](https://github.com/user-attachments/assets/a1607b08-ef1a-4748-879c-1b8dad538454)

my question is how to config so that i can see **big log** in skywalking ui. 

thanks!
