### DISCUSSION TITLE
Trying to use fix to add license headers to the beginning of all source files.

### DISCUSSION THREAD

**Discussion by abrassel** [apache/skywalking#8081] [Q&A] [answered]
Hi!  As described in the title, I'm trying to use apache skywalker as an action to add my licensing header to files committed to main.  I have a .licenserc.yaml at the top level of my git directory, and I have the following in my workflows:

```

on:
  push:
    branches:
    - main
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add_header:
    name: Adds licenses to headers
    runs-on: ubuntu-latest
    steps:
    - name: Fix License Header
      uses: apache/skywalking-eyes@main
      with:
        mode: fix

    - name: Apply Changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: License Bot
        author_email: license_bot@github.com
        message: 'Automatic application of license header'
  ```
  
  However, when an action runs, I get the following:
  
  ```
   INFO Loading configuration from file: .licenserc.yaml 
INFO No config file is given, using the default config 
INFO Totally checked 0 files, valid: 0, invalid: 0, ignored: 0, fixed: 0 
```

It seems as though my source file could not be found?  Is it in the wrong directory?
