### DISCUSSION TITLE
How to  send zipkin V2 data to skywalking oap?

### DISCUSSION THREAD

**Discussion by JiZhihan** [apache/skywalking#8104] [Q&A]
Skywalking version: es7-8.7.0
I can now successfully report data to the zipkin server by coding.

The new requirement is that I want to report data in zipkin V2 format to skywalking's oap by coding.
Here is my oap profile.
`storage:
  selector: ${SW_STORAGE:zipkin-elasticsearch7}`

```
receiver_zipkin:
  selector: ${SW_RECEIVER_ZIPKIN:default}
  default:
    host: ${SW_RECEIVER_ZIPKIN_HOST:0.0.0.0}
    port: ${SW_RECEIVER_ZIPKIN_PORT:9411}
    contextPath: ${SW_RECEIVER_ZIPKIN_CONTEXT_PATH:/}
    jettyMinThreads: ${SW_RECEIVER_ZIPKIN_JETTY_MIN_THREADS:1}
    jettyMaxThreads: ${SW_RECEIVER_ZIPKIN_JETTY_MAX_THREADS:200}
    jettyIdleTimeOut: ${SW_RECEIVER_ZIPKIN_JETTY_IDLE_TIMEOUT:30000}
    jettyAcceptorPriorityDelta: ${SW_RECEIVER_ZIPKIN_JETTY_DELTA:0}
    jettyAcceptQueueSize: ${SW_RECEIVER_ZIPKIN_QUEUE_SIZE:0}
    instanceNameRule: ${SW_RECEIVER_ZIPKIN_INSTANCE_NAME_RULE:[spring.instance_id,node_id]}
```

The following core code of the client only modifies the Url as opposed to reporting data to the zipkin server
![image](https://user-images.githubusercontent.com/56993966/141066341-fd1cd8a4-3f60-436d-b317-d009e6a78484.png)

the response code 202 returned by the client request, but no data can be seen on the web ui
