### DISCUSSION TITLE
use "go install" meet error in "git action"

### DISCUSSION THREAD

**Discussion by iture123** [apache/skywalking#8338] [Q&A]
Run go install github.com/apache/skywalking-eyes/cmd/license-eye@latest
package github.com/apache/skywalking-eyes/cmd/license-eye@latest: cannot use path@version syntax in GOPATH mode
Error: Process completed with exit code 1.
![d126499172b5e2e53bd0f5c822c4b10](https://user-images.githubusercontent.com/12154864/147387270-065694a8-052b-4b82-b302-9ffd647030e6.png)

the git action workflow is 
**https://github.com/iture123/test-license/actions/runs/1621914114/workflow**

**Comment by kezhenxu94** [comment]
Can you try set the go version to 1.17 by adding a step like


```yaml
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
```
