### DISCUSSION TITLE
Need help on readLabledMetricValue - Unable to fetch the values

### DISCUSSION THREAD

**Discussion by tnayhsud** [apache/skywalking#8401] [Q&A]
Hello Folks, 

We are storing a metric in our system under "labeled" metric, which we are able to list using listMetricValues . But while trying to display it using  readLabledMetricValue, we are unable to fetch it . Here is the graphQL which is being used, still on verge of picking up the lang (please ignore any mistakes in the query)

Any help on this will be greatly appreciated, thanks in advance.

## PromFetcherRules

```
fetcherInterval: PT15S
fetcherTimeout: PT10S
metricsPath: /metrics
staticConfig:
  # targets will be labeled as "instance"
  targets:
    - url: http://192.168.49.2:9091
      sslCaFilePath:
  labels:
    service: cilium_metrics
expSuffix: tag({tags -> tags.service = 'cilium::' + tags.service}).instance(['service'], ['instance'])
metricPrefix: meter_hubble
metricsRules:
  - name: tcp_ipv4_flags
    exp: hubble_tcp_flags_total.sum(['service', 'instance']).rate('PT1M')
  - name: flows_processed_total
    exp: hubble_flows_processed_total.sum(['service', 'instance']).rate('PT1M')
  - name: top_drops_by_source
    exp: hubble_drop_total.tagEqual("reason", "Success").sum(['service', 'instance']).rate('PT1M')
  - name: top_drops_by_destination
    exp: hubble_drop_total.tagEqual("reason", "Success").sum(['service', 'instance']).rate('PT1M')
  - name: test_label
    exp: hubble_drop_total.tagEqual("reason", "Success").sum(['source','service', 'instance']).rate('PT1M')
```

## readLabeledMetricsValues GraphQL query

```
{
    "query": "query queryData($condition: MetricsCondition!, $labels: [String!]!, $duration: Duration!) {\n  \n  readLabeledMetricsValues: readLabeledMetricsValues(\n    condition: $condition, \n labels: $labels, \n    duration: $duration) {\n label \n    values {\n      values {value}\n    }\n }}",
    "variables": {
        "duration": {
            "start": "2022-01-11 0000",
            "end": "2022-01-11 0600",
            "step": "MINUTE"
        },
        "condition": {
            "name": "meter_hubble_test_label",
            "entity": {
                "scope": "ServiceInstance",
                "serviceName": "cilium::cilium_metrics",
                "serviceInstanceName": "http://192.168.49.2:9091",
                "normal": true
            }
        },
        "labels": [
            "source"
        ]
    }
}
```

## Read labeled metrics response
```
{"data":{"readLabeledMetricsValues":[{"label":"source","values":{"values":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}...]}}]}}
```

##  List metrics request GraphQL query
```
{
    "query": "query queryData($regex: String!) {\n  listMetrics: listMetrics(regex: $regex) {\n name \n type \n catalog}}",
    "variables": {
        "duration": {
            "start": "2022-01-11 0445",
            "end": "2022-01-11 0515",
            "step": "MINUTE"
        },
        "regex": "meter.*",
        "condition": {
            "name": "meter_hubble_test_label",
            "entity": {
                "scope": "ServiceInstance",
                "serviceName": "cilium::cilium_metrics",
                "serviceInstanceName": "http://192.168.49.2:9091",
                "normal": false
            }
        }
    }
}
```
## List metrics response

```
{
    "data": {
        "listMetrics": [
            ...
            {
                "name": "meter_hubble_test_label",
                "type": "LABELED_VALUE",
                "catalog": "SERVICE_INSTANCE"
            },
            ....
        ]
    }
}
```
