### DISCUSSION TITLE
We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue.

### DISCUSSION THREAD

**Discussion by yhlsunnny** [apache/skywalking#8856] [Q&A] [answered]
We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue.

**Comment by wu-sheng** [comment, marked as answer]
This usually means, your backend, OAP server or webapp, is not working well.

**Reply by yhlsunnny** [reply]
My backend started normally, but the UI call reported the above error

**Reply by wu-sheng** [reply]
I just could say what we know, nothing more.

**Reply by yhlsunnny** [reply]
The MAC system version is V9 0.0. After normal deployment, an error is reported. The UI part calls the back-end interface to report an error

**Reply by Superskyyy** [reply]
> My backend started normally, but the UI call reported the above error

Are you using the UIdocker image? Try add prefix http:// like this SW_OAP_ADDRESS=http://oap:12800 it's usually this problem. @yhlsunnny

**Reply by yhlsunnny** [reply]
No, it was installed on the MAC system

@Superskyyy

**Reply by Superskyyy** [reply]
> No, it was installed on the MAC system
> 
> @Superskyyy

It should work out of the box, there is something in your local env that we cannot know of. You have to try troubleshoot yourself. Other than that try use containers to run.

**Reply by yhlsunnny** [reply]
The problem has been solved because the corresponding driver cannot be found when connecting to MySQL.

**Reply by tanpenggood** [reply]
Hi bro, I also encountered the same problem, I am using skywalking 9.1.0
I didn't modify the relevant environment variables and configurations.

After running SkyWalking for three days, SkyWalking Web Page shows no data and browser remains in a white screen state. Response infos of the WebPage is 'We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue'. I ensure javascript of myweb view is enabled.

After `docker-compose restart` skywalking, normal access was restored.
Is it because skywalking-ui server crashed?

my docker-compose as follow:
```yaml
version: '3.3'
services:
  skywalking-oap-server:
    image: apache/skywalking-oap-server:9.1.0
    container_name: skywalking-oap-server
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: h2
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms1024m -Xmx1024m -Xmn512m'
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_OC_RULES: vm
      SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES: vm
    networks: 
      - sw
    volumes:
      - ./oap/conf/alarm-settings.yml:/skywalking/config/alarm-settings.yml

  skywalking-ui:
    image: apache/skywalking-ui:9.1.0
    container_name: skywalking-ui
    networks:
      - sw
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap-server:12800
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms256m -Xmx256m'

networks:
  sw:
```
