### DISCUSSION TITLE
"Unique index or primary key violation" in skywalking 9.0.0

### DISCUSSION THREAD

**Discussion by elepherai** [apache/skywalking#8886] [Q&A] [answered]
Hi, I got "Unique index or primary key violation" error when my container with java agent is up. 

![image](https://user-images.githubusercontent.com/43477405/163547951-7881fcea-583c-4991-8f52-9456d9ec0eba.png)

- skywalking-oap-server: 9.0.0
- skywalking-ui: 9.0.0
- skywalking-java-agent: 8.10.0-java8

**docker-compose.yml** 
```
skywalking-oap:
    container_name: skywalking-oap
    image: apache/skywalking-oap-server:9.0.0
    mem_limit: 1g
    ports:
      - "11800:11800"
      - "12800:12800"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Xmx1g -Xms1g
    healthcheck:
      test: /skywalking/bin/swctl
      interval: 60s
      timeout: 60s
      start_period: 60s
      retries: 3
 
skywalking-ui:
    container_name: skywalking-ui
    image: apache/skywalking-ui:9.0.0
    mem_limit: 1g
    ports:
      - "8086:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SW_OAP_ADDRESS=skywalking-oap:12800
    depends_on:
      skywalking-oap:
        condition: service_healthy
```

**Dockerfile**
```
FROM apache/skywalking-java-agent:8.10.0-java8
COPY ./target/app.jar /workspace/app.jar
WORKDIR /workspace

ENTRYPOINT [ \
    "java", \
    "-javaagent:/skywalking/agent/skywalking-agent.jar", \
    "-Dskywalking.agent.service_name=app", \
    "-Dskywalking.collector.backend_service=skywalking-oap:11800", \
    "-jar", \
    "app.jar", \
    "--spring.cloud.nacos.discovery.server-addr=nacos:8848", \
    "--spring.cloud.nacos.config.server-addr=nacos:8848" \
]
```

Thank you!
