### DISCUSSION TITLE
I can show metrics when entityType=serviceInstance, how to show metrics when entityType=service?

### DISCUSSION THREAD

**Discussion by xing393939** [apache/skywalking#8944] [Q&A]
I defined the Custom MAl and show metrics in Rocketbot UI, and it works.
My MAL script is:
```
expSuffix: instance(['service'], ['instance'])
metricPrefix: sw_golang
metricsRules:
  - name: num_goroutine
    exp: num_goroutine
```
My UI settings is:
![image](https://user-images.githubusercontent.com/2681291/165048611-5e782c42-a49a-47f9-839b-8580487ce9f3.png)

In this case, I can only see metrics when I select the service and the instance. I want to see metrics of the service with all instances. I change the UI settings and set entityType=service, but it shows nothing, what can I do?
