### DISCUSSION TITLE
In skywalking, the service name of infrastructure monitoring is empty

### DISCUSSION THREAD

**Discussion by hongdor** [apache/skywalking#8963] [Q&A] [answered]
I got a data of linux server. and I could see the chart of data.
but the service name of server was empty as you see in the below image.
I want to know how to get service name or set service name.

![image](https://user-images.githubusercontent.com/67362953/165482184-f91c031e-b61a-44a9-8ac3-785908104263.png)

[opentelemetry collector config]
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'vm-monitoring' # make sure to use this in the vm.yaml to filter only VM metrics
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:9100' ]

processors:
  batch:

exporters:
  opencensus:
    endpoint: "localhost:11800" # The OAP Server address
    tls:
      insecure: true
  # Exports data to the console  
  logging:
    logLevel: error

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [opencensus,logging]

```

**Comment by wu-sheng** [comment, marked as answer]
Try showcase, I think there is some change from our showcase version to yours.

**Comment by wankai123** [comment]
We have not verified the compatibility of the latest OTEL version yet, you can try 0.29.0 and our showcase is useing it.

**Comment by hongdor** [comment]
After I add node_identifier_host_name, I can obtain service name
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'vm-monitoring' # make sure to use this in the vm.yaml to filter only VM metrics
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:9100' ]
              ##########################################################
              labels:
                node_identifier_host_name: 'localhost'
              ##########################################################

processors:
  batch:

exporters:
  opencensus:
    endpoint: "localhost:11800" # The OAP Server address
    tls:
      insecure: true
  # Exports data to the console  
  logging:
    logLevel: error

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [opencensus,logging]
```
