### DISCUSSION TITLE
Skywalking benchmark on Finance Core System

### DISCUSSION THREAD

**Discussion by lewiselau** [apache/skywalking#9002] [Show and tell]
Hi Community, 

We have a performance Test on Skywalking, on base of Finance Core system. 
### **The platform architecture:** 
 - Application: Finance core system, Kubernetes based, 10 key spring boot microservices, 40 pods with Load balancing. 
 - Skywalking Backend: OAP v9.1.0-SNAPSHOT-85CE164(20220217220813), K8S based, 2 nodes x 8Ghz/8gbRAM each one, elastic search storage (3 - 6 nodes)  (After 100CCU, OAP was upgraded to OAP 9.1.0 - 20220508)
 - Skywalking Javaagent plugins: Javaagent V8.10, Default plugins + Mybatis plugin + Threadpool plugin + url ignore plugin + Trace Maven dependency to generate TraceID into Logback.  (After 100CCU, Javaagent was upgraded to  V8.11 - 20220508)
 - Skywalking Vue agent: "skywalking-client-js":"^0.8.0"  
 - Test cases: 5 CCU, 10 CCU, 20 CCU, 40 CCU, 50CCU, 100CCU (CCU - Concurrent User, but here it is Rest API call with Jmeter, without Think Time)

### **Phased Summary:**

- Storage will already be the key bottleneck and optimization point. For cost-efficiency, we are willing to extend the ES flush interval for better performance; Seems 60 seconds works well instead 10s default. 
- There are multi OAP thread pools, we are attempting to scale out some threads, but thread are not the bottleneck as the storage iops. 
- Some maximum content length need to optimization tuning, which leading part of the data dropped. 
- Storage consuming: 1GB per CCU / HOUR, include 80% Logging (2 days retention), 8% Tracing (2 days retention), 12% Metrics (10 days retention)

### **Some open questions:**
1. We utilized Skywalking self observibility to trace the OAP side performance, however we can only find one OAP instance 'localhost:1234' in the scenario of multi OAP pods, even though we practiced static hostname or pod discovered with K8S, in regarding to the setup manual: https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-telemetry/. 
 <20220509> This one was resolved. Per review from professional community, the key points are:
        - It is opencensus on oap end, so it is opencensus exporter in opentelemetry collector configmap, to reference https://github.com/apache/skywalking-showcase/blob/main/deploy/platform/kubernetes/feature-so11y/open-telemetry.yaml#L51
        - Disable SW_PROMETHEUS_FETCHER, which is only for static way 
        - Keep oap container name and service name same as the ones defined in  scrape_configs job of opentelemetry, e.g oap as container name and oap-server as service name.
  Please refer to my practice in Appendix part. 

2. No data on Virtual database UI within our environments (Ali K8S PaaS, Ali MySQL PaaS), however on other scenario it works well. No idea so far.  
   <20220512> This one was resolved. Root cause is, Skywalking enhance was impacted by the enhance from another APM Tracer - Aliyun ARMS, which led to below enhance failure: 
   - Enhance class io.grpc.netty.NettyClientStream error
   - Enhance class com.alibaba.druid.pool.DruidDataSource error.
   - Enhance class com.mysql.cj.jdbc.ConnectionImpl error.   (This one is related to Virtual database)
 Disable ARMS, then Virtual database UI works well. 

3. We hope to archive some key metrics for long-term analysis, e.g. apdex and p9x response time data. However, there are no default solution. We are trying to validate on 3 options: a) GraphQL with script; b) Coding a GRPC Server to activate Skywalking Exporter feature; c) From storage level, ETL to another storage. We are still on the way.   
   <20220512> On the way to GRPC Server Option, and will update later on.

4. After Small version upgrade within oap 9.0 (From v9.1.0-SNAPSHOT-85CE164(20220217220813) to 9.1.0 - 20220508)), no new collected data can be not presented on UI with below notification on UI:
    Exception while fetching data (/data) : null
    The data can be presented after Storage refresh, e.g. ES. 
      <20220522> Per test, new data include metrics/trace/log is able to write onto Elastic Search, and also the input data within one week is able to be qeury from UI normally. But in case query the data in past one month where the data over 1 week is already remove by housekeeping job, there will be Exception warning from UI, "Exception while fetching data (/data) : null"  as below: 
And also, some warinig log generated as below: 
```
2022-05-22 13:10:57,480 org.apache.skywalking.library.elasticsearch.client.SearchClient 63 [armeria-eventloop-epoll-5-1] ERROR [] - [9.1.0-SNAPSHOT-1285f5b] Failed to search, request org.apache.skywalking.library.elasticsearch.requests.search.Search@404c6719, params null, index [sky-walking_segment-20220422, sky-walking_segment-20220423, sky-walking_segment-20220424, sky-walking_segment-20220425, sky-walking_segment-20220426, sky-walking_segment-20220427, sky-walking_segment-20220428, sky-walking_segment-20220429, sky-walking_segment-20220430, sky-walking_segment-20220501, sky-walking_segment-20220502, sky-walking_segment-20220503, sky-walking_segment-20220504, sky-walking_segment-20220505, sky-walking_segment-20220506, sky-walking_segment-20220507, sky-walking_segment-20220508, sky-walking_segment-20220509, sky-walking_segment-20220510, sky-walking_segment-20220511, sky-walking_segment-20220512, sky-walking_segment-20220513, sky-walking_segment-20220514, sky-walking_segment-20220515, sky-walking_segment-20220516, sky-walking_segment-20220517, sky-walking_segment-20220518, sky-walking_segment-20220519, sky-walking_segment-20220520, sky-walking_segment-20220521, sky-walking_segment-20220522]
java.util.concurrent.CompletionException: java.lang.RuntimeException: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [sky-walking_segment-20220422]","resource.type":"index_or_alias","resource.id":"sky-walking_segment-20220422","index_uuid":"_na_","index":"sky-walking_segment-20220422"}],"type":"index_not_found_exception","reason":"no such index [sky-walking_segment-20220422]","resource.type":"index_or_alias","resource.id":"sky-walking_segment-20220422","index_uuid":"_na_","index":"sky-walking_segment-20220422"},"status":404}
```

### **Detail performance test data** 
as below, and we will continue to update later on.

https://gist.github.com/lewiselau/9aa8bec87e3af682d7229660f965fbab
Update: 20220508 00
Direct image here - seems gist not visible to sometime
![image](https://user-images.githubusercontent.com/77489349/167266473-9aa827d4-dc96-4550-9c09-c17e67d36f03.png)
![image](https://user-images.githubusercontent.com/77489349/167278087-ccd5e01b-64b4-420b-a44c-2db94a77590a.png)

### **Appendix:**
**1. Self obsevibility setting on Discovery K8S manner**
Per review and guidance from Community professor, the k8s-discovery option of self-observibility feature is activated. And here attach the configuration file as successful practice. 
Environment parameter and Ports on OAP deployment
ports: 
```
  - containerPort: 1234
    name: prometheus-port
```
env:
```
  - name: SW_TELEMETRY
    value: prometheus
  - name: SW_TELEMETRY_PROMETHEUS_PORT
    value: '1234'
  - name: SW_OTEL_RECEIVER
    value: default
  - name: SW_OTEL_RECEIVER_ENABLED_OC_RULES
    value: oap
  #- name: SW_PROMETHEUS_FETCHER
    #value: default
```

Configmap/deployment on opentelemetry collector
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf-so11y
  labels:
    app: opentelemetry-so11y
data:
  otel-collector-config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'skywalking-so11y'
              metrics_path: '/metrics'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: oap;prometheus-port
                - source_labels: []
                  target_label: service
                  replacement: oap-server
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: host_name
                  regex: (.+)
                  replacement: $$1
    exporters:
      opencensus:
        endpoint: "sw-service.apm.svc:11800"
        tls:
          insecure: true
      # logging:
      #   logLevel: debug
    service:
      pipelines:
        metrics:
          receivers: [ prometheus ]
          exporters: [ opencensus ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-deployment-so11y
  labels:
    app: otel-so11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-so11y
  template:
    metadata:
      labels:
        app: otel-so11y
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: otel-sa-so11y
      containers:
        - name: otel
          image: otel/opentelemetry-collector:0.50.0
          command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          volumeMounts:
            - name: otel-collector-config-vol-so11y
              mountPath: /conf
      volumes:
        - name: otel-collector-config-vol-so11y
          configMap:
            name: otel-collector-conf-so11y
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
```
Permission setting since K8S API Server will be accessed for pod metadata information.
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-sa-so11y
  namespace: apm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-role-so11y
  #namespace: apm
rules:
  - apiGroups: [""]
    resources:
      - pods # @feature: so11y; OpenTelemetry needs to read OAP Pods information to get OAP details
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-role-binding-so11y
  namespace: apm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-role-so11y
subjects:
  - kind: ServiceAccount
    name: otel-sa-so11y
    namespace: apm
```

**2. The UI snapshot**
So far we achieved self-observibility on both statis and K8S-Discovery way.
![image](https://user-images.githubusercontent.com/77489349/167370267-944e5c7d-3ae7-4641-b7a7-9b9f2380bd10.png)

**Comment by Superskyyy** [comment]
Thanks for the sharing! Looks like the tables are messed up because GitHub trying to limit the width. Let's find out a better way to show the work..

**Comment by kezhenxu94** [comment]
> Some open questions:
> 
> 1. We utilized Skywalking self observibility to trace the OAP side performance, however we can only find one OAP instance 'localhost:1234' in the scenario of multi OAP pods, even though we practiced static hostname or pod discovered with K8S, in regarding to the setup manual: https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-telemetry/.

https://skywalking.apache.org/docs/main/latest/en/setup/backend/backend-telemetry/#service-discovery-on-kubernetes service discover on Kubernetes should work as I use this to set up self observability multiple times and all the OAP instances are correctly shown as their Pod IPs, can you share more details how you set it up and how the result looks like?


> 3. We hope to archive some key metrics for long-term analysis, e.g. apdex and p9x response time data. However, there are no default solution. We are trying to validate on 3 options: a) GraphQL with script; b) Coding a GRPC Server to activate Skywalking Exporter feature; c) From storage level, ETL to another storage. We are still on the way.

I personally think using SkyWalking gRPC exporter is a quick and practical way to save those key metrics for longer term

**Reply by lewiselau** [reply]
Thanks for your kind comments.
About self observibility, please refer to my updates about the  setting and final UI. And any feedback is welcome. 
About the Skywalking GRPC Exporter, we are trying to code the GRPC Server end for Skywalking consuming, and finally the communication direction will be, Skywalking push metrics data to our customized GRPC Server.

**Reply by kezhenxu94** [reply]
Hi @lewiselau here are my observations:

- you don't need to set `SW_PROMETHEUS_FETCHER` in Kubernetes service discovery, setting `SW_PROMETHEUS_FETCHER` will bring `localhost:1234` always.
- I saw your OAP service name is `sw-service` according to:

  ```yaml
    exporters:
      otlp:
        endpoint: "sw-service.apm.svc:11800"
  ```

  did you make sure that the pod container name `oap` is correct here? Because it looks you are not using any of our installation methods (Helm Chart or Operator)
  ```yaml
    - source_labels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name]
      action: keep
      regex: oap;prometheus-port # <----- here
  ```

**Reply by lewiselau** [reply]
As We removed the parameter SW_PROMETHEUS_FETCHER, there will be nothing on self observibility service / instance, with below sammple yaml of OAP deployment and  Service.
We found there are error warning from Opentelemetry pod as below. Seems some version incompatible between client and Server end. 
(Per our understanding, prometheus is not necessary, so no prometheus on this scenario.)

```
2022-05-08T16:45:53.835Z        error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.   {"kind": "exporter", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.metrics.v1.MetricsService/Export", "dropped_items": 88}
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap-deployment
  namespace: apm
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: skywalking-oap
  template:
    metadata:
      labels:
        tier: skywalking-oap
    spec:
      containers:
      - name: oap
        #image: apache/skywalking-oap-server:8.9.1
        image: lewise/oap:9.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 11800
            name: grpc
          - containerPort: 12800
            name: rest
          - containerPort: 1234
            name: prometheus-port
        env: 
          - name: SW_TELEMETRY
            value: prometheus
          - name: SW_TELEMETRY_PROMETHEUS_PORT
            value: '1234'
          - name: SW_OTEL_RECEIVER
            value: default
          - name: SW_OTEL_RECEIVER_ENABLED_OC_RULES
            value: oap

apiVersion: v1
kind: Service
metadata:
  name: sw-service
  namespace: apm
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 11800 
    targetPort: 11800
    nodePort: 30118
  - name: rest
    port: 12800 
    targetPort: 12800
    nodePort: 30128
  - name: prometheus-port
    port: 1234
    targetPort: 1234
    nodePort: 31234
  selector:
    tier: skywalking-oap
```
