### DISCUSSION TITLE
version 9.0.0 , Grpc server thread pool is full, rejecting the task

### DISCUSSION THREAD

**Discussion by yujj1993** [apache/skywalking#9022] [Q&A] [answered]
I run version 9.0.0 oap-server in kubernetes1.13,  resources is  8C CPU, 8G RAM, 2 replices.But oap-server will report an error after running for a period of time.I have modified the application.yml as follows:
```
core:
  default:
    gRPCThreadPoolQueueSize: ${SW_RECEIVER_GRPC_POOL_QUEUE_SIZE:20000}
    gRPCThreadPoolSize: ${SW_RECEIVER_GRPC_THREAD_POOL_SIZE:32}
```
But there is no improvement.

Errors are reported as the picture：
![微信图片_20220510112419](https://user-images.githubusercontent.com/46517992/167536525-c5c0e255-8281-4328-aed4-443dee03f4da.png)
