### DISCUSSION TITLE
Why did the event not trigger an alarm?

### DISCUSSION THREAD

**Discussion by saber-wang** [apache/skywalking#9327] [Q&A]
rules:
```
    rules:
      started_event_rule:
        metrics-name: Started
        threshold: 1
        op: ">="
        period: 10
        count: 1
        message: Started
      killing_event_rule:
        metrics-name: Killing
        threshold: 1
        op: ">="
        period: 5
        count: 1
        message: killing
```

events:
![image](https://user-images.githubusercontent.com/45062099/177993286-e8454264-9741-42ea-b509-6173af1e07b1.png)
