### DISCUSSION TITLE
skywalking trace data is not appeared in service mesh

### DISCUSSION THREAD

**Discussion by stevenlii** [apache/skywalking#9334] [Q&A] [answered]
**Describe the question:**

I'm trying to use skywalking to check service mesh(istio 1.14.1) tracing, and I checked https://github.com/istio/istio/pull/32588  and https://github.com/apache/skywalking/issues/7241 , now get no trace data on service mesh 
![image](https://user-images.githubusercontent.com/8954758/178489357-887bc37e-a61b-420b-ac9c-6e4a70448533.png)

**Steps to reproduce**
skywalking  installed below: 
```
helm install skywalking skywalking/skywalking -n skywalking \
  --set oap.image.tag=9.1.0 \
  --set oap.storageType=elasticsearch \
  --set ui.image.tag=9.1.0 \
  --set elasticsearch.imageTag=7.5.1 \
  --set oap.replicas=1 \
  --set oap.env.SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS=mx-mesh \
  --set oap.env.SW_ENVOY_METRIC_ALS_TCP_ANALYSIS=mx-mesh \
  --set values.telemetry.v2.enabled=true
  --set oap.envoy.als.enabled=true
```

istioctl 1.14.1 installed like this: 
```
istioctl manifest install -y \
  --set profile=demo \
  --set meshConfig.defaultConfig.envoyMetricsService.address=skywalking-oap.istio-system.svc.cluster.local:11800 \
  --set 'meshConfig.defaultConfig.proxyStatsMatcher.inclusionRegexps[0]=.*' \
  --set meshConfig.enableEnvoyAccessLogService=true \
  --set meshConfig.defaultConfig.envoyAccessLogService.address=skywalking-oap.istio-system.svc.cluster.local:11800
```
configured meshConfig below: 
```
meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      envoyAccessLogService:
        address: skywalking-oap.istio-system.svc.cluster.local:11800
      envoyMetricsService:
        address: skywalking-oap.istio-system.svc.cluster.local:11800
      proxyMetadata: {}
      proxyStatsMatcher:
        inclusionRegexps:
        - .*
    enableEnvoyAccessLogService: true
    enablePrometheusMerge: true
    extensionProviders:
    - name: skywalking
      skywalking:
        port: 11800
        service: skywalking-oap.istio-system.svc.cluster.local
  profile: demo
  tag: 1.14.1

```
add Telemetry
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: test
spec:
  tracing:
  - customTags:
      my_new_foo_tag:
        literal:
          value: foo
    providers:
    - name: skywalking
    randomSamplingPercentage: 100
```
set start_child_span in EnvoyFilter like below:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: istio-system
  name: route
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: REPLACE
        value:
          name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            start_child_span: true

```

And I propagate sw8 like this( using grpc, so get trace in metadata):

```
 void genTrace(Metadata headers) {
        Metadata request = TRACING_KEY.get(Context.current());
         if (request.get(Metadata.Key.of("sw8", Metadata.ASCII_STRING_MARSHALLER)) == null) {
			//manual generate trace id as https://gitcode.net/apache/skywalking/-/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v3.md
		}
```
However I could not get trace data. Did I miss something or  something wrong? 
Any suggestion are welcomed.
