### DISCUSSION TITLE
The result of MAL sum aggregation operation is not as expected

### DISCUSSION THREAD

**Discussion by lidingming2005** [apache/skywalking#9348] [Q&A] [answered]
Hi,

I want to aggregate some prometheus metrics from a k8s service, and I define otel colletor like this:
```
global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'myjob'
    metrics_path: '/metrics'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name]
        action: keep
        regex: target;target-port  
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: host_name
        regex: (.+)
        replacement: $$1 
```

And My MAL Script is:
```
expSuffix: service(['service'])
metricPrefix: my
metricsRules:
  - name: meter_test
    exp: server_request_count.sum(['service'])
```

The sample family is like 'server_request_count{service="my_service", status=<status>, host_name=<pod_name>}', and I expect to get the summation of server_request_count by all status and all host_name. But the result is the average of them, which confused me.

For example, I have 2 pods, the sample family like this:
server_request_count{service="my_service", status="200", host_name="pod1"} a1
server_request_count{service="my_service", status="404", host_name="pod1"} a2
server_request_count{service="my_service", status="200", host_name="pod2"} b1
server_request_count{service="my_service", status="404", host_name="pod2"} b2
The result of my_meter_test which my expected is (a1+a2+b1+b2), but actually I get (a1+a2+b1+b2)/2

Is my understanding of MAL's aggregation operation wrong? Or what should I do to make the result as my excepted?

Thank you very much!
