### DISCUSSION TITLE
Questions about alert notifications

### DISCUSSION THREAD

**Discussion by jia2332** [apache/skywalking#9685] [Q&A]
I see that the document says support service event notification
```
Metrics name. This is also the metrics name in the OAL script. Only long, double, int types are supported. See the [list of all potential metrics name](https://skywalking.apache.org/docs/main/v9.2.0/en/setup/backend/backend-alarm/#list-of-all-potential-metrics-name). Events can also be configured as the source of Alarm. Please refer to [the event doc](https://skywalking.apache.org/docs/main/v9.2.0/en/concepts-and-designs/event) for more details.
```
But it seems that the notification was not successful.

Here is my configuration
service_resp_time_rule is successful. 
But service_start_up_rule failed
```
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    threshold: 10000
    op: ">"
    period: 10
    count: 3
    silence-period: 10
    tags:
      level: WARNING
    message: "  service_resp_time：{name}"

  service_start_up_rule:
    metrics-name: Start
    threshold: 1
    op: ">="
    period: 10
    count: 1
    silence-period: 10
    tags:
      level: WARNING
    message: "service_start_up：{name}"
wechatHooks:
  textTemplate: |-
    {
      "msgtype": "text",
      "text": {
        "content": "Apache SkyWalking Alarm: \n %s."
      }
    }
  webhooks:
    - https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=****************
```
