### DISCUSSION TITLE
Alarm rule Exclusion name (include-names-regex)did not take effect

### DISCUSSION THREAD

**Discussion by lklkxcxc** [apache/skywalking#9766] [Q&A] [answered]
alarm rule config:
```
rules:
  # Rule unique name, must be ended with `_rule`.
  service_resp_time_rule:
    metrics-name: service_resp_time
    include-names-regex: prod*   #  Only include service name begin prod*
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
```
Only include service name begin prod*，but the service whose name is prod-123-xxx is not matched
