### DISCUSSION TITLE
skywalking oap server docker image problem

### DISCUSSION THREAD

**Discussion by hieu276** [apache/skywalking#9774] [Q&A]
OAP image: apache/skywalking-oap-server:9.2.0
UI image: apache/skywalking-ui:9.2.0
I tried running skywalking on docker by using skywalking images version 9 and faced problem when loading ui (in following image) . I have the same problem when running skywalking distribution in ubuntu 22.04.  If i run oap-server in my local host, it work perfectly with ui container. 

This is my docker-compose.yml

```yaml
version: '3'
services:
  oap:
    image: apache/skywalking-oap-server:9.2.0
    container_name: oap
    restart: always
    ports:
      - 11800:11800 
      - 12800:12800 
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - TZ=Asia/Ho_Chi_Minh
  skywaling-ui:
    image: apache/skywalking-ui:9.2.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 8009:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
```

My problem:
![image](https://user-images.githubusercontent.com/48582387/195271683-65536b35-6c19-4965-b7e3-8b1e539f289b.png)
