### DISCUSSION TITLE
I did not find meter in the oal file_ status_ Code parameter

### DISCUSSION THREAD

**Discussion by FangPengbo** [apache/skywalking#9861] [Q&A] [answered]
In [Default alarm rules,](https://skywalking.apache.org/docs/main/v9.0.0/en/setup/backend/backend-alarm/#default-alarm-rules) I see the following configuration
```
  meter_service_status_code_rule:
    metrics-name: meter_status_code
    exclude-labels:
      - "200"
    op: ">"
    threshold: 10
    period: 10
    count: 3
    silence-period: 5
    message: The request number of entity {name} non-200 status is more than expected.
    only-as-condition: false
```
But I didn't find meter in the oal file_ status_ The code parameter,
And I don't understand the parameter "exclude labels". Where does the labels come from?
Among them, op: ">", but the result is that the number of requests with entity {name} status other than 200 exceeds the expectation.
It should be op: "!=".

Can someone help me? 🙏
