### ISSUE TITLE
[Feature] [Infra-e2e] Support debugging on an existing kubernetes cluster and single-step debugging 

### ISSUE THREAD

**Issue by dashanji** [apache/skywalking#10228]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. When using the current infra-e2e for kubernetes test locally, we find the kind cluster is repeatedly created and deleted, which will waste of time, so we can add some fields to set up the kubeconfig of an existing kubernetes cluster(kind).
2. As mentioned before, if we can debug on an existing cluster, to not affect the original cluster resources, we need to add a built-in command to collect the previous kubernetes reousces created in the previous steps and delete them.
3. To make debugging more convenient, we need to add a built-in command to support single-step debugging, which can wait for a signal from an external process, and when the signal comes, continue to the next step.

### Use case

1. Add a filed like `kubeconfig`.
```yaml
setup:
  kubeconfig: ../config
  steps:
     ...
```
2. Add a built-in command like `e2e-delete-previous-kubernetes-resources`.
```yaml
setup:
  steps:
     - name: xxx
        command: kubectl create xxx
     - name: xxx
        command: kubectl apply xxx
     - name: e2e-delete-previous-kubernetes-resources
```

3. Add a built-in command like `single-debugging`.
```yaml
setup:
  steps:
     - name: xxx
        command: kubectl create xxx
     - name: single-debugging
     - name: xxx
        command: kubectl apply xxx
     - name: single-debugging
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
@kezhenxu94 @fgksgf Could you provide some suggestions here?

**Comment by fgksgf** [comment]
1. This makes sense to me
2. I think the implementation would be complicated and hard to be general, maybe let users to control it would be more suitable, for example make `cleanup` support execute commands:
```yaml
cleanup:
  steps:
     - name: xxx
        command: kubectl delete -f xxx
```
3. Good point, but we need a more detailed design
