### ISSUE TITLE
[Bug] docker Build 9.3.0 Error Report Insufficient Memory

### ISSUE THREAD

**Issue by JavaLionLi** [apache/skywalking#10251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

![image](https://user-images.githubusercontent.com/31852897/211252100-8f731666-4d78-4823-824f-90d560eff62d.png)

Docker Orchestration skywalking 9.3.0 Startup Error Insufficient Memory (8.9.1 Run No Exception)

There is insufficient memory for the Java Runtime Environment to continue.

Actual memory remaining
![image](https://user-images.githubusercontent.com/31852897/211252533-0f07b78f-381b-41d5-8a70-19cc4d5b99be.png)

Docker version information
![image](https://user-images.githubusercontent.com/31852897/211252208-4db3f1b9-131d-4abc-b7b7-948cc568b607.png)

### What you expected to happen

Run successfully

### How to reproduce

docker orchestration configuration

```
version: '3'

services:
  sky-oap:
    image: apache/skywalking-oap-server:9.3.0
    container_name: sky-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      SW_CORE_RECORD_DATA_TTL: 7
      SW_CORE_METRICS_DATA_TTL: 7
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 127.0.0.1:9200
      TZ: Asia/Shanghai
    network_mode: "host"

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
