### ISSUE TITLE
[Feature] Try to pull a docker image when the local image does not exist

### ISSUE THREAD

**Issue by ethan256** [apache/skywalking#10397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In the e2e test, can the e2e tool try to get the image when the docker image does not exist locally?

### Use case

```yaml
setup:
  env: kind
  file: kind.yaml
  kind:
    pull-images: 
      - private-docker-images
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
