### ISSUE TITLE
[INFRA] verify support float compare

### ISSUE THREAD

**Issue by ethan256** [apache/skywalking#10402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When a float type is present in the verifier module, an error will be reported.

### Use case

actual.yaml
```yaml
code: 200
message: success
data:
  - instanceName: provider1
    status: 2
    rate: 1.0
```

expected.yaml
```yaml
code: 200
message: success
data:
{{- contains .data }}
  - instanceName: provider1
    status: 2
    rate: 1.0
{{- end }}
```

result:

```shell
ERROR failed to verify the output: /Users/ethan/github.com/skywalking/skywalking-infra-e2e/test/verify/0.actual.yaml, error:
mismatch (-want +got):
  map[interface{}]interface{}{
  	string("code"): int(200),
  	string("data"): []interface{}{
  		map[interface{}]interface{}{
  			string("instanceName"): string("provider1"),
- 			string("rate"):         int(1),
+ 			string("rate"):         float64(1),
  			string("status"):       int(2),
  		},
  	},
  	string("message"): string("success"),
  } 
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
