### ISSUE TITLE
[INFRA] Cannot resolve protobuf-java's license

### ISSUE THREAD

**Issue by AlbumenJ** [apache/skywalking#10488]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

Bumps protobuf-java.version from 3.19.6 to 3.22.0.
Updates protobuf-java from 3.19.6 to 3.22.0

https://github.com/apache/dubbo/pull/11737

```
License: Unknown Dependency: com.google.protobuf:protobuf-java
License: Unknown Dependency: com.google.protobuf:protobuf-java-util 
```

### What you expected to happen

Work success

### How to reproduce

https://github.com/apache/dubbo/pull/11737

Bumps protobuf-java.version from 3.19.6 to 3.22.0.
Updates protobuf-java from 3.19.6 to 3.22.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Are you using latest? We have a recent fix for this dependencies resolutions. 
For old eyes versions, it requires local build first.

**Comment by AlbumenJ** [comment]
```yaml
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check License
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: "Compile Dubbo (Linux)"
        run: |
          ./mvnw --batch-mode --no-snapshot-updates -e --no-transfer-progress --fail-fast -T 2C clean install -DskipTests=true -DskipIntegrationTests=true -Dcheckstyle.skip=true -Dcheckstyle_unix.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .licenserc.yaml
          mode: check
```

Should I change to `apache/skywalking-eyes/dependency@latest`?
