### ISSUE TITLE
[Bug] [INFRA/EYE] Failing to configure paths and paths-ignore when providing multiple licenses

### ISSUE THREAD

**Issue by arturo-seijas** [apache/skywalking#10748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

Hi!

I've provided the following configuration expecting two different header patterns to be recognized to the provided set of files (note that both configurations work separately):
```
header:
  - license:
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        Licensed under the Apache2.0. See LICENSE file in charm source for details.
      paths:
        - 'lib/**'
      comment: on-failure
  - license:
      spdx-id: Apache-2.0
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        See LICENSE file for licensing details.
      paths:
        - '**'
      paths-ignore:
        - 'lib/**'
      comment: on-failure
```
When executing, all files are analysed by each entry.

### What you expected to happen

I expected the first license to be applied only to `lib/**` and the second one for the rest of the files

### How to reproduce

* Create a new repository with the following files
1. `.licenserc.yaml`
```
header:
  - license:
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      Licensed under the Apache2.0. See LICENSE file in charm source for details.
    paths:
      - 'lib/**'
    comment: on-failure
  - license:
    spdx-id: Apache-2.0
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    paths:
      - '**'
    paths-ignore:
      - 'lib/**'
    comment: on-failure
```

2. Add a `sample.sh` file with the following content
```
# Copyright 2023 Company Ltd.
# See LICENSE file for licensing details.
```
Add a `lib/samplelib.sh` file with the following content
```
# Copyright 2023 Company Ltd.
# Licensed under the Apache2.0. See LICENSE file in charm source for details.
```

Run `license-eye -c .licenserc.yaml header check`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Hi @arturo-seijas , sorry to tell it turns out to be the yaml config is still wrong in terms of indentations, the culprit is that our doc gives the wrong one and I fix it in https://github.com/apache/skywalking-eyes/pull/161 , please try this one:


```yaml
header:
  - license:
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        Licensed under the Apache2.0. See LICENSE file in charm source for details.
    paths:
      - 'lib/**'
    comment: on-failure
  - license:
      spdx-id: Apache-2.0
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        See LICENSE file for licensing details.
    paths:
      - '**'
    paths-ignore:
      - 'lib/**'
    comment: on-failure
```

Note that the `paths`/`paths-ignore`/`comment` are in the same level of `license`
