### ISSUE TITLE
[Bug] [INFRA/EYE] Failing to validate custom content when providing multiple licenses

### ISSUE THREAD

**Issue by arturo-seijas** [apache/skywalking#10746]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

Hi!

I've provided the following configuration expecting two different header patterns to be recognized, given that I have two different header contents in my source files (note that both configurations work separately):

```
header:
  - license:
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      Licensed under the Apache2.0. See LICENSE file in charm source for details.
    paths:
      - 'lib/**'
    comment: on-failure
  - license:
    spdx-id: Apache-2.0
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    paths:
      - '**'
    paths-ignore:
      - 'lib/**'
    comment: on-failure
```

The resulting scan is ignoring the specified `content`. the tools is also throwing a warning `failed to find a license template for spdx id , open header-templates/.txt: file does not exist`.

### What you expected to happen

The tool should have compared the headers against the `content`, analogous to what happens when a single `license` item is set.

### How to reproduce

* Create a new repository with the following files
1. `.licenserc.yaml`
```
header:
  - license:
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      Licensed under the Apache2.0. See LICENSE file in charm source for details.
    paths:
      - 'lib/**'
    comment: on-failure
  - license:
    spdx-id: Apache-2.0
    copyright-owner: Company Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    paths:
      - '**'
    paths-ignore:
      - 'lib/**'
    comment: on-failure
```

2. Add a `sample.sh` file with the following content
```
# Copyright 2023 Company Ltd.
# See LICENSE file for licensing details.
```

3. Add a `lib/samplelib.sh`file with the following content
```
# Copyright 2023 Company Ltd.
# Licensed under the Apache2.0. See LICENSE file in charm source for details.
```

* Run the GitHub action with the following configuration
```
- name: Check license headers
        uses: apache/skywalking-eyes/header@main
        with:
          config: .licenserc.yaml       
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Please provide a suitable title according.

**Comment by arturo-seijas** [comment]
> Please provide a suitable title according.

Sorry. Fixed

**Comment by kezhenxu94** [comment]
Hi, @arturo-seijas , this turns out to be typos in the doc, please see https://github.com/apache/skywalking-eyes/pull/159

**Comment by arturo-seijas** [comment]
HI again!
I've been testing this and, although I'm not getting the warning anymore, The `paths` and paths-ignore` sections are being ignored:
```
header:
  - license:
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        Licensed under the Apache2.0. See LICENSE file in charm source for details.
      paths:
        - 'lib/**'
      comment: on-failure
  - license:
      spdx-id: Apache-2.0
      copyright-owner: Company Ltd.
      content: |
        Copyright [year] [owner]
        See LICENSE file for licensing details.
      paths:
        - '**'
      paths-ignore:
        - 'lib/**'
      comment: on-failure

```
