### ISSUE TITLE
[Bug] Missing SPDX text licenses

### ISSUE THREAD

**Issue by heliocastro** [apache/skywalking#10764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking-Eyes Component

License Eye (apache/skywalking-eyes)

### What happened

Only a few selected text licenses are provided under assets/headers-templates

This causes the following issue:

```bash
WARNING failed to find a license template for spdx id EPL-2.0, open header-templates/EPL-2.0.txt: file does not exist 
```

### What you expected to happen

As EPL-2.0 ( and others ) are qualified SPDX ID licenses, is expected that would be found

### How to reproduce

Execute a check with this config:

```yaml
header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: SW360 Frontend Authors
    copyright-year: '2023'
    software-name: sw360-frontend
```

### Anything else

An alternative solution would be the possibility to provide the License file in commandline or download in real time from SPDX.org 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
