### ISSUE TITLE
skywalking-satellite docker run in arm64

### ISSUE THREAD

**Issue by guangdashao** [apache/skywalking#11138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Satellite (apache/skywalking-satellite)

### What happened

satellite image run in linux arm64 , container error and restart

```
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
```

### What you expected to happen

satellite linux/arm64 image run success in  linux/arm64 machine

### How to reproduce

- docker-compose.yaml

```yaml
version: '3.9'
x-deploy-common:
  &deploy-common
  restart: unless-stopped      
  network_mode: "host"
  init: true
services:
  skywalking-satelite:
    <<: *deploy-common
    image: harbor.ansteel.cn/lib/apache/skywalking-satellite:v1.2.0
    container_name: skywalking-satelite
    environment:
      SATELLITE_TELEMETRY_CLUSTER: safellite
      SATELLITE_TELEMETRY_SERVICE: safellite
      SATELLITE_TELEMETRY_INSTANCE: safellite-10.151.47.33
      SATELLITE_TELEMETRY_EXPORT_TYPE: metrics_service
      SATELLITE_GRPC_CLIENT: *****
```

- run docker 

```
docker comopse up -d
```

- error out put

```shell
[root@meta2-app1 ~]# docker logs -f 18420da8c9a9
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
/skywalking-satellite: line 0: /
                                ��Q�t�e@�rI: not found
/skywalking-satellite: line 1: ELF: not found
/skywalking-satellite: line 1: syntax error: unterminated quoted string
```

### Anything else

i readed the skywalking-satellite source,found dockerfile is error
```
RUN mv /src/bin/skywalking-satellite-${VERSION}-linux-amd64 /src/bin/skywalking-satellite
```

dockerfile not relate to platform , just copy amd64 file .

https://github.com/apache/skywalking-satellite/blob/main/docker/Dockerfile

```
FROM golang:1.19 as build

ARG VERSION="latest"

ENV CGO_ENABLED=0

WORKDIR /src

COPY . .

RUN VERSION=$VERSION make linux
RUN mv /src/bin/skywalking-satellite-${VERSION}-linux-amd64 /src/bin/skywalking-satellite

FROM alpine:3

RUN apk -U upgrade

VOLUME /skywalking/configs

WORKDIR /skywalking

COPY --from=build /src/bin/skywalking-satellite /
COPY --from=build /src/configs /skywalking/configs

EXPOSE 12800 11800 1234

CMD ["/skywalking-satellite", "start", "--config", "/skywalking/configs/satellite_config.yaml"]

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
