### ISSUE TITLE
[Feature] [Tracing] Add OTLP Tracing support as a Zipkin trace input

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#11261]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We are declaring to support [OTLP trace format through OTLP collector and forward to Zipkin receiver](https://skywalking.apache.org/docs/main/next/en/setup/backend/otlp-trace/). 

This works, but an extra component seems unnecessary.

OTLP trace format is logically the same as the Zipkin trace format, so, we just need to add a OLTP trace handler and an in-memory converter to Zipkin receiver.

### Use case

```yaml
receiver-otel:
  selector: ${SW_OTEL_RECEIVER:default}
  default:
    enabledHandlers: ${SW_OTEL_RECEIVER_ENABLED_HANDLERS:"otlp-metrics,otlp-logs"}
    enabledOtelMetricsRules: ....
```

We should add `otlp-trace` as an option to `enabledHandlers` to support this.

@kezhenxu94 Any suggestion?

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
