### ISSUE TITLE
Observability Of Kubernetes Some indicators do not have data

### ISSUE THREAD

**Issue by 5279314** [apache/skywalking#11815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Skywalking Shows K8s Metrics, Deployed by https://github.com/apache/skywalking-showcase/tree/main/deploy/platform/kubernetes/feature-kubernetes-monitor,  But `Namespace、Deployment ` NO Data,Is this a normal phenomenon?
<img width="1621" alt="image" src="https://github.com/apache/skywalking/assets/27267683/d2ecd1ff-480b-43b4-af11-4ca1a02fe2a2">
<img width="1598" alt="image" src="https://github.com/apache/skywalking/assets/27267683/60b2de62-57e7-40c0-bf54-5daff637f76a">

### What you expected to happen

Skywalking UI Can Show K8s Metrics.

### How to reproduce

otel-collector-config
```
  otel-collector-config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubernetes-cadvisor'
              kubernetes_sd_configs:
                - role: node
              scheme: https
              metrics_path: /metrics/cadvisor
              tls_config:
                insecure_skip_verify: true
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              authorization:
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_node_label_(.+)
                  replacement: $$1
                - source_labels: [ ]
                  target_label: cluster
                  replacement: k8s-cluster-1.23
            # @feature: kubernetes-monitor; configuration to scrape Kubernetes Endpoints metrics
            - job_name: kube-state-metrics
              scheme: https
              metrics_path: /metrics
              tls_config:
                insecure_skip_verify: true
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              authorization:
                credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [ __meta_kubernetes_service_label_app_kubernetes_io_name ]
                  regex: kube-state-metrics
                  replacement: $$1
                  action: keep
                - action: labelmap
                  regex: __meta_kubernetes_service_label_(.+)
                - source_labels: [ ]
                  target_label: cluster
                  replacement: k8s-cluster-1.23
```

### Anything else

skywalking Version: 9.6.0 or 9.7.0
OTel Version: opentelemetry-collector:0.85.0 or 0.92.0
Kubernetes Version:
```
 kubectl version --short
Client Version: v1.27.4.   
Kustomize Version: v5.0.1
Server Version: v1.27.4    # or 1.23.4
```

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
