### ISSUE TITLE
[Bug] Large mount of Text Display

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#11974]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

The large amount of text was taking up too much space on the page, making it difficult to read.

<img width="934" alt="image" src="https://github.com/apache/skywalking/assets/1960537/c27558d3-77e9-4afb-8fa1-2fb47c83ff07">

### What you expected to happen

When displaying large amounts of text in a limited space, truncating text and providing a "download" button can help. 

### How to reproduce

View property "sw".

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
It is better this could support pop out as show in a box with JSON formarter

**Comment by sksDonni** [comment]
Hi @hanahmily and @wu-sheng, I would like to take this up.

**Comment by sksDonni** [comment]
Hi @hanahmily, I am trying to add properties to my group, but its for some reason not reflecting in my UI frontend. I tried adding properties using both the terminal and the java client. 

This is the response I get back when I try to retrieve the properties of group sw.  I am able to see the group sw in the stream panel, but the properties of the group are not visible.

```
./bydbctl property get -g sw -n temp_data --id General-Service
Using config file: /Users/sukrutha/.bydbctl.yaml
property:
  leaseId: "0"
  metadata:
    container:
      createRevision: "62"
      group: sw
      id: 0
      modRevision: "75"
      name: temp_data
    id: General-Service
  tags:
  - key: name
    value:
      str:
        value: hello
  - key: state
    value:
      str:
        value: succeed
  ttl: ""
  updatedAt: "2024-03-06T15:36:18.075455Z"
  ```

<img width="1278" alt="Screenshot 2024-03-06 at 9 36 56 PM" src="https://github.com/apache/skywalking/assets/53624363/db9af966-9c47-43af-95e1-3e9c7d744396">

Any help would be appreciated.

**Comment by hanahmily** [comment]
Could you show me the details of the group of the property? The property page will show groups with "CATALOG_UNSPECIFIED".

**Comment by sksDonni** [comment]
```
./bydbctl group get -g sw_metric
Using config file: /Users/sukrutha/.bydbctl.yaml
group:
  catalog: CATALOG_MEASURE
  metadata:
    createRevision: "5"
    group: ""
    id: 0
    modRevision: "5"
    name: sw_metric
  resourceOpts:
    blockInterval:
      num: 2
      unit: UNIT_HOUR
    segmentInterval:
      num: 1
      unit: UNIT_DAY
    shardNum: 2
    ttl:
      num: 7
      unit: UNIT_DAY
  updatedAt: null
  ```

**Comment by hanahmily** [comment]
> catalog: CATALOG_MEASURE

You should create a group like below:

```yaml
group:
    catalog: CATALOG_UNSPECIFIED
...
```

I also filed an #11993 to fix this flaw.
