### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by OrezzerO** [apache/skywalking#12157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

I try to run oap server in docker with mysql as storage. Here is my  docker  compose file:
```yml
version: '2.1'

services:
  oap:
    image: apache/skywalking-oap-server:9.6.0-java17
    networks:
      - skywalking
    environment:
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES: vm
      TZ: Asia/Shanghai
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://xxx:3306/sw
      SW_DATA_SOURCE_USER: xxxx
      SW_DATA_SOURCE_PASSWORD: xxxx
      JAVA_OPTS: -Xms4G -Xmx4G
    volumes:
      - ./mysql-connector-j-8.0.32.jar:/skywalking/oap-libs/mysql-connector-j-8.0.32.jar

    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"

  oap-ui:
    image: apache/skywalking-ui:9.6.0-java17
    networks:
      - skywalking
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      JAVA_OPTS: -Xms2G -Xmx2G
    ports:
      - "8080:8080"

networks:
  skywalking:

```
I create a database  `sw` in mysql . When i run   `docker compose up` , oap log says `SELECT command denied to user 'xxxx'@'xxx' for table 'xxxx'`. 

Each time when i run `docker compose up` table name changes.  I go to mysql and check. table exists.  It seems that select command is executed async and  before table is created. 

Now I am running  `docker compose up` and  `docker compose down`  repeatedly. Each round can create one or two new table .

### What you expected to happen

1. Tables can be created once .and i do not need to restart container.

### How to reproduce

run my docker compose 

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
