### ISSUE TITLE
[Bug] Can not specify the kind cluster name in kind config

### ISSUE THREAD

**Issue by fgksgf** [apache/skywalking#12165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Infra E2E (apache/skywalking-infra-e2e)

### What happened

If we provide a name `test` in kind yaml, like:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
```
infra-e2e will fail to load images to the kind cluster, because we did not specify the kind name in code:
https://github.com/apache/skywalking-infra-e2e/blob/1485ae03f0ad90496ad7626a5ae4a6a73a1f6296/internal/components/setup/kind.go#L272-L280

https://github.com/apache/skywalking-infra-e2e/blob/1485ae03f0ad90496ad7626a5ae4a6a73a1f6296/internal/components/setup/kind.go#L208-L212

So it will use the default kind cluster name `kind`.

### What you expected to happen

infra-e2e should be able to load images to the kind cluster `test`.

### How to reproduce

Use this e2e config with the above `kind.yaml`:
```yaml
# e2e.yaml
setup:
  env: kind
  file: kind.yaml
  kind:
    import-images:
      - busybox:latest
   # ...
```

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
