### ISSUE TITLE
[Bug] skywalking 10 did not provides "/skywalking/bin/swctl", then can not check health

### ISSUE THREAD

**Issue by ldcsaa** [apache/skywalking#12223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

In skywalking 9.7.0 and before, uses these codes to check health in docker compose, but skywalking 10+, did not provides these tools:
```
services:
  skywalking:
    depends_on:
      elasticsearch:
        condition: service_healthy
    container_name: "skywalking"
    healthcheck:
      test: ["CMD", "/skywalking/bin/swctl", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
```

### What you expected to happen

provides tool: `/skywalking/bin/swctl`

### How to reproduce

just check the dir

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
Yes, we don't provide this in the image anymore.
Are you using the old compose file?

**Comment by ldcsaa** [comment]
> Yes, we don't provide this in the image anymore. Are you using the old compose file?

I will start `skywalking-ui` after  skywalking OAP server started succ. So I need to check skywalking health, these is my code:

```
  skywalking:
    depends_on:
      elasticsearch:
        condition: service_healthy
    container_name: "skywalking"
    healthcheck:
      test: ["CMD", "/skywalking/bin/swctl", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    environment:
      - "SW_TELEMETRY=prometheus"
      - "SW_OTEL_RECEIVER=default"
      - "SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES=oap"
      - "SW_HEALTH_CHECKER=default"
      - "SW_HEALTH_CHECKER_INTERVAL_SECONDS=30"
      - "SW_CORE_GRPC_PORT=11800"
      - "SW_TELEMETRY_PROMETHEUS_PORT=1234"
      - "SW_STORAGE=elasticsearch"
      - "SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200"
      - "SW_CORE_REST_PORT=12800"
      - "JAVA_OPTS=-Xms256m -Xmx512m"
    image: "registry.cn-hangzhou.aliyuncs.com/jessma/apache-skywalking:10.0.0"
    networks:
      - "soa-net"
    ports:
      - "11800:11800/tcp"
      - "1234:1234/tcp"
      - "12800:12800/tcp"
    volumes:
      - "./apache-skywalking/config/alarm-settings.yml:/skywalking/config/alarm-settings.yml"
      - "./apache-skywalking/config/application.yml:/skywalking/config/application.yml"
    working_dir: "/skywalking"

  skywalking-ui:
    depends_on:
      skywalking:
        condition: service_healthy
    container_name: "skywalking-ui"
    environment:
      - "SW_SERVER_PORT=8080"
      - "SW_OAP_ADDRESS=http://skywalking:12800"
      - "SW_TIMEOUT=10000"
      - "JAVA_OPTS=-Xms128m -Xmx256m"
    image: "registry.cn-hangzhou.aliyuncs.com/jessma/apache-skywalking-ui:10.0.0"
    networks:
      - "soa-net"
    ports:
      - "8787:8080/tcp"
    volumes:
      - "./apache-skywalking-ui/webapp/application.yml:/skywalking/webapp/application.yml"

```
