### ISSUE TITLE
[BanyanDB-UI] Missing Criteria Part in Measure Query 

### ISSUE THREAD

**Issue by hanahmily** [apache/skywalking#12301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

The measure read page failed to send "criteria" to the server. 

### What you expected to happen

The "criteria" should be passed to the server.

### How to reproduce

The input yaml is 

```yaml
timeRange:
  begin: '2024-06-05T08:02:22.643Z'
  end: '2024-06-05T08:17:22.643Z'
offset: 1
limit: 10
criteria:
  condition:
    name: entity_id
    op: BINARY_OP_EQ
    value:
      str:
        value: c2t5d2Fsa2luZy1zaG93Y2FzZTo6Z2F0ZXdheS5zYW1wbGUtc2VydmljZXM=.1
orderBy:
  indexRuleName: ''
  sort: SORT_UNSPECIFIED
```

But the HTTP request is 

```json
{"groups":["measure-minute"],"name":"kubernetes_service_http_call_success_count_minute","offset":1,"limit":10,"orderBy":{"indexRuleName":"","sort":"SORT_UNSPECIFIED"},"timeRange":{"begin":"2024-06-05T08:06:01.812Z","end":"2024-06-05T08:21:01.812Z"},"tagProjection":{"tagFamilies":[{"name":"storage-only","tags":["entity_id"]}]},"fieldProjection":{"names":["value"]}}
```

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
