### ISSUE TITLE
[BanyanDB]  Data Mismatch with OAL Metrics Using BanyanDB

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#12302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

I am currently using BanyanDB as the storage backend for my metrics. When writing metrics data using OAL, I have encountered a data mismatch issue. Here are the two OAL statements:
```
kubernetes_service_http_call_cpm = from(K8SService.*).filter(detectPoint == DetectPoint.SERVER).filter(type == "protocol").filter(protocol.type == "http").cpm();
kubernetes_service_http_call_success_count = from(K8SService.*).filter(detectPoint == DetectPoint.SERVER).filter(type == "protocol").filter(protocol.type == "http").filter(protocol.success == true).cpm();
```
Logically, `kubernetes_service_http_call_cpm` should be greater than or equal to `kubernetes_service_http_call_success_count`. However, after running BanyanDB for some time, I noticed that sometimes `call_success_count` exceeds `call_cpm`.

### Call CPM Query with Result
```
groups:
  - "measure-minute"
name: kubernetes_service_http_call_cpm_minute
timeRange:
  begin: '2024-06-05T06:30:00.000Z'
  end: '2024-06-05T09:30:00.000Z'
offset: 1
limit: 200
criteria:
  condition:
    name: entity_id
    op: BINARY_OP_EQ
    value:
      str:
        value: c2t5d2Fsa2luZy1zaG93Y2FzZTo6Z2F0ZXdheS5zYW1wbGUtc2VydmljZXM=.1
orderBy:
  indexRuleName: ''
  sort: SORT_UNSPECIFIED
tagProjection:
  tagFamilies:
    - name: "storage-only"
      tags:
        - "entity_id"
fieldProjection: 
  names:
    - "value"
```
[query-cpm-result.txt](https://github.com/user-attachments/files/15584944/query-cpm-result.txt)

### Success Count Query with Result
```yaml
groups:
  - "measure-minute"
name: kubernetes_service_http_call_success_count_minute
timeRange:
  begin: '2024-06-05T06:30:00.000Z'
  end: '2024-06-05T09:30:00.000Z'
offset: 1
limit: 200
criteria:
  condition:
    name: entity_id
    op: BINARY_OP_EQ
    value:
      str:
        value: c2t5d2Fsa2luZy1zaG93Y2FzZTo6Z2F0ZXdheS5zYW1wbGUtc2VydmljZXM=.1
orderBy:
  indexRuleName: ''
  sort: SORT_UNSPECIFIED
tagProjection:
  tagFamilies:
    - name: "storage-only"
      tags:
        - "entity_id"
fieldProjection: 
  names:
    - "value"
```
[query-success-rsult.txt](https://github.com/user-attachments/files/15584948/query-success-rsult.txt)

### What you expected to happen

`kubernetes_service_http_call_cpm` should always be greater than or equal to `kubernetes_service_http_call_success_count`.

### How to reproduce

1. Deploy the showcase as the following command: `FEATURE_FLAGS = banyandb,mesh-with-agent,cluster,kubernetes-monitor,satellite,rover make deploy.kubernetes`
2. Forward the UI: `kubectl port-forward svc/demo-ui 8080:80 --namespace skywalking-showcase`
3. Visit the Kubernetes Service Topology, and see the each node `success rate`: `http://localhost:8080/Kubernetes/Service/tab/1`

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
