### ISSUE TITLE
[Bug] Use Helm install Skywalking , but got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later. 

### ISSUE THREAD

**Issue by freshgeek** [apache/skywalking#12601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Use Helm install Skywalking , but got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later. 

### What you expected to happen

got error :  table: alarm_record does not exist. OAP is running in 'no-init' mode, waiting... retry 3s later.  
and oap  server is   unavailable  

### How to reproduce

my env :
- k8s v1.28.11
- rancher v2.9.1
- helm v3.15.2 

helm values : 

```
elasticsearch:
  config:
    password: hide
    user: admin
  ingress:
    enabled: true
    hosts:
      - es.hide
  persistence:
    enabled: true
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi    
oap:
  dynamicConfig:
    enabled: true
  image:
    repository: apache/skywalking-oap-server
    tag: 10.0.1
  storageType: elasticsearch
ui:
  image:
    repository: apache/skywalking-ui
    tag: 10.0.1
  ingress:
    enabled: true
    hosts:
      - sky-ui.hide

```

### Anything else

I searched for recent issues and discussions and found that it keeps mentioning init job. I observed that there was no init job generated and running during the installation process of helm (I cannot know if it failed to create or was created and then deleted)
- https://github.com/apache/skywalking/issues/11123
- https://github.com/apache/skywalking/issues/10540
- https://github.com/apache/skywalking/issues/10470
- https://github.com/apache/skywalking/issues/9486
- https://github.com/apache/skywalking/pull/8958
- https://github.com/apache/skywalking/discussions/9093

There is no mention of how to troubleshoot or solve the problem

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
