### ISSUE TITLE
[Feature] adapt Istio ALS new peer metadata attributes

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#12643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/istio/istio/pull/53274/files

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
Just tried out https://github.com/istio/istio/releases/tag/1.24.0-rc.0 and the filter_state becomes empty always, according to


> Peer metadata is now stored
>     in `filter_state.downstream_peer` and `filter_state.upstream_peer` instead
>     of `filter_state["wasm.downstream_peer"]` and
>     `filter_state["wasm.upstream_peer"]`.

it should have downstream_peer upstream_peer but not, after downgrading to 1.22, `filter_state["wasm.downstream_peer”]` and
     `filter_state["wasm.upstream_peer”]`  appear again so it’s probably not an issue of my setup

**Comment by kezhenxu94** [comment]
Tracked by https://github.com/istio/istio/issues/53769

**Comment by zirain** [comment]
a demo iop file as following:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFormat: |
      %FILTER_STATE(upstream_peer)% %FILTER_STATE(downstream_peer)% [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% requestSize=%BYTES_RECEIVED% responseSize=%BYTES_SENT% requestPath=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
    extensionProviders:
      - name: grpc-als
        envoyHttpAls:
          service: envoy-als.monitoring.svc.cluster.local
          port: 8080
    defaultProviders:
      accessLogging:
        - grpc-als
        - envoy
```
