### ISSUE TITLE
[Feature] Not able to find few apache skywalking metrics

### ISSUE THREAD

**Issue by amolngt** [apache/skywalking#12783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In rabbitmq dashboard, in queue menu-> there is one column called "Message Rates"-> incoming, deliver / get and ack. I want to know metrics for each so that i can use that in rules for setting alarms. I found it for incoming, but its NOT working. Basically I am trying multiple metrics for rabbitmq.

### Use case

```
rules:
  # Alarm for Incoming Message Rate
  incoming_message_rate_high:
    metrics-name: meter_rabbitmq_messages_published
    threshold: 10
    period: 1
    count: 3
    silence-period: 5
    expression: meter_rabbitmq_messages_published > 10
    message: "High incoming message rate detected messages per second."

hooks:
  webhook:
    default:
      is-default: true
      urls:
        - http://localhost:3000/webhook # Replace with your webhook URL
```
I followed this link-> [](https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-rabbitmq-monitoring/)

But didnt get much help. Please let me know what metrics rule i can use for "Message Rates"-> incoming, deliver / get and ack. **Plus if you any other important metrics for rabbitmq, then please mention that also. **

Thank you in advance.

### Are you willing to submit a pull request to implement this on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
