### ISSUE TITLE
[Bug] [skywalking-eyes] When using the fix command, the new license is simply added, not updated

### ISSUE THREAD

**Issue by redb0** [apache/skywalking#12886]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

License Tools (apache/skywalking-eyes)

### What happened

When using the fix command, the new license is simply added, not updated. 

### What you expected to happen

When executing the fix command, the license is updated if it is not valid.

### How to reproduce

I use config:

```yaml
header:
  license:
    copyright-owner: My
    software-name: Test
    content: |
      Project: [software-name]
      -----
      Copyright (C) [year] [owner], All Rights Reserved

  paths:
    - '**/test.py'
   
  comment: on-failure

  license-location-threshold: 10

  language:
    Python:
      extensions:
        - ".py"
```

My `test.py` file:

```python
print('foo')
```

when I use the fix command for the first time, the license is added normally:

```python
# Project: Test
# -----
# Copyright (C) 2024 My, All Rights Reserved

print('foo')
```

Next, I fix the license manually, for example, I replace Test with Test123. And I run the fix command again. 

```python
# Project: Test
# -----
# Copyright (C) 2024 My, All Rights Reserved

# Project: Test123
# -----
# Copyright (C) 2024 My, All Rights Reserved

print('foo')
```

Is it possible to make the license updated instead of adding a new one?

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
