### ISSUE TITLE
[Bug] banyandb quick start docker-compose run failed

### ISSUE THREAD

**Issue by eye-gu** [apache/skywalking#13060]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

```shell
docker compose -f ./docker-compose.yaml --project-name=banyandb-quickstart up -d
```

Running this command yields an error: `dependency failed to start: container banyandb has no healthcheck configured`

### What you expected to happen

start sucessfully

### How to reproduce

```shell
docker compose -f ./docker-compose.yaml --project-name=banyandb-quickstart up -d
```

### Anything else

I added a health check and successfully ran it:
```yaml
services:
  banyandb:
    image: ${BANYANDB_IMAGE:-apache/skywalking-banyandb:latest}
    container_name: banyandb
    command: standalone
    expose:
      - 17912
    ports:
    - 17913:17913
    networks:
      - demo
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z 127.0.0.1 17912 || exit 1" ]
      interval: 5s
      timeout: 60s
      retries: 120
```

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
