### ISSUE TITLE
[Feature] Alarm webhook support Bearer auth

### ISSUE THREAD

**Issue by MasamiYui** [apache/skywalking#13095]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

For security, usually the webhook http callback api has authentication, and Bearer is a common verification type. Can add a new feature to support this authentication method? If possible, I can implement it.

- alarm-settings.yml
```
hooks:
  webhook:  
    default:  
      is-default: true  
      urls:  
        http://127.0.0.1/notify/  
      #new feature: support bearer auth  
      authorization:   
        type: Bearer  
        credentials: {token}  
```

### Related issues

https://github.com/apache/skywalking/issues/6353 ,It is related to the http header, but it is not completed.

### Are you willing to submit a pull request to implement this on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
