### ISSUE TITLE
[Feature] Introduce separate config file for BanyanDB advacend settings

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#13092]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

```yaml
    # The group settings of record.
    # `gr` is the short name of the group settings of record.
    #
    # The "normal" section defines settings for datasets not specified in "super".
    # Each dataset will be grouped under a single group named "normal".
    grNormalShardNum: ${SW_STORAGE_BANYANDB_GR_NORMAL_SHARD_NUM:1}
    grNormalSIDays: ${SW_STORAGE_BANYANDB_GR_NORMAL_SI_DAYS:1}
    grNormalTTLDays: ${SW_STORAGE_BANYANDB_GR_NORMAL_TTL_DAYS:3}
    # "super" is a special dataset designed to store trace or log data that is too large for normal datasets.
    # Each super dataset will be a separate group in BanyanDB, following the settings defined in the "super" section.
    grSuperShardNum: ${SW_STORAGE_BANYANDB_GR_SUPER_SHARD_NUM:2}
    grSuperSIDays: ${SW_STORAGE_BANYANDB_GR_SUPER_SI_DAYS:1}
    grSuperTTLDays: ${SW_STORAGE_BANYANDB_GR_SUPER_TTL_DAYS:3}
    # The group settings of metrics.
    # `gm` is the short name of the group settings of metrics.
    #
    # OAP stores metrics based its granularity.
    # Valid values are "day", "hour", and "minute". That means metrics will be stored in the three separate groups.
    # Non-"minute" are governed by the "core.downsampling" setting.
    # For example, if "core.downsampling" is set to "hour", the "hour" will be used, while "day" are ignored.
    gmMinuteShardNum: ${SW_STORAGE_BANYANDB_GM_MINUTE_SHARD_NUM:2}
    gmMinuteSIDays: ${SW_STORAGE_BANYANDB_GM_MINUTE_SI_DAYS:1}
    gmMinuteTTLDays: ${SW_STORAGE_BANYANDB_GM_MINUTE_TTL_DAYS:7}
    gmHourShardNum: ${SW_STORAGE_BANYANDB_GM_HOUR_SHARD_NUM:1}
    gmHourSIDays: ${SW_STORAGE_BANYANDB_GM_HOUR_SI_DAYS:5}
    gmHourTTLDays: ${SW_STORAGE_BANYANDB_GM_HOUR_TTL_DAYS:15}
    gmDayShardNum: ${SW_STORAGE_BANYANDB_GM_DAY_SHARD_NUM:1}
    gmDaySIDays: ${SW_STORAGE_BANYANDB_GM_DAY_SI_DAYS:15}
    gmDayTTLDays: ${SW_STORAGE_BANYANDB_GM_DAY_TTL_DAYS:15}
    # If the metrics is marked as "index_mode", the metrics will be stored in the "index" group.
    # The "index" group is designed to store metrics that are used for indexing without value columns.
    # Such as `service_traffic`, `network_address_alias`, etc.
    # "index_mode" requires BanyanDB *0.8.0* or later.
    gmIndexShardNum: ${SW_STORAGE_BANYANDB_GM_INDEX_SHARD_NUM:2}
    gmIndexSIDays: ${SW_STORAGE_BANYANDB_GM_INDEX_SI_DAYS:15}
    gmIndexTTLDays: ${SW_STORAGE_BANYANDB_GM_INDEX_TTL_DAYS:15}
```

Due to the limitation of the `application.yml`, all configs are flat, and the names of these configs are not readable. So, let's bring a `bydb.yml` config file to provide hierarchy structure for those settings, for example

```yaml
groups:
  normal_records:
    shard_num:  ${SW_STORAGE_BANYANDB_GR_NORMAL_SHARD_NUM:1}
    segment_interval: ${SW_STORAGE_BANYANDB_GR_NORMAL_SI_DAYS:1}
    ttl: ${SW_STORAGE_BANYANDB_GR_NORMAL_TTL_DAYS:3}
  super_records:
    ...
  metrics_min:
    ...
  metrics_hour:
    ...
  metrics_day:
    ...
  metadata:
    # Index mode data only, traffic_*
    ...
```

This kind of new style could provide new clear configurations for end users. 
Meanwhile, we need to support https://github.com/apache/skywalking/issues/11945 which is another kind of group level configuration. Only some of the groups support hot-warm-cold setup, e.g., metadata would not have warm and cold data, as they are kept in hot only as there are heartbeat(last_ping) update with time.

FYI @hanahmily 

### Use case

We are also going to support system env override mechanism, as they are more friendly in k8s env.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
