### ISSUE TITLE
[Feature] [skywalking-ui] async-profiling duration options need shorter intervals for high-load applications

### ISSUE THREAD

**Issue by forgottener** [apache/skywalking#13282]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Background
The current async-profiling feature in SkyWalking UI provides duration options of 5, 10, and 15 minutes. While these durations work well for applications with moderate load, they create challenges for high-load Java applications where the profiling data can quickly exceed size limits.

### Problem
When profiling high-load Java applications, even a 5-minute sampling period can generate files exceeding 10MB, resulting in JFR_UPLOAD_FILE_TOO_LARGE_ERROR. This prevents effective continuous monitoring of these applications, as the profiling data cannot be properly uploaded and analyzed.

### Proposed Solution
Add shorter duration options for async-profiling in the skywalking-ui:
- Add 30-second and 1-minute options to the existing choices
- Consider adding a custom duration input with reasonable lower bounds

This enhancement would allow users to effectively profile high-load Java applications without encountering file size limitations

![Image](https://github.com/user-attachments/assets/c6c892b4-f2e0-44e9-8451-5f96755006b1)

### Are you willing to submit a pull request to implement this on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment]
I am good with shorter profiling duration.

**Comment by wu-sheng** [comment]
Meanwhile, I want to point out, the max file size is totally configurable.

```yaml
receiver-async-profiler:
  selector: ${SW_RECEIVER_ASYNC_PROFILER:default}
  default:
    # Used to manage the maximum size of the jfr file that can be received, the unit is Byte, default is 30M
    jfrMaxSize: ${SW_RECEIVER_ASYNC_PROFILER_JFR_MAX_SIZE:31457280}
```

It just requires more OAP memory to analyze the file.
