### ISSUE TITLE
[Feature] Enhance Top-N to support `filter`

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#13322]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

```yaml
   # endpoint metrics
   # `attr0` is defined in the `EndpointDecorator` as the Layer.
  - name: endpoint_cpm-layer
    metricName: endpoint_cpm
    groupByTagNames:
      - attr0
    sort: des
```

TopN supported multiple columns as conditions to do `group-by` pre-aggregation. Now, we have a further requirement to add extra filter conditions for this pre-aggregation, which is supported by the `criteria` field.

```yaml
   # endpoint metrics
   # `attr0` is defined in the `EndpointDecorator` as the Layer.
  - name: endpoint_cpm-layer
    metricName: endpoint_cpm
    groupByTagNames:
      - attr0
    sort: des
    criteria:
      le:
        op: "LOGICAL_OP_AND"
        right:
          condition:
            name: "attr1"
            op: "BINARY_OP_EQ"
            value:
              str:
                value: "service_1"
        left:
          condition:
            name: "attr2"
            op: "BINARY_OP_NE"
            value:
              str:
                value: "cluster2"
```

OAP will pick the proper topN name to match different on-demand queries.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
