### ISSUE TITLE
If there are more than 20 spans in a segment, some spans are not displayed.

### ISSUE THREAD

**Issue by dingsongjie** [apache/skywalking#2504]
If there are more than 20 spans in a segment, some spans are not displayed.

**Comment by wu-sheng** [comment]
@dingsongjie Which page? Could you show us some screenshot?

FYI @TinyAllen pay attention about this, if do not exist in RocketBot UI, I think we are good.

**Comment by dingsongjie** [comment]
1  This is a segment took a total of 83933 ms

![image](http://kan.027cgb.com/620321/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190422172925.png)
2   Click to enter details , Show only spans of 450 ms interval

![image](http://kan.027cgb.com/620321/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190422172814.png)

3 The span of this page should exceed 20

(![image](http://kan.027cgb.com/620321/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190422174102.png)

4 I have several pages like this.

**Comment by dingsongjie** [comment]
5  After a few minutes, I click on the details again , Page changed

![image](http://kan.027cgb.com/620321/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190422175203.png)

**Comment by wu-sheng** [comment]
The latency is possible because segments are saved in async way.

**Comment by dingsongjie** [comment]
Why are there only 20 spans in a segment?  I have a lot of apis like this

**Comment by wu-sheng** [comment]
> Why are there only 20 spans in a segment? I have a lot of apis like this

I don't know why actually. I think should be all.

**Comment by wu-sheng** [comment]
**segmentQueryMaxSize** has been added in SkyWalking config yml.

```yml
storage:
  elasticsearch:
    nameSpace: ${SW_NAMESPACE:""}
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:localhost:9200}
    user: ${SW_ES_USER:""}
    password: ${SW_ES_PASSWORD:""}
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:2}
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:0}
    # Batch process setting, refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.5/java-docs-bulk-processor.html
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:2000} # Execute the bulk every 2000 requests
    bulkSize: ${SW_STORAGE_ES_BULK_SIZE:20} # flush the bulk every 20mb
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
    metadataQueryMaxSize: ${SW_STORAGE_ES_QUERY_MAX_SIZE:5000}
    segmentQueryMaxSize: ${SW_STORAGE_ES_QUERY_SEGMENT_SIZE:200}
```
