### ISSUE TITLE
refresh error

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#2584]
Hello, I 'm using skywalking v6.1
Refresh the trace page and report an error
As shown below:

![image](https://user-images.githubusercontent.com/5441976/57191808-29c59600-6f5c-11e9-8937-918fcede7c7f.png)

ref https://github.com/apache/skywalking-rocketbot-ui/issues/91

**Comment by zxbu** [comment]
Spring Boot Actuator add `/trace`  as endpoints out of the box. 
I solved it by disable  `/trace`  endpoints. 
modify `webapp.yml` like this:

```yaml
server:
  port: 8080

collector:
  path: /graphql
  ribbon:
    ReadTimeout: 10000
    # Point to all backend's restHost:restPort, split by ,
    listOfServers: 127.0.0.1:12800

security:
  user:
    # username
    admin:
      # password
      password: admin

endpoints:
  trace:
   # disable  trace  endpoints
    enabled: false

```
