### ISSUE TITLE
about OAP cluster setup 

### ISSUE THREAD

**Issue by makingtime** [apache/skywalking#3159]
Please answer these questions before submitting your issue.

Why do you submit this issue?
- [×] Question

------

### Question

- What do you want to know?

Hi, I'm working on deploy an OAP cluster with zookeeper as coordinator,  I have read some official documents, and found the changes need to do are: 

#### Backend part

1. OAP Server instances

   base on [backend-cluster.md](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-cluster.md), change `cluster` segment of `application.yml` in each OAP Server instance, add zookeeper nodes info, mainly ip and port.

   eg. 

   ```
   cluster:
     zookeeper:
       nameSpace: ${SW_NAMESPACE:""}
       hostPort: ${SW_CLUSTER_ZK_HOST_PORT:zk_host1:2181,zk_host2:2181,zk_host3:2181}
       # Retry Policy
       baseSleepTimeMs: 1000 # initial amount of time to wait between retries
       maxRetries: 3 # max number of times to retry
   ```

   

2. UI

   base on [ui-setup.md](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/ui-setup.md),  change `webapp/webapp.yml`, add all OAP Server instaces' IP:PORT to `collector.ribbon.listOfServers`

   eg.

   ```
   collector:
     path: /graphql
     ribbon:
       ReadTimeout: 10000
       # Point to all backend's restHost:restPort, split by , 
       listOfServers: OAP_SERVER1:12800,OAP_SERVER2:12800
   ```

   

#### Agent part

base on [java-agent/README.md](https://github.com/apache/skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md), change `collector.backend_service`, add all OAP Server instaces' IP:PORT to `agent/config/agent.config`

eg.

```
collector.backend_service=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:OAP_SERVER1:11800,OAP_SERVER2:11800}
```

#### Questions

I'm new to Skywalking, and I'm not quite understand how skywalking OAP cluster works, would appreciate some help to below questions:

1. could you help confirm if there are anything that I miss? do I need to setup a load balancer for OAP Servers?
2. if we config multiple OAP servers in `agent.config`, when a java agent sends out data, which OAP server will it be sent to?  or do we need to setup a load balance server, and use it for `collector.backend_service` in `agent.config`?
3. when we config multiple OAP servers in RocketbotUI's `webapp/webapp.yml`, how does RocketbotUI decide which OAP server to send graphQL request to?

 A little suggestion: I think it will be best if we have a complete guide for OAP cluster setup (maybe include UI and agent setup links).

Thanks!
