### ISSUE TITLE
nacos and 6.2.0

### ISSUE THREAD

**Issue by Dauber01** [apache/skywalking#3268]
i used the 6.2.0,use nacos as the cluster,then i run three skywalking oap instance,and in nacos it show like this
![image](https://user-images.githubusercontent.com/28582852/63011118-3beb9480-beba-11e9-8372-bcd65c2f54b8.png)
and one instance throw exception like this,i have clear the elastic search before i update 6.1.0 to 6.2.0

**Comment by wu-sheng** [comment]
Which exception? Do you miss it?

**Comment by Dauber01** [comment]
2019-08-14T09:44:28.692206051Z 2019-08-14 17:44:28,692 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher -51103 [grpc-default-executor-0] WARN  [] - Can't found service by service instance id from cache, service instance id is: 55
2019-08-14T09:44:28.945138635Z 2019-08-14 17:44:28,944 - org.apache.skywalking.oap.server.receiver.jvm.provider.handler.JVMSourceDispatcher -51355 [grpc-default-executor-0] WARN  [] - Can't found service by service instance id from cache, service instance id is: 56
the WARNINGlike this

**Comment by wu-sheng** [comment]
This means you do upgrade in OAP backend, but don't reboot all agents.

**Comment by Dauber01** [comment]
and could  i ask why the nacos show there is only one instance like the picture ↑, but infacet i run three skywalking oap in my server

**Comment by wu-sheng** [comment]
I don't know that for sure. But basically, no matter how many nodes, oap cluster is not working.

**Comment by Dauber01** [comment]
sorrry,i don't hnow what you mean ,is meaning that the the nacos is not working with the 6.2.0 as cluster?

**Comment by Dauber01** [comment]
the nacos is support in 6.2.0 or 6.3.0 .I see the tag 6.2.0 aready have the propeties of nacos

**Comment by wu-sheng** [comment]
I am talking about warning bug. Fix that first.
1. Erase es
1. Reboot agent
1. Reboot oap

Make sure both of all be set.

**Comment by kezhenxu94** [comment]
> and could i ask why the nacos show there is only one instance like the picture ↑, but infacet i run three skywalking oap in my server

@Dauber01 Please make sure that all the three OAP nodes started successfully, if you start all of them in a single server, pay special attention to the buffer file path, which may conflict with each other, resulting only one that can start successfully, as for the nacos cluster implementation, I've tested again, it works as expected

```yml

receiver-trace:
  default:
    bufferPath: ${SW_RECEIVER_BUFFER_PATH:../trace-buffer2/}  # Path to trace buffer files, suggest to use absolute path

# ...

service-mesh:
  default:
    bufferPath: ${SW_SERVICE_MESH_BUFFER_PATH:../mesh-buffer2/}  # Path to trace buffer files, suggest to use absolute path

```

![image](https://user-images.githubusercontent.com/15965696/63022949-98f54380-bed6-11e9-936f-70f9273b2284.png)
