### ISSUE TITLE
How to config envoy to upload the trace data

### ISSUE THREAD

**Issue by UchihaWen** [apache/skywalking#3685]
help needed!!!
When I use the example https://github.com/apache/skywalking/blob/master/docs/en/setup/envoy/metrics_service_setting.md 
I can not find any information in the skywalking UI . Something i configured wrong?
I just use the same file in the example to test, and I use this config below too, it did not work neither

---
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
stats_sinks:
  - name: envoy.metrics_service
    config:
      grpc_service:
        envoy_grpc:
          cluster_name: service_skywalking
node:
  id: ingress
  cluster: test
  locality:
    region: ap-southeast-1
    zone: zone1
    sub_zone: subzone1
  metadata:
    skywalking: iscool
    envoy: isawesome
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: test }
          http_filters:
          - name: envoy.router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8080 }}]
  - name: service_skywalking
    connect_timeout: 5s
    type: LOGICAL_DNS
    http2_protocol_options: {}
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_skywalking
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    # This is the port where SkyWalking serving the Envoy Metrics Service gRPC stream.
                    port_value: 11800
---

**Comment by wu-sheng** [comment]
Envoy must be controlled by istio, read #3682 , search my speech at KubeCon China about als solution.

**Comment by hanahmily** [comment]
@UchihaWen if your listener config comes from static config file instead of LDS, I think I can help. pls follow this example:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
            - name: envoy.http_grpc_access_log
              config:
                common_config:
                  log_name: skywalking
                  grpc_service:
                    envoy_grpc:
                      cluster_name: service_skywalking
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: www.google.com
                  cluster: service_google
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 5s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
    tls_context:
      sni: www.google.com
  - name: service_log
    connect_timeout: 5s
    type: STATIC
    http2_protocol_options: {}
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_skywalking
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 11800
```
Even you pick up LDS, you can access envoy api to add above ALS in listener.
Good luck
