### ISSUE TITLE
About the ES indexRefreshInterval 

### ISSUE THREAD

**Issue by MoDann** [apache/skywalking#3768]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The ES indexRefreshInterval configuration
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking：6.3.0
OS：cento6
JRE：java8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
can you support the ES indexRefreshInterval configuration？Like indexRefreshInterval: ${SW_STORAGE_ES_INDEX_REFRESH_INTERVAL:30}

**Comment by wu-sheng** [comment]
There are configs there
```yaml
flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:1000} # Execute the bulk every 1000 requests
concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests
```
