### ISSUE TITLE
How should database access and JVM instance alert rules be configured?

### ISSUE THREAD

**Issue by zjie0723** [apache/skywalking#4207]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- How should database access and JVM instance alert rules be configured? 
  

```
# database metrics
  database_access_resp_time_rule:
    metrics-name: database_access_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of database {name} is more than 1000ms in 3 minutes of last 10 minutes.
  database_access_sla_rule:
    metrics-name: database_access_sla
    op: "<"
    threshold: 8000
    period: 10
    count: 2
    silence-period: 3
    message: Successful rate of database {name} is lower than 80% in 2 minutes of last 10 minutes.

# JVM metrics
  instance_jvm_cpu_rule:
    metrics-name: instance_jvm_cpu
    op: ">"
    threshold: 60
    period: 10
    count: 2
    silence-period: 3
    message: JVM instances have been used more than 80% in the last 2 minutes.
  instance_jvm_young_gc_time_rule:
    metrics-name: instance_jvm_young_gc_time
    op: ">"
    threshold: 100
    period: 10
    count: 3
    silence-period: 5
    message: JVM Young GC time.
  instance_jvm_young_gc_count_rule:
    metrics-name: instance_jvm_young_gc_count
    op: ">"
    threshold: 1
    period: 10
    count: 3
    silence-period: 5
    message: JVM Young GC count.

```
