### ISSUE TITLE
How to set a password for WebUI with v6.6.0?

### ISSUE THREAD

**Issue by Cassuis** [apache/skywalking#4234]
___
### Question
- I try to edit webapp.yml to set a webui password,but it seems don't works! 
___
### Bug
-v6.6.0
___
### My webapp.yml
```
server:
  port: 8080

collector:
  path: /graphql
  ribbon:
    ReadTimeout: 10000
    # Point to all backend's restHost:restPort, split by ,
    listOfServers: 0.0.0.0:12800

security:
  user:
    admin:
      password: admin
```
