### ISSUE TITLE
Telemetry Metrics enable failed

### ISSUE THREAD

**Issue by regardfs** [apache/skywalking#4866]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
According to this page: [https://github.com/apache/skywalking/blob/v6.6.0/docs/en/setup/backend/backend-telemetry.md](https://github.com/apache/skywalking/blob/v6.6.0/docs/en/setup/backend/backend-telemetry.md)

Repro Steps:
1. add telemetry config to  code/skywalking/oap-server/server-bootstrap/src/main/resources/application.yml 
```
telemetry:                                                                            
  prometheus:                                                                         
    host: 127.0.0.1                                                                   
    port: 1543
```
2. ./mvnw clean package -DskipTests 
3. rebuld docker image with 6.6 es7-base and es7-oap
4. helm install skywalking
5. no 1543 port in pod or docker
6. login pod and find telemetry: none in file of /skywalking/config/application.yml

How could i enable this ?

**Comment by wu-sheng** [comment]
That depends on how you package image, I think. This is only related to the docker file and port expose.

**Comment by regardfs** [comment]
First of all, I only configured the `SW_TELEMETRY_PROMETHEUS_HOST` and `SW_TELEMETRY_PROMETHEUS_PORT` in my  helm values.yml,  but not work;
```
    Environment:
      SW_ES_USER:                    elastic
      SW_ES_PASSWORD:                8bla12O3hQ7u4WJ43N2xzgB4
      JAVA_OPTS:                     -Xmx2g -Xms2g -Dmode=no-init
      SW_CLUSTER:                    kubernetes
      SW_CLUSTER_K8S_NAMESPACE:      default
      SW_TELEMETRY_PROMETHEUS_HOST:  0.0.0.0
      SW_TELEMETRY_PROMETHEUS_PORT:  1543
```
Furthermore, I find code in `https://github.com/apache/skywalking/blob/v6.6.0/oap-server/server-bootstrap/src/main/resources/application.yml#L178`, It had been annotated by default, So I download the code and enable this like below:
```
telemetry:
  prometheus:
    host: ${SW_TELEMETRY_PROMETHEUS_HOST:0.0.0.0}
    port: ${SW_TELEMETRY_PROMETHEUS_PORT:1543}
```
But no port 1543 started in my oap-server pod, I had read all doc but not find any more detail about the telemetry.
I would be greateful if you could provide some advice and detail on this function....
