### ISSUE TITLE
use so11y Self Observability cannot find data from UI

### ISSUE THREAD

**Issue by pingliu** [apache/skywalking#5056]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [X] Bug

___
### Question
- What do you want to know?
when I use Telemetry for backend. config is
```
receiver-so11y:
  default:
telemetry:
  so11y:
```
I cannot check them out through UI !

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking:6.4.0
jdk:1.8
