### ISSUE TITLE
Support alarm labels

### ISSUE THREAD

**Issue by dagmom** [apache/skywalking#5124]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- Alarm support level

Many monitoring system alarms support levels, such as info, warn, critical.
I want to enhance the alarm rules with alert level.

**Comment by wu-sheng** [comment]
What are the use cases of that? As the SkyWalking doesn't react from it, can't see the real value.

**Comment by dagmom** [comment]
@wu-sheng In large data centers, there can be many alerts.
Some alarms must be dealt with immediately. And some may cause problems, we'll deal with that later.
For example successful rate of endpoint lower than 75% is warning, and lower than 50% is critical.

**Comment by wu-sheng** [comment]
OK, If you are talking about large scale env, I would recommend bringing the `tag` system into an alarm message. For alarm rule, you could set multiple tags(name: value), if the alarm happens, these tags would be sent with message too. What do you think?

**Comment by dagmom** [comment]
@wu-sheng 
Like prometheus alertmanager?
```yml
groups:
- name: PromRules
  rules:
  - alert: Node-Load
    annotations: {description: 'descTest',
      summary: 'summaryTest'}
    expr: node_load1 > 0.01
    for: 30s
    labels: {resType: 'Node',severity: 'warning'}
  - alert: Node-Load
    annotations: {description: 'descTest',
      summary: 'summaryTest'}
    expr: node_load1 > 0.02
    for: 30s
    labels: {resType: 'Node',severity: 'critical'}
```
