### ISSUE TITLE
Request Help : What is the best practice to store ES data for just 7 or 14 days?

### ISSUE THREAD

**Issue by totemofwolf** [apache/skywalking#5332]
- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What is the best practice to store ES data for just 7 or 14 days?
- Is startup env setting `SW_CORE_DAY_METRIC_DATA_TTL: 7` enough?
- Should we `remove` all indices' alias before `DELETE` them?

``` bash
POST /_aliases
{
    "actions": [
        { "remove": { "index": "segment-20200810", "alias": "segment" }}
    ]
}
```
___
### Bug
- docker image version oap : apache/skywalking-oap-server:7.0.0-es7
- k8s deployment of oap :

``` yaml
      containers:
      - name: skywalking-oap
        image: "apache/skywalking-oap-server:7.0.0-es7"
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: "-Xmx4g -Xms4g -Dmode=no-init"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "skywalking-prod"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,release=skywalking-prod,component=skywalking-oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_TRACE_SAMPLE_RATE
          value: "5000"
        - name: SW_CORE_DAY_METRIC_DATA_TTL
          value: "7"
```
