### ISSUE TITLE
Support group concept in the alarm core.

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#5475]
This is a useful feature in the alarm core. In the current implementation, we could put the `rules` for different metrics. But, in a real SRE use case, alarm rules sometimes should be combined(and/or) by several different metrics. Such as `traffic(CPM) > n && successful rate < m%` is a very typical one.

I suggest we add a new config section, named `group`(optional), in the `alarm-settings.yml` file. I have two ideas
1. The simple one is, we add `should` and `must` conditions, like this
```yml
groups:
  group_name_1:
    should:
    - metrics_1
    - metrics_2
    must:
    - metrics_3
    - metrics_4
    message: xxxxx
```
This means ( metrics_1 || metrics_2 ) && ( metrics_3 && metrics_4 ). This idea is from ElasticSearch API, which is easy to implement from the grammar parsing perspective.

2. The best one is, we support real grammar expression, which could use `antlr4` like the OAL core engine.
```
groups:yml
  group_name_1: 
    expression: metrics_1 && metrics_2 && ( metrics_3 || metrics_4 )
    message: xxxxx
```

@xbkaishui as you are quite active these days, do you have the interest to do this? And what is your preference?

@mrproliu @JaredTan95 @kezhenxu94 As you were involved in the alarm code, what do you think about this?
