### ISSUE TITLE
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener

### ISSUE THREAD

**Issue by 2084350** [apache/skywalking#5771]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
my skywalking metrics data lost, only two log:

2020-11-02 07:44:46,187 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer -1813149 [pool-6-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.

==========================================
oap    | Nov 02, 2020 7:45:10 AM io.grpc.internal.SerializingExecutor run
oap    | SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@418719f7
oap    | io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
oap    |        at io.grpc.Status.asRuntimeException(Status.java:524)
oap    |        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:368)
oap    |        at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onError(TraceSegmentReportServiceHandler.java:84)
oap    |        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
oap    |        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
oap    |        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
oap    |        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:867)
oap    |        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
oap    |        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
oap    |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oap    |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oap    |        at java.lang.Thread.run(Thread.java:748)

___
### Bug
- Which version of SkyWalking, OS and JRE?
 skywalking 8.1.0
 jre 1.8.3

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
  my skywalking config：
```
   downsampling:
      - Hour
      - Day
    # Set a timeout on metrics data. After the timeout has expired, the metrics data will automatically be deleted.
    enableDataKeeperExecutor: ${SW_CORE_ENABLE_DATA_KEEPER_EXECUTOR:true} # Turn it off then automatically metrics data delete will be close.
    dataKeeperExecutePeriod: ${SW_CORE_DATA_KEEPER_EXECUTE_PERIOD:5} # How often the data keeper executor runs periodically, unit is minute
    recordDataTTL: ${SW_CORE_RECORD_DATA_TTL:3} # Unit is day
    metricsDataTTL: ${SW_CORE_METRICS_DATA_TTL:7} # Unit is day
```
