### ISSUE TITLE
alarm config properties meaning question

### ISSUE THREAD

**Issue by Diyuzhou** [apache/skywalking#5820]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ *] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
alarm-setting meaning
___
### Bug
- Which version of SkyWalking, OS and JRE?
8.2.0

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
```
service_sla_rule:
    # Metrics value need to be long, double or int
    metrics-name: service_sla
    op: "<"
    threshold: 8000
    # The length of time to evaluate the metrics
    period: 10
    # How many times after the metrics match the condition, will trigger alarm
    count: 2
    # How many times of checks, the alarm keeps silence after alarm triggered, default as same as period.
    silence-period: 3
    message: Successful rate of service {name} is lower than 80% in 2 minutes of last 10 minutes
```
count means [How many times after the metrics match the condition, will trigger alarm]
but refers to message [Successful rate of service {name} is lower than 80% in 2 minutes of last 10 minutes]
should that be -> [Successful rate of service {name} is lower than 80% in 2 times of last 10 minutes not 2 minutes] ?
here make me confuse
