### ISSUE TITLE
why prometheus fetcher  cannot save  metrics of the same name for different services

### ISSUE THREAD

**Issue by wuwenrufeng** [apache/skywalking#5964]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
    - Question or discussion

___
### Question
- What do you want to know?
why prometheus fetcher  cannot save  metrics of the same name for different services

- What happened?
   I added two files in the $CLASSPATH/fetcher-prom-rules, first service name is a_server,second service name is b_server, and they have same metirc name(instance_count), but i only get first metrics.
  - t1.yaml
  ```yaml
  fetcherInterval: PT30S
  fetcherTimeout: PT10S
  metricsPath: /metrics
  staticConfig:
    # targets will be labeled as "instance"
    targets:
      - url: http://172.31.1.116:5000/metrics
        sslCaFilePath:
    labels:
      service: a_server
  defaultMetricLevel: instance(['service'], ['instance'])
  metricsRules:
    - name: instance_count
      exp: latest count.tagEqual('name', 'beijing')
  ```
- t2.yaml
  ```yaml
  fetcherInterval: PT30S
  fetcherTimeout: PT10S
  metricsPath: /metrics
  staticConfig:
    # targets will be labeled as "instance"
    targets:
      - url: http://172.31.1.116:5000/metrics
        sslCaFilePath:
    labels:
      service: b_server
  defaultMetricLevel: instance(['service'], ['instance'])
  metricsRules:
    - name: instance_count
      exp: latest count.tagEqual('name', 'tianjin')
  ```
  - es backend:
![Snipaste_2020-12-07_17-05-12](https://user-images.githubusercontent.com/45844514/101331129-7eef2980-38ae-11eb-9d44-03d7c965b411.png)
  - sw UI
    
![cSnipaste_2020-12-07_17-09-13](https://user-images.githubusercontent.com/45844514/101331467-ff158f00-38ae-11eb-9ceb-b24592d1d0a3.png)
![aSnipaste_2020-12-07_17-08-14](https://user-images.githubusercontent.com/45844514/101331478-03da4300-38af-11eb-9bdc-ef8023356440.png)
![bSnipaste_2020-12-07_17-08-31](https://user-images.githubusercontent.com/45844514/101331540-1d7b8a80-38af-11eb-9ea2-ca00e7f17918.png)

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
