### ISSUE TITLE
Cannot pull indicator after setting metrics URL 

### ISSUE THREAD

**Issue by wuwenrufeng** [apache/skywalking#5975]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
  - Bug

### Bug
- Which version of SkyWalking, OS and JRE?
   8.2.0  centos7 1.8.2

- What happened?
   I set fetcher metrics url is prometheus federate address ,eg: http://prometheus:32702/federate?match[]={srv_name=%22srv-test%22}  ,but it don't work , raise one warning.
  fetcher yaml file below:
  ```yaml
  fetcherInterval: PT15S
  fetcherTimeout: PT10S
  metricsPath: /metrics
  staticConfig:
  # targets will be labeled as "instance"
  targets:
    - url: http://prometheus:32702/federate?match[]={srv_name=%22srv-test%22}
      sslCaFilePath:
  labels:
    service: iot-server
  defaultMetricLevel: instance(['service'], ['instance'])
  metricsRules:
    - name: instance_cpu_limits
      exp: latest container_resource_limits_cpu.tagEqual('namespace','test')
 ```
  warning info below:
<img width="1437" alt="iiSnipaste_2020-12-08_17-55-35" src="https://user-images.githubusercontent.com/45844514/101469074-35224400-397f-11eb-862f-6ddfa90a760f.png">

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
