### ISSUE TITLE
config  receiver-trace sampleRate is not work,How should I configure it？

### ISSUE THREAD

**Issue by qianglu1989** [apache/skywalking#6062]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

config  receiver-trace sampleRate is not work ，How should I configure it？ I can't find the documentation
```
receiver-trace:
  selector: ${SW_RECEIVER_TRACE:default}
  default:
    sampleRate: ${SW_RECEIVER_TRACE_SAMPLE_RATE:4000}
```

debug code ->>>>>

![image](https://user-images.githubusercontent.com/8486184/102964207-0501a600-4526-11eb-9307-ff29f5874ea9.png)

 
skywalking 8.3
es 7.2
jkd 1.8
