### ISSUE TITLE
8.3.0 SelfObservability DashBoard  always show zero

### ISSUE THREAD

**Issue by ZhouZiHe** [apache/skywalking#6230]
We used skywalking-8.3.0 . Our SelfObservability always shows zero 
Our applaction.yaml like this : 
![image](https://user-images.githubusercontent.com/20511319/105020522-5b5cf880-5a82-11eb-9c64-cd8135ae22ad.png)
![image](https://user-images.githubusercontent.com/20511319/105020685-97905900-5a82-11eb-96fd-e061b248782e.png)
Our self.yaml like this :
![image](https://user-images.githubusercontent.com/20511319/105020820-c1e21680-5a82-11eb-930a-50491ff5ccb6.png)
But our SelfObservability DashBoard always show zero
![image](https://user-images.githubusercontent.com/20511319/105020999-fce44a00-5a82-11eb-8428-935e4638d8b1.png)
We want to know whether we configured error .

**Comment by wu-sheng** [comment]
Do you send any data to OAP? Such as trace, metrica, etc.

**Comment by ZhouZiHe** [comment]
> Do you send any data to OAP? Such as trace, metrica, etc.
We send trace data to oap server by grpc

**Comment by ZhouZiHe** [comment]
> Do you send any data to OAP? Such as trace, metrica, etc.

We send trace data to oap server by grpc
And when we test using " curl http://172.16.86.64:1234 " , it can also show data like this :
![image](https://user-images.githubusercontent.com/20511319/105027636-f8239400-5a8a-11eb-9b57-86921781e08e.png)

**Comment by arugal** [comment]
![image](https://user-images.githubusercontent.com/26432832/105027765-2012f780-5a8b-11eb-9b5f-210644d037ae.png)
@ZhouZiHe  `self.yaml looks like `0.0.0.0:1234`, please confirm

**Comment by wu-sheng** [comment]
Yes, doc says so. Please fix.
https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-telemetry.md

**Comment by ZhouZiHe** [comment]
> ![image](https://user-images.githubusercontent.com/26432832/105027765-2012f780-5a8b-11eb-9b5f-210644d037ae.png)
> @ZhouZiHe `self.yaml` looks like `0.0.0.0:1234`, please confirm



> ![image](https://user-images.githubusercontent.com/26432832/105027765-2012f780-5a8b-11eb-9b5f-210644d037ae.png)
> @ZhouZiHe `self.yaml` looks like `0.0.0.0:1234`, please confirm
there is no problem this is our develop config 
when we use online config is this :
![image](https://user-images.githubusercontent.com/20511319/105028156-a2032080-5a8b-11eb-927c-a68fa636d257.png)

**Comment by arugal** [comment]
```yaml
version: '3.8'
services:
  oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    container_name: oap
    restart: always
    ports:
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_STORAGE: h2
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      SW_PROMETHEUS_FETCHER: default
  ui:
    image: apache/skywalking-ui:8.3.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
```
![image](https://user-images.githubusercontent.com/26432832/105030212-72094c80-5a8e-11eb-8c04-d19ff6ad96fe.png)

@ZhouZiHe Did you set the`prometheus-fetcher? https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-telemetry.md#self-observability
