### ISSUE TITLE
Support elastic / beats log-receiver

### ISSUE THREAD

**Issue by wu-sheng** [apache/skywalking#6261]
[Elastic filebeats](https://github.com/elastic/beats) is still released under Apache 2.0. So, we could consider to support its format as a new log receiver too.

@dmsolr leads on this.

**Comment by hailin0** [comment]
I am interested in it. what can I do?

**Comment by wu-sheng** [comment]
@dmsolr Have you began this process?
@hailin0 This means we could adopt logs from Elastic filebeat. and trandfer them to OAP log analyzer.

**Comment by hailin0** [comment]
> @dmsolr Have you began this process?
> @hailin0 This means we could adopt logs from Elastic filebeat. and trandfer them to OAP log analyzer.

I created a custom filebeat output plugin before.

Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.

**Comment by wu-sheng** [comment]
> I created a custom filebeat output plugin before.
> 
> Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.

Any benefit of that? Today, we are adopting(supporting) others protocol, such as #6176. Because we nearly only need TEXT/JSON/YAML formatted logs with service/instance/endpoint(optional) names, should be enough for LAL #6264

**Comment by hailin0** [comment]
> > I created a custom filebeat output plugin before.
> > Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.
> 
> Any benefit of that? Today, we are adopting(supporting) others protocol, such as #6176. Because we nearly only need TEXT/JSON/YAML formatted logs with service/instance/endpoint(optional) names, should be enough for LAL #6264

I mean, how does skywalking receive the log from the beat?

Beats now supports Kafka transmission, so skywalking/beats-log-receiver only needs to support consuming beats data from kafka, right?

**Comment by dmsolr** [comment]
> Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.

I have not gotten started yet. Welcome @hailin0 
I think that is okay if you would like to write an output plugin. But this plugin may be contributing to elastic/beats.

**Comment by dmsolr** [comment]
> Beats now supports Kafka transmission, so skywalking/beats-log-receiver only needs to support consuming beats data from kafka, right?

Yeap. We adapt to elastic/beats.

**Comment by hailin0** [comment]
> > Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.
> 
> I have not gotten started yet. Welcome @hailin0
> I think that is okay if you would like to write an output plugin. But this plugin may be contributing to elastic/beats.



> > Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.
> 
> I have not gotten started yet. Welcome @hailin0
> I think that is okay if you would like to write an output plugin. But this plugin may be contributing to elastic/beats.

Yes, directly send beat data to skywalking/beats-log-receiver via tcp, need to build  skywalking output plugin of beats

**Comment by wu-sheng** [comment]
> > > Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.
> > 
> > 
> > I have not gotten started yet. Welcome @hailin0
> > I think that is okay if you would like to write an output plugin. But this plugin may be contributing to elastic/beats.
> 
> > > Now, do we need to create a filebeat output plugin of skywalking? and receive and process logs in OAP.
> > 
> > 
> > I have not gotten started yet. Welcome @hailin0
> > I think that is okay if you would like to write an output plugin. But this plugin may be contributing to elastic/beats.
> 
> Yes, directly send beat data to skywalking/beats-log-receiver via tcp, need to build skywalking output plugin of beats

I didn't read their documentation, besides Kafka, I think there must be some formats with direct RPC, don't they? Of course Kafka is fine, we have kafka consumer for our own for a while. It is not a problem.
The reasons I didn't ask for the beat's plugin besides above are
1. I am not sure whether Elastic will accept the pull request or not, if YES, then no problem.
2. New plugin means, users have to upgrade their filebeat or add a new plugin. Either, there is extra works. If those don't provide benefits, we are wasting time on both sides.

Still, you both know more details than I did.

**Comment by hailin0** [comment]
> 1. I am not sure whether Elastic will accept the pull request or not, if YES, then no problem.

This is difficult. reference: https://github.com/streamnative/pulsar-beat-output

It's easier to support consuming of beats data from kafka

**Comment by wu-sheng** [comment]
> > 1. I am not sure whether Elastic will accept the pull request or not, if YES, then no problem.
> 
> This is difficult. reference: https://github.com/streamnative/pulsar-beat-output
> 
> It's easier to support consuming of beats data from kafka

Then Kafka consumer it is. There is no block for us to do this. But pay attention on the metadata(service/instance), whether they provide those?

**Comment by wu-sheng** [comment]
@dmsolr @hailin0 Who will lead this? And what is the agenda(time)?

**Comment by hailin0** [comment]
> But pay attention on the metadata(service/instance), whether they provide those?

beats metadata example:
```json

{
  "@timestamp": "2019-09-02T04:10:20.423Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.3.0",
    "pipeline": "filebeat-7.3.0-system-syslog-pipeline"
  },
  "agent": {
    "hostname": "bogon",
    "id": "a44c8bbc-723c-4982-84f8-bad50c80fac9",
    "version": "7.3.0",
    "type": "filebeat",
    "ephemeral_id": "50725221-8fe5-48be-af66-89e43fadf1c2"
  },
  "input": {
    "type": "log"
  },
  "log": {
    "offset": 21029,
    "file": {
      "path": "/var/log/messages"
    }
  },
 ...
}
```

**Comment by wu-sheng** [comment]
OK, @hailin0 I think hostname is not enough, we need the service name at least.

@kezhenxu94 Log ecosystem adoption seems need LAL too(#6264), we need to support to isolate the metadata from the log text.

**Comment by hailin0** [comment]
> we need the service name at least.

This requires user configuration, but is not stable enough, so it is easy to make error

**Comment by wu-sheng** [comment]
> > we need the service name at least.
> 
> This requires user configuration, but is not stable enough, so it is easy to make error

Logically, we will need some ways, either elastic's configuration, or we could isolate the information from the log text. If neither, I can't see the way. But anyway, this is user's choice.

**Comment by hailin0** [comment]
> either elastic's configuration, or we could isolate the information from the log text

There are two possible ways:
1. The user configures the service name in each beats node. [beats add fields](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html)
2. The beats node parses and reads the service name from log.[beats copy fields](https://www.elastic.co/guide/en/beats/filebeat/current/copy-fields.html)

This is user's choice.

**Comment by wu-sheng** [comment]
Let's add these fields into the log's tags. @kezhenxu94 The LAL should support convert some tags as entity names.

**Comment by hailin0** [comment]
> 1. The user configures the service name in each beats node. [beats add fields](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html)

'add_fileds' can be read system environment variable,  the service name can be obtained effectively in the service deployed by k8s

**Comment by wu-sheng** [comment]
> > 1. The user configures the service name in each beats node. [beats add fields](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html)
> 
> add_fileds plugin support read system environment variables.
> beats can read the service name from system environment variables when user using k8s deploy service node

This is a very typical deployment, and very suitable for documentation and blog.

**Comment by hailin0** [comment]
> @dmsolr @hailin0 Who will lead this? And what is the agenda(time)?

I accept it

**Comment by hailin0** [comment]
### Phase 1：Inject tracing metadata into log
- need update plugins：
  - log4j 1.x
  - log4j 2.x
  - logback

**Comment by wu-sheng** [comment]
@hailin0 This should be a separate issue to track, as this actually is a new feature, not related to the log-receiver.(Even, logically, this makes the log-receiver better)

**Comment by hailin0** [comment]
# demo

### logback pattern
```text
[%tc] [%level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{96}:%line - %msg%n
```

### logback output to file
```text
[TC:N/A] [INFO] 2021-04-11 17:23:33.371 [thread-main] com.example.Main:100 - log message 1
[TC:[service-a,3a5b8da5a5ba40c0b192e91b5c80f1a8@192.168.1.8,N/A,-1,N/A]] [INFO] 2021-04-11 17:23:33.371 [thread-web-1] com.example.controller.TestController:100 - log message 2
[TC:[service-a,3a5b8da5a5ba40c0b192e91b5c80f1a8@192.168.1.8,ddd92f52207c468e9cd03ddd107cd530.69.16181331190470001,0,ddd92f52207c468e9cd03ddd107cd530.69.16181331190470000]] [INFO] 2021-04-11 17:25:19.062 [thread-web-2] com.example.controller.TestController:150 - log message 3
```

### filebeat.yml config
```yml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /tmp/filebeat/filebeat-in.log

processors:
  - dissect:
      tokenizer: '[TC:%{TC}] [%{logTags.level}] %{datetime} [%{logTags.thread}] %{logTags.logger}:%{line} - %{body}'
      field: "message"
      target_prefix: ""
      overwrite_keys: true
  - dissect:
      tokenizer: '[%{service},%{serviceInstance},%{traceContext.traceId},%{traceContext.spanId},%{traceContext.traceSegmentId}]'
      field: "TC"
      target_prefix: ""
  - script:
      lang: javascript
      id: filter_datetime_format
      source: >
        function process(event) {
            var datetime = event.Get("datetime");
            var datetimeArr = datetime.split(" ");
            var dateArr = datetimeArr[0].split("-");
            var timeArrs = datetimeArr[1].split(".");
            var timeArr = timeArrs[0].split(":");
            var mills = timeArrs[1];

            var date = new Date();
            date.setUTCFullYear(parseInt(dateArr[0]));
            date.setUTCMonth(parseInt(dateArr[1]) - 1);
            date.setUTCDate(parseInt(dateArr[2]));
            date.setUTCHours(parseInt(timeArr[0]));
            date.setUTCMinutes(parseInt(timeArr[1]));
            date.setUTCSeconds(parseInt(timeArr[2]));
            date.setUTCMilliseconds(parseInt(mills));

            var timeMillis = date.getTime();
            event.Put("timestamp", timeMillis);
        }
  - copy_fields:
      fields:
        - from: log.file.path
          to: logTags.logfile
        - from: agent.hostname
          to: logTags.hostname
        - from: agent.type
          to: logTags.agent
        - from: agent.version
          to: logTags.agentVersion
        - from: agent.id
          to: logTags.agentId
        - from: agent.name
          to: logTags.agentName
      fail_on_error: false
      ignore_missing: true
  - drop_fields:
      fields: ["@timestamp", "@metadata", "ecs", "host", "input", "agent", "log", "TC", "line", "message", "datetime"]

output.file:
  path: "/tmp/filebeat"
  filename: filebeat-out.log
```


### filebeat output json
```json
{
    "@timestamp":"2021-04-11T15:40:49.025Z",
    "@metadata":{
        "beat":"filebeat",
        "type":"_doc",
        "version":"7.12.0"
    },
    "service":"service-a",
    "serviceInstance":"3a5b8da5a5ba40c0b192e91b5c80f1a8@192.168.1.8",
    "traceContext":{
        "traceId":"ddd92f52207c468e9cd03ddd107cd530.69.16181331190470001",
        "spanId":"0",
        "traceSegmentId":"ddd92f52207c468e9cd03ddd107cd530.69.16181331190470000"
    },
    "logTags":{
        "thread":"thread-web-1",
        "level":"INFO",
        "logger":"com.example.controller.TestController",
        "hostname":"5d960e25ed4c",
        "filepath":"/tmp/filebeat/filebeat-in.log",
        "agent":"filebeat",
        "agentId":"9744570a-0e17-43c8-8958-c5f102ef7eb5",
        "agentName":"5d960e25ed4c",
        "agentVersion":"7.12.0"
    },
    "timestamp":1618161813371,
    "body":"log message 3"
}
```
