### ISSUE TITLE
The problem of pass parameter exception in docker compose startup

### ISSUE THREAD

**Issue by rola0411** [apache/skywalking#6320]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Bug
- Which version of SkyWalking, OS, and JRE?
8.3.0, centos7.7, jdk8
- What happened?
when I used kafka in skywalking，There's a problem

error ： CONSUME_PARTITION="2" docker-compose -f ./oap-server.yml up -d    

success：CONSUME_PARTITION="2,3" docker-compose -f ./oap-server.yml up -d  

supplement：english is poor。I don't know what the problem is， docker or skywalking。

The configuration：
version: '3.8'
services:
  oap:
     environment:
        SW_KAFKA_FETCHER_CONSUME_PARTITIONS: ${CONSUME_PARTITION}

**Comment by wu-sheng** [comment]
Could you share your full configuration? And error stack?

**Comment by rola0411** [comment]
Docker-compose.yml
```yaml
version: '3.8'
services:
  oap:
    image: 10.249.58.10:8081/skywalking/skywalking-oap-server:8.3.0-es7  
    container_name: oap-server-1
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: 10.249.58.4:9200,10.249.58.5:9200,10.249.58.6:9200
      SW_STORAGE_ES_INDEX_SHARDS_NUMBER: 2
      SW_STORAGE_ES_INDEX_REPLICAS_NUMBER: 2
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      SW_KAFKA_FETCHER: default
      SW_KAFKA_FETCHER_SERVERS: 10.249.58.4:9092,10.249.58.5:9092,10.249.58.6:9092
      SW_KAFKA_FETCHER_PARTITIONS: 3
      SW_KAFKA_FETCHER_PARTITIONS_FACTOR: 2
      SW_KAFKA_FETCHER_ENABLE_METER_SYSTEM: "false"
      SW_KAFKA_FETCHER_IS_SHARDING: "false"
      SW_KAFKA_FETCHER_CONSUME_PARTITIONS: ${CONSUME_PARTITION}
      SW_KAFKA_HANDLER_THREAD_POOL_SIZE: -1
      SW_KAFKA_HANDLER_THREAD_POOL_QUEUE_SIZE: -1
      TZ: "Asia/Shanghai"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /usr/share/zoneinfo/Asia:/usr/share/zoneinfo/Asia
```
![error-sw](https://user-images.githubusercontent.com/46880610/106977320-11b82180-6795-11eb-9c86-1dacb715ac86.jpg)
