### ISSUE TITLE
Agent config sync for CDS failed with Consul KVS

### ISSUE THREAD

**Issue by Shikugawa** [apache/skywalking#6369]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

#### version
```8.4.0```

#### OS
```Linux bca492f8751d 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 Linux```

#### JRE
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

- Which company or project?

- What happened?
I found that agent config sync for CDS failed with KVS with this exception.

```
oap_1            | 2021-02-15 12:48:03,755 - org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister -185731 [pool-13-thread-1] ERROR [] - Sync config center error.
oap_1            | java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
oap_1            | 	at org.apache.skywalking.oap.server.recevier.configuration.discovery.AgentConfigurationsReader.<init>(AgentConfigurationsReader.java:45) ~[configuration-discovery-receiver-plugin-8.4.0.jar:8.4.0]
oap_1            | 	at org.apache.skywalking.oap.server.recevier.configuration.discovery.AgentConfigurationsWatcher.notify(AgentConfigurationsWatcher.java:54) ~[configuration-discovery-receiver-plugin-8.4.0.jar:8.4.0]
oap_1            | 	at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.lambda$null$1(ConfigWatcherRegister.java:99) ~[configuration-api-8.4.0.jar:8.4.0]
oap_1            | 	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
oap_1            | 	at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.lambda$configSync$2(ConfigWatcherRegister.java:83) ~[configuration-api-8.4.0.jar:8.4.0]
oap_1            | 	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
oap_1            | 	at org.apache.skywalking.oap.server.configuration.api.ConfigWatcherRegister.configSync(ConfigWatcherRegister.java:82) [configuration-api-8.4.0.jar:8.4.0]
oap_1            | 	at org.apache.skywalking.apm.util.RunnableWithExceptionProtection.run(RunnableWithExceptionProtection.java:33) [apm-util-8.4.0.jar:8.4.0]
oap_1            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
oap_1            | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
oap_1            | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
oap_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
oap_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
oap_1            | 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

To reproduce this exception, we should walk these steps,

1. Setup application.xml like this
```
configuration:
 consul:
    # Consul host and ports, separated by comma, e.g. 1.2.3.4:8500,2.3.4.5:8500
    hostAndPorts: ${SW_CONFIG_CONSUL_HOST_AND_PORTS:consul:8500}
    # Sync period in seconds. Defaults to 60 seconds.
    period: ${SW_CONFIG_CONSUL_PERIOD:1}
    # Consul aclToken
    aclToken: ${SW_CONFIG_CONSUL_ACL_TOKEN:""}

configuration-discovery:
  selector: ${SW_CONFIGURATION_DISCOVERY:default}
  default:
    disableMessageDigest: ${SW_DISABLE_MESSAGE_DIGEST:true}
```

2. Setup agent config. (It is the same as testdata)
```
configurations:
  serviceA:
    trace.sample_rate: 1000
    trace.ignore_path: /api/seller/seller/*
  serviceB:
    trace.sample_rate: 1000
    trace.ignore_path: /api/seller/seller/*
```

3. Send request with this command

```curl --request PUT --data ./config.yaml http://localhost:8500/v1/kv/configuration-discovery.default.agentConfigurations```

4. Make sure config has inserted successfully

```curl http://localhost:8500/v1/kv/configuration-discovery.default.agentConfigurations```
```
[{"LockIndex":0,"Key":"configuration-discovery.default.agentConfigurations","Flags":0,"Value":"Li9jb25maWcueWFtbA==","CreateIndex":156,"ModifyIndex":156}]
```

I'm new to this feature so that I have any misunderstood about usage. Could you take a look and determine this is bug or not?
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
