### ISSUE TITLE
Alarm composite rules not working

### ISSUE THREAD

**Issue by JayeshMuley** [apache/skywalking#6370]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
Have setup the composite rule but alarms are not coming although Time-Bucket is overlapping , Please help if anything wrong in configuration. I am using Skywaling8.3

Configuration  - 
alarm-settings.yml

```yaml
rules:
  service_instance_resp_time_alert_rule:
    metrics-name: service_instance_resp_time
    op: ">"
    threshold: 100
    period: 5
    count: 1
    message: Response time of is more than 100ms in 1 count of last 5 minutes Message1
  service_instance_jvm_cpu__alert_rule:
    metrics-name: instance_jvm_cpu
    op: ">"
    threshold: 20
    period: 5
    count: 1
    message: service_instance_jvm_cpu is more than 20% in 1  times in last 5 minutes  Message2
composite-rules:
  comp_rule:
    expression: service_instance_resp_time_alert_rule && service_instance_jvm_cpu__alert_rule
    message: Message4
    expression: (service_instance_resp_time_alert_rule || service_instance_jvm_cpu__alert_rule)
    message: Message5
    expression: service_instance_resp_time_alert_rule
    message: Message7
    expression: service_instance_jvm_cpu__alert_rule
    message: Message8
    expression: service_instance_jvm_cpu__alert_rule && service_instance_jvm_memory_heap_alert_rule
    message: Message6
```

individual alarm in database - 

CPU Alert 

```text
+---------------+----------------+--------------------------------------------------------------------------+
| start_time    | time_bucket    | substr(alarm_message,10,1000)                                            |
+---------------+----------------+--------------------------------------------------------------------------+
| 1613134640445 | 20210212182720 | nstance_jvm_cpu is more than 20% in 1  times in last 5 minutes   Message2 |
| 1613135000445 | 20210212183320 | nstance_jvm_cpu is more than 20% in 1  times in last 5 minutes   Message2 |
| 1613135360445 | 20210212183920 | nstance_jvm_cpu is more than 20% in 1  times in last 5 minutes   Message2 |
| 1613135720445 | 20210212184520 | nstance_jvm_cpu is more than 20% in 1  times in last 5 minutes   Message2 |
| 1613136620445 | 20210212190020 | nstance_jvm_cpu is more than 20% in 1  times in last 5 minutes   Message2 |
+---------------+----------------+--------------------------------------------------------------------------+

```

Responce Time Alert 

```text
+---------------+----------------+---------------------------------------------------------------------+
| start_time    | time_bucket    | substr(alarm_message,10,1000)                                       |
+---------------+----------------+---------------------------------------------------------------------+
| 1613134460446 | 20210212182420 | time of is more than 100ms in 1 times of last 5 minutes Message1 |
| 1613134820445 | 20210212183020 | time of is more than 100ms in 1 times of last 5 minutes Message1 |
| 1613135540445 | 20210212184220 | time of is more than 100ms in 1 times of last 5 minutes Message1 |
+---------------+----------------+---------------------------------------------------------------------+
3 rows in set (0.05 sec)
```

But no Composite alerts 

Composite Alert for Message4,5,6,7,8 are not detected.

Thanks and Regards,
Jayesh

**Comment by wu-sheng** [comment]
@xbkaishui Anything you can see from the data?

**Comment by kezhenxu94** [comment]
> ```yaml
> composite-rules:
>   comp_rule:
>     expression: service_instance_resp_time_alert_rule && service_instance_jvm_cpu__alert_rule
>     message: Message4
>     expression: (service_instance_resp_time_alert_rule || service_instance_jvm_cpu__alert_rule)
>     message: Message5
>     expression: service_instance_resp_time_alert_rule
>     message: Message7
>     expression: service_instance_jvm_cpu__alert_rule
>     message: Message8
>     expression: service_instance_jvm_cpu__alert_rule && service_instance_jvm_memory_heap_alert_rule
>     message: Message6
> ```

This is not a valid yaml file (b/c you have duplicate keys `expression` and `message` under section `comp_rule`), try this 

```yaml
# ... the other configurations
composite-rules:
  comp1_rule:
    expression: service_instance_resp_time_alert_rule && service_instance_jvm_cpu__alert_rule
    message: Message4
  comp2_rule:
    expression: (service_instance_resp_time_alert_rule || service_instance_jvm_cpu__alert_rule)
    message: Message5
  comp3_rule:
    expression: service_instance_resp_time_alert_rule
    message: Message7
  comp4_rule:
    expression: service_instance_jvm_cpu__alert_rule
    message: Message8
  comp5_rule:
    expression: service_instance_jvm_cpu__alert_rule && service_instance_jvm_memory_heap_alert_rule
    message: Message6
```
