### ISSUE TITLE
We're sorry but SkyWalking doesn't work properly without JavaScript enabled. Please enable it to continue?

### ISSUE THREAD

**Issue by heheliu321** [apache/skywalking#6593]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
That is your env setting or browser.

**Comment by magang0425** [comment]
怎么处理的？

**Comment by tanpenggood** [comment]
Hi bro, I also encountered the same problem, I am using skywalking 9.1.0
I didn't modify the relevant environment variables and configurations.
Accessing skywalking, the browser remains in a white screen state.
After `docker-compose restart` skywalking, normal access was restored.

my docker-compose as follow:
```yaml
version: '3.3'
services:
  skywalking-oap-server:
    image: apache/skywalking-oap-server:9.1.0
    container_name: skywalking-oap-server
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: h2
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms1024m -Xmx1024m -Xmn512m'
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_OC_RULES: vm
      SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES: vm
    networks: 
      - sw
    volumes:
      - ./oap/conf/alarm-settings.yml:/skywalking/config/alarm-settings.yml

  skywalking-ui:
    image: apache/skywalking-ui:9.1.0
    container_name: skywalking-ui
    networks:
      - sw
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap-server:12800
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms256m -Xmx256m'

networks:
  sw:
```
