### ISSUE TITLE
How to config alarm for vm metrics

### ISSUE THREAD

**Issue by yzxin** [apache/skywalking#6710]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
According to the guidance of this article( https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring ), we can obtain the performance metrics of the host in skywalking. We want to monitor and alert these metrics, but I did not succeed. I don't know if it is a configuration problem. I hope to get help. Below is the configuration alarm-settings.yml,the first rule ( service_resp_time_rule) can trigger normally, but the second rule(filesystem_usage_rule) can't:
```
rules:
  # Rule unique name, must be ended with `_rule`.
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1
    period: 10
    count: 1
    silence-period: 5
    message: Response time of service {name} {id} is more than 1000ms in 3 minutes of last 10 minutes.
  filesystem_usage_rule:
    metrics-name: meter_vm_filesystem_percentage
    threshold: 0
    op: ">"
    period: 10
    count: 1
    silence-period: 5
    message: VM {name} {id} filesystem usage more than 0% in 1 minutes of last 10 minutes
#  Active endpoint related metrics alarm will cost more memory than service and service instance metrics alarm.
#  Because the number of endpoint is much more than service and instance.
#
#  endpoint_avg_rule:
#    metrics-name: endpoint_avg
#    op: ">"
#    threshold: 1000
#    period: 10
#    count: 2
#    silence-period: 5
#    message: Response time of endpoint {name} is more than 1000ms in 2 minutes of last 10 minutes

webhooks:
  - http://uat2.mycompany.com:5000/notify/
#  - http://127.0.0.1/go-wechat/
```

___
### Bug
- Which version of SkyWalking, OS, and JRE?

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.
