### ISSUE TITLE
Add LAL in Satellite

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking#6719]
I want to convert log to metrics in Satellite to reuse the alarm plugin in the OAP server.
There are some ideas and problems about the future.

# Ideas
1.the counter which contains some special logs.

# problems
1. Do we need to be as complicated as LAL of the server?

**Comment by wu-sheng** [comment]
Do you have any proposal about how to do log analysis in golang? Any design?

**Comment by EvanLjp** [comment]
I would implement 2 filters, which are log abort filter and log metrics Filter.

**Comment by wu-sheng** [comment]
We should have abort/regex/re-tag/metric or more filters for go-version LAL. @kezhenxu94 Idea or suggestion?

**Comment by EvanLjp** [comment]
Maybe there are 3 new plugins for the feature, which are log_abort_filter plugin, log_meter_filter_plugin, and the log_meter_tag plugin.
# log_abort_filter plugin
```
processor:
      filters:
        - plugin_name: "log-abort-filter"
         aborts:
          - service: demo_service
             service_instance: demo_instance
             endpoint: endpoint1
             abort_tags:
                 - logger: logger1
                 - thread: thread1
```
# log_meter_filter_plugin

```
processor:
      filters:
       - plugin_name: "log-metrics-counter-filter"
          log_metrics_rules_file: log-metrics-counter.file


[
    {
        "metrics_name1_counter":"",
        "filter":[
            {
                "type":"regexp",
                "service":"service1",
                "serviceInstance":"instance1",
                "endpoint":"endpoint1",
                "tags":[
                    {
                        "tagname1":"tagvalue1"
                    }
                ],
                "message":"message1"
            }
        ]
    }
]



# log_meter_tag plugin
[
  {
    "metrics_name1_counter": "",
    "constant_labels": {
      "a": "b"
    },
    "dynamic_labels": [
      "service",
      "serviceInstance",
      "endpoint",
      "tags.xx"
    ]
  }
]

**Comment by wu-sheng** [comment]
Where do the regex matching and splitting happen?

**Comment by kezhenxu94** [comment]
> I would implement 2 filters, which are log abort filter and log metrics Filter.
> So it's simpler than the LAL in the server.

The feature parity between Go version and Java version is not a big concern to me, what I'm concerned is to design the architecture carefully and to make it easily extend when we need to implement all the features in Java version, see my comments 👇.

According to your comment https://github.com/apache/skywalking/issues/6719#issuecomment-817803089 , I'm afraid that the implementation will be very specific to what you need, not in a general manner.

Because there is DSL in the Java version, which makes the LAL in Java looks more "modern", while I didn't find DSL in Go, here is my suggestions.

Because all discussed above are `filter` plugin, I'd suggest defining a general filter and some strategies (that can be defined by users and can be reused) to perform the actions after the filtered logs, here is a possible configuration.


```yaml
filters:
  - regex: ".*DEBUG.*"
    # ... other configurations
    actions:
      - abort
  - regex: ".*failed to order a product.*"
    # ... other configurations
    actions:
      - countErrorMetrics
      - abort
  - regex: ".*failed to order a product.*"
    actions:
      - label1

filterActions:
  - countErrorMetrics:
      name: "errorLogCount"
      type: counter
      # ... other
  - abort: {}
  - label1:
    key: "{{ Log.Key }}"
    val: "constantValue"
  - label2:
    key: "level"
    val: "{{ Log.Level }}"
```
