### ISSUE TITLE
Add alarm conditions

### ISSUE THREAD

**Issue by amwyyyy** [apache/skywalking#6792]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

Is it possible to add such a condition to the alert rule to trigger an alarm after the service or endpoint receives more than the least requests. Because in the low period of business, there may be a few of abnormal requests, resulting in an alarm.

```
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    threshold: 1000
    op: ">"
    period: 10
    count: 1
```
There may be only one request, but an alarm is triggered because the response time of this request exceeds the threshold. We hope that at least 100 requests will trigger the alarm, so as to avoid unexpected alarms.

such as:
```
rules:
  service_resp_time_rule:
    metrics-name: service_resp_time
    threshold: 1000
    op: ">"
    period: 10
    count: 1
    least: 100
```
