### ISSUE TITLE
Make alarm rules work for events

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7024]
Some events can directly and immediately trigger service failure, such as health-check failure, Pod OOM, etc., I think we can have alarm rules work for events as well, WDYT @wu-sheng , for example.

```yaml
  unhealthy_event_rule:
    metrics-name: Unhealthy
    threshold: 2
    op: ">"
    period: 10
    count: 1
```
