### ISSUE TITLE
how to config self observability on k8s cluster

### ISSUE THREAD

**Issue by TerrySolar** [apache/skywalking#7226]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

```yaml
fetcherInterval: PT15S
fetcherTimeout: PT10S
metricsPath: /metrics
staticConfig:

  targets:
    - service1:1234
  labels:
    service: oap-server
```

the self observability config need to assign the targets ip or hostname before the oap server started, but on k8s enviroment we can't get hostname or ip before pod is running, is there some good solutions for this question?

**Comment by kezhenxu94** [comment]
- If you want to see self observability metrics in SkyWalking UI, you need to use a Prometheus and relabel the instances with Kubernetes Pod metadata and labels, and then activate `otel-oc-rules/oap.yaml` to fetch from prometheus into OAP.
- If you want to see self observability metrics in Grafana, set up a Prometheus and Grafana, import our Grafana settings https://github.com/apache/skywalking/blob/a396888de804a8f7090db70e6a2b7879684c4bf0/docs/en/setup/backend/grafana-cluster.json https://github.com/apache/skywalking/blob/a396888de804a8f7090db70e6a2b7879684c4bf0/docs/en/setup/backend/grafana-instance.json

Here is an example of Prometheus config

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus-self'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'oap'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
          action: keep
          regex: true
        - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scheme ]
          action: replace
          target_label: __scheme__
          regex: (.+)
```

You also need to put annotations in your OAP pods:

```yaml
prometheus.io/path: /metrics
prometheus.io/port: "1234"  
prometheus.io/scheme: http  
prometheus.io/scrape: "true"
```
