### ISSUE TITLE
Does Skywalking support istio 1.10?

### ISSUE THREAD

**Issue by zackzhangkai** [apache/skywalking#7241]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does Skywalking support istio1.10?

I want to collect the tracing of request with skywalking. But in istio1.10 the `adapter` crd has been removed.

https://github.com/apache/skywalking-kubernetes/blob/master/chart/skywalking/templates/istio-adapter/adapter.yaml#L17

```
{{- if .Values.oap.istio.adapter.enabled }}
apiVersion: "config.istio.io/v1alpha2"
kind: adapter
metadata:
  name: skywalking-adapter
spec:
  description: "skywaling-adapter"
  session_based: false
  templates:
    - metric
{{- end}}
```
