### ISSUE TITLE
Kafka transport topics are created duplicated with and without namespace

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#7326]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS, and JRE?
 skywalking8.6.0,mac,jdk1.8.0_191

- What happened?
oap creates wrong topic when I write namespace with "yanggy" string value in kafka-fetcher item;

Below is my operation steps;

1. give namespace a string value
```yaml
kafka-fetcher:
  selector: ${SW_KAFKA_FETCHER:default}
  default:
    bootstrapServers: ${SW_KAFKA_FETCHER_SERVERS:localhost:9092}
    namespace: ${SW_NAMESPACE:"yanggy"}
    partitions: ${SW_KAFKA_FETCHER_PARTITIONS:2}
    replicationFactor: ${SW_KAFKA_FETCHER_PARTITIONS_FACTOR:2}
    enableMeterSystem: ${SW_KAFKA_FETCHER_ENABLE_METER_SYSTEM:false}
    enableNativeProtoLog: ${SW_KAFKA_FETCHER_ENABLE_NATIVE_PROTO_LOG:false}
    enableNativeJsonLog: ${SW_KAFKA_FETCHER_ENABLE_NATIVE_JSON_LOG:false}
    isSharding: ${SW_KAFKA_FETCHER_IS_SHARDING:false}
    consumePartitions: ${SW_KAFKA_FETCHER_CONSUME_PARTITIONS:""}
    kafkaHandlerThreadPoolSize: ${SW_KAFKA_HANDLER_THREAD_POOL_SIZE:-1}
    kafkaHandlerThreadPoolQueueSize: ${SW_KAFKA_HANDLER_THREAD_POOL_QUEUE_SIZE:-1}
```
2. start oap server
3. show topics using kafka-manager
  ![](https://github.com/Cool-Coding/photos/blob/master/skywalking/skywalking-1.png?raw=true)

   we can see that oap creates seven redundant topics without "yanggy" prefix and four wrong topics with "yanggy" prefix; because the partitions of  the topic with "yanggy" prefix is wrong; the partition and replica all shoud be 2;

___
#### First let's see how oap creates topics.
```java
// the KafkaFetcherHandlerRegister class  77-115 lines
AdminClient adminClient = AdminClient.create(properties);
        Set<String> missedTopics = adminClient.describeTopics(Lists.newArrayList(
            config.getTopicNameOfManagements(),
            config.getTopicNameOfMetrics(),
            config.getTopicNameOfProfiling(),
            config.getTopicNameOfTracingSegments(),
            config.getTopicNameOfMeters(),
            config.getTopicNameOfLogs(),
            config.getTopicNameOfJsonLogs()
        ))
                                              .values()
                                              .entrySet()
                                              .stream()
                                              .map(entry -> {
                                                  try {
                                                      entry.getValue().get();
                                                      return null;
                                                  } catch (InterruptedException | ExecutionException ignore) {
                                                  }
                                                  return entry.getKey();
                                              })
                                              .filter(Objects::nonNull)
                                              .collect(Collectors.toSet());

        if (!missedTopics.isEmpty()) {
            log.info("Topics" + missedTopics.toString() + " not exist.");
            List<NewTopic> newTopicList = missedTopics.stream()
                                                      .map(topic -> new NewTopic(
                                                          topic,
                                                          config.getPartitions(),
                                                          (short) config.getReplicationFactor()
                                                      )).collect(Collectors.toList());

            try {
                adminClient.createTopics(newTopicList).all().get();
            } catch (Exception e) {
                throw new ModuleStartException("Failed to create Kafka Topics" + missedTopics + ".", e);
            }
        }
```

oap just gets topics without using namespace !

#### Second let's see why there are four topics having "yanggy" prefix

```
  // the KafkaFetcherHandlerRegister class
   public void start() {
        handlerMap = builder.build();
        if (isSharding) {
            consumer.assign(topicPartitions);
        } else {
            consumer.subscribe(handlerMap.keySet());
        }
        consumer.seekToEnd(consumer.assignment());
        executor.submit(this);
    }
```
 When the start method run, consume will subscribe some topics; if the topic doesn't exist, it will create with one partition and one replica;

___
###  Requirement or improvement
If the bug is true, I will  move the logic of creating topic in oap from prepare phase to start phase. after doing this,  there are two benefits. one is the logic of getting kafka topic name when creating and subscribe kafka topic at oap side is unified. another is the logic of creating topic at oap side and sending metric data to topic at agent is consistent.  oap wouldn't create redundant  topics such as "logs" topic.

```java
public void start() throws ModuleStartException {
        handlerMap = builder.build();

        createTopicIfNeeded(handlerMap.keySet(), properties);

        if (isSharding) {
            consumer.assign(topicPartitions);
        } else {
            consumer.subscribe(handlerMap.keySet());
        }
        consumer.seekToEnd(consumer.assignment());
        executor.submit(this);
    }

  private void createTopicIfNeeded(Collection<String> topics, Properties properties) throws ModuleStartException {
        AdminClient adminClient = AdminClient.create(properties);
        Set<String> missedTopics = adminClient.describeTopics(topics)
                                              .values()
                                              .entrySet()
                                              .stream()
                                              .map(entry -> {
                                                  try {
                                                      entry.getValue().get();
                                                      return null;
                                                  } catch (InterruptedException | ExecutionException ignore) {
                                                  }
                                                  return entry.getKey();
                                              })
                                              .filter(Objects::nonNull)
                                              .collect(Collectors.toSet());

        if (!missedTopics.isEmpty()) {
            log.info("Topics" + missedTopics.toString() + " not exist.");
            List<NewTopic> newTopicList = missedTopics.stream()
                                                      .map(topic -> new NewTopic(
                                                          topic,
                                                          config.getPartitions(),
                                                          (short) config.getReplicationFactor()
                                                      )).collect(Collectors.toList());

            try {
                adminClient.createTopics(newTopicList).all().get();
            } catch (Exception e) {
                throw new ModuleStartException("Failed to create Kafka Topics" + missedTopics + ".", e);
            }
        }
    }
```
