### ISSUE TITLE
Does skywalking-eyes support SPDX-short-identifiers?

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7757]
### Discussed in https://github.com/apache/skywalking/discussions/7756

<div type='discussions-op-text'>

<sup>Originally posted by **tisonkun** September 20, 2021</sup>
https://spdx.github.io/spdx-spec/appendix-V-using-SPDX-short-identifiers-in-source-files/

It seems the checker only allows full-text license header.

cc @kezhenxu94 @fgksgf </div>

**Comment by tisonkun** [comment]
@kezhenxu94 possibly we can just achieve this with:

```yml
header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-License-Identifier: Apache-2.0
```

thanks to SPDX license identifier is simple :)
