### ISSUE TITLE
[INFRA E2E][Feature] allow reusing the `verify.cases`

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#7896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

This feature allows people to reuse the `verify.cases` that can be shared between many similar cases.

## Reuse `verify.cases`

We can add a configuration item `include` under `verify.cases`, people can extract the common `verify.case` snippets into a separate file and reuse them via `include`.

```yaml
# setup:
# trigger:
verify:
  retry:
    count: 200
    interval: 5s
  cases:
    - include: simple-case.yaml
```

```yaml
# simple-case.yaml
cases:
  - query: swctl svc ls
    expected: expected/services.yaml
  # .....
```

### Use case

We have many cases that share the same verifications and setup scripts. For example, the `auth`, `jdk`, `mtls` and `ssl` in main repo share the same verification cases but we need to duplicate the codes. https://github.com/apache/skywalking-java/pull/42#issuecomment-932974220 is a similar feature request to share the code snippets, I think if we share the `verify.cases`, others like `setup`, `trigger` can be tolerable because they are short enough. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
