### ISSUE TITLE
[Feature] [E2E-INFRA] Request to make kind file configuration expandable with system environment

### ISSUE THREAD

**Issue by JohnNiang** [apache/skywalking#8100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Request to make kind file configuration expandable with system environment.

### Use case

E2E configuration sample:

```yaml
setup:
  env: kind
  file: common/kind-$K8S_VERSION.yaml
```

And there are several kind configurations in common folder:

```bash
common
├── kind-1.19.yaml
├── kind-1.20.yaml
├── kind-1.21.yaml
└── kind-1.22.yaml
```

Then, we could create a matrix E2E testing in GitHub Action, such as:

```yaml
jobs:
  Install:
    name: XYZ
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        k8sVersion: ["1.19", "1.20", "1.21", "1.22"]
    steps:
      - uses: actions/checkout@v2
      - 
      - name: Run E2E Test
        uses: apache/skywalking-infra-e2e@feat/expand-env-for-kind-config-path
        env:
          K8S_VERSION: ${{ matrix.k8sVersion }}
        with:
          e2e-file: $GITHUB_WORKSPACE/test/e2e/cases/xyz/e2e.yaml
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
