### ISSUE TITLE
[Feature]  add annotations for oap.service (skywalking-kubernetes )

### ISSUE THREAD

**Issue by lihuixian001** [apache/skywalking#8469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

add annotations for oap.service  just like ui.service.annotations 

### Use case

When opa.service.type is set to loadBalancer, you need to customize the loadBalancer by setting annotations, just like ui.service.annotations. It's a bit strange why didn't add annotations support?

```
oap:
  name: oap
  image:
    tag: 8.9.1
  storageType: elasticsearch
  replicas: 2
  service:
    type: loadBalancer
    annotations:
      service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-bp16j1jvwlwxxxxxxx"  
      service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"  
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
