### ISSUE TITLE
[INFRA] license-eye support pre-commit hook

### ISSUE THREAD

**Issue by kwanhur** [apache/skywalking#8710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

After finish coding, always need to do license check on new files before push. So hope it can be done when commit.

Add one hook in [pre-commit](https://pre-commit.com/#new-hooks) could be a solution.

### Use case

place `license-eye` hook in `.pre-commit-config.yaml`, like

```yaml
- repo: https://github.com/apache/skywalking-eyes
  rev: v0.2.0
  hooks:
    - id: license-eye-header-check
    - id: license-eye-header-fix
```

precommit install-hooks then every new file will be checked and fixed before commit.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
@kwanhur how will you implement this feature?

**Comment by kwanhur** [comment]
Add `.pre-commit-hooks.yaml` into repo `skywalking-eyes`, its content like:

```yaml
-   id: license-eye-header-check
    name: license-eye-header-check
    description: "Checks the files' license header"
    entry: license-eye header check
    language: golang
-   id: license-eye-header-fix
    name: license-eye-header-fix
    description: "Fixes the files' license header"
    entry: license-eye header fix
    language: golang
```

Similar configs for `license dependency`.

**Comment by kezhenxu94** [comment]
That's not what I expect, skywalking-eyes itself is a tool, we can add `.pre-commit-hooks.yaml` in this repo, but I expect this is something our users can also use in their repos, for example, adding a command to automatically generate these files in users repo, e.g. `license-eye hook init`

**Comment by kwanhur** [comment]
If on this way, [local hooks](https://pre-commit.com/#repository-local-hooks) maybe the choice, but it'll loss autoupdate feature.

**Comment by kezhenxu94** [comment]
In my opinion there is no way to have the autoupdate feature (or non-local hooks), license-eye finally will be shipped as a executable binary, how could that `.pre-commit-hooks.yaml` take effect?

**Comment by kwanhur** [comment]
According to local `.pre-commit-config.yaml`, `pre-commit` installs the binary with specified repo and revision, and then local hooks work on repo's `.pre-commit-hooks.yaml` base on hook id.

So the `id` in `.pre-commit-hooks.yaml` is important, every hook takes effect through its `entry`. `entry` means how to work on those matched files.

**Comment by kwanhur** [comment]
I place `license-eye` hooks as the below, it works well.

```yaml
- repo: local
  hooks:
    - id: license-header-check
      name: license header check
      entry: license-eye header check
      language: system
      types: [file]
    - id: license-header-fix
      name: license header fix
      entry: license-eye header fix
      language: system
      types: [file]
```
