### ISSUE TITLE
[Bug] apm-spring-cloud-gateway-plugin, trace log loss when the request time out.

### ISSUE THREAD

**Issue by wuwen5** [apache/skywalking#9061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Java Agent (apache/skywalking-java)

### What happened

The gateway trace log was lost when the request timed out

![04C449E8-D524-40E0-90EE-50343180B477](https://user-images.githubusercontent.com/5037807/168287378-c3d8249c-9f2a-4381-9c78-d2d266231926.png)

### What you expected to happen

expected
![4A5A6623-BF95-4957-B48E-0FA8B178AFC7](https://user-images.githubusercontent.com/5037807/168288602-ea18e85a-49f2-4273-9060-fc587b9ef062.png)

### How to reproduce

```
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
      routes:
      - id: provider_route
        uri: http://1.2.3.4:18070
        predicates:
        - Path=/provider/timeout/*
````

```curl 'http://localhost:8080/provider/timeout/testcase'```
        

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
