### ISSUE TITLE
[Feature] Add metric for analyzing  cache-related  span like Virtual Database

### ISSUE THREAD

**Issue by pg-yang** [apache/skywalking#9556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Virtual  Cache will analysis  span  which  is  cache-related . It will generate SLA, response time or some else metric
In a word  , it's   similar to Virtual Database
Reference [virtual-database](https://skywalking.apache.org/docs/main/latest/en/setup/service-agent/virtual-database/)  [skywalking demo ](http://demo.skywalking.apache.org/dashboard/VIRTUAL_DATABASE/Service/bG9jYWxob3N0Oi0x.0/Virtual-Database-Service)

Works should  to  be  done :

#### Agent (focus on Java agent) 
- [x]   Update  cache plugins for  uniform `Span’s layer ` , `tag `  if  necessary .  
    The known cache-related plugin(need suggestion : which plugin is cache-related):
    1. jedis-plugins
    2. redisson-plugin
    3. xmemcached-plugin
    4. zookeeper-plugin
    5. spymemcached-plugin

#### Backend 
- [x]  develop  Virtual  Cache metric
    1. Add  RequestType : Cache 
    1. ServiceMeta for registering  cache  service 
    9.  Cache-source for OAL
    10. Slow query Top N metric 
- [x]  Update [core oal ]( https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/oal/core.oal) for metric (reponse time  or  some  else )
- [x] Update  Doc  for  Virtual  Cache 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pg-yang** [comment]
Maybe , we should expand  the meaning  of  `Database ` . `Virtual Database`  should  contains  cache  instead of creating `Virtual Cache`

**Comment by wu-sheng** [comment]
I think they are different, basically. Cache is much faster than database.

**Comment by pg-yang** [comment]
They  are used for saving  data , and contain statement  too .
We provide slow threshold config for various DB
```
agent-analyzer:
  selector: ${SW_AGENT_ANALYZER:default}
  default:
    slowDBAccessThreshold: ${SW_SLOW_DB_THRESHOLD:default:200,mongodb:100,redis:20} 
```
We just add `redis:20`

**Comment by pg-yang** [comment]
And we could append `dbType` to serviceName like `Mysql:192.168.1.1:3306` or `Redis:192.168.1.1:6379`

**Comment by wu-sheng** [comment]
Yes, I don't think this is tech issue. I just talked from design perspective.

**Comment by pg-yang** [comment]
> design perspective

It depends how you define Database  . Design comes from Definition .

**Comment by wu-sheng** [comment]
Let's say in this way, cache should be related to more metrics, such as cache hint is an important metric, database doesn't care about hint rate.

**Comment by pg-yang** [comment]
Hint ? means cache hit ?
Data store system can response  a result ,   whether the result is empty or not .From  client-server communication protocol perspective , they are all successful  .
If we want to get  hit rate , we should decode response , It's better if  the response have hit-state  .  However, we cannot guarantee that every cache system protocol has `hit-state ` 
Finally , `Hit` also  is appropriate  for Database (such as Mysql) .

**Comment by wu-sheng** [comment]
buYou just described it from a general side, I mean for layer, and for apm, we should understand the service. 
In every official architecture, cache service and database service are two things. This is why we have cache and service span type from many years ago.
You should not say they arevsame just because they have similar metric.

**Comment by pg-yang** [comment]
OK , I 'll  follow  current rule . For  a system  the  concept should  be  consistent at  least

**Comment by wu-sheng** [comment]
And another thing is, that some caches are not remote services. The cache could be local memory.

**Comment by pg-yang** [comment]
Should we analysis  local span for  local memory  cache  such  as  guava-cache

**Comment by wu-sheng** [comment]
Yes, we should, and we should provide a format rule to difference local and remote caches.

**Comment by pg-yang** [comment]
The  new config  look like  this :

```yml 
agent-analyzer:
     #......
    virtualService:
      database:
        slowAccessThreshold: ${SW_VIRTUAL_DB_SLOW_THRESHOLD:default:200,mongodb:100}
        maxSlowStatementLength: ${SW_VIRTUAL_DB_SLOW_MAX_LENGTH:default:200,mongodb:100}
      cache:
        slowAccessThreshold: ${SW_VIRTUAL_CACHE_SLOW_THRESHOLD:default:80,redis:30}
        maxSlowStatementLength: ${SW_VIRTUAL_CACHE_SLOW_MAX_LENGTH:default:200,redis:100}
        enableLocal: false # This  term  define  whether  analysis  local cache such  as  Guave-Cache ,Ecache 

```
Do  you have any  suggestion?

**Comment by wu-sheng** [comment]
Does the kernal support this kind of structure? I remember only 3 levels supported.

**Comment by pg-yang** [comment]
Yes  , only  3 levels  supported  , I'll reorganize  this  config ,

**Comment by pg-yang** [comment]
```yaml 
agent-analyzer:
  selector: ${SW_AGENT_ANALYZER:default}
  default:
    # .....
    databaseSlowAccessThreshold: ${SW_VIRTUAL_DB_SLOW_THRESHOLD:default:200,mongodb:100}
    databaseMaxSlowStatementLength: ${SW_VIRTUAL_DB_SLOW_MAX_LENGTH:default:200,mongodb:100}
    cacheSlowAccessThreshold: ${SW_VIRTUAL_CACHE_SLOW_THRESHOLD:default:80,redis:30}
    cacheMaxSlowStatementLength: ${SW_VIRTUAL_CACHE_SLOW_MAX_LENGTH:default:200,redis:100}
    analysisLocalCache: false # This  term  define  whether  analysis  local cache such  as  Guave-Cache ,Ecache
```
BTW , I want to  modify the kernel  for  supporting more  levels in future

**Comment by wu-sheng** [comment]
> BTW , I want to modify the kernel for supporting more levels in future

The reason we don't recommend more levels is that, nested YAML file is very hard to be controlled through system env variables, which are the key parts of how helm/operator(cloud-native) components control the OAP behaviors in the setup stage.

**Comment by wu-sheng** [comment]
> cacheMaxSlowStatementLength: ${SW_VIRTUAL_CACHE_SLOW_MAX_LENGTH:default:200,redis:100}

Is this necessary? What kinds of statements we could get? Could you provide an example? Such as in Redis case, if this statement doesn't include `key`, then mostly, it is pointless.

And for cache, `put` usually is much slower than `read`. Threshold should be separated for read/write or general operation.

**Comment by pg-yang** [comment]
> if this statement doesn't include `key`

Yes, sometimes  we  couldn't  get  the key  from  cache  plugin   , we could  show slow  command in  UI  at  least . It's better  than  noting . 
jedis-4.x -plugin :
```
- {key: db.statement, value: HSET a}
- {key: db.statement, value: SET key}
- {key: db.statement, value: XADD abc}
- {key: db.statement, value: XREAD}    # only command , no key !!
```

> Threshold should be separated for read/write or general operation.

Agree

**Comment by wu-sheng** [comment]
OK, then the value of these metrics would be lower than we could be.

**Comment by pg-yang** [comment]
Now , we could distinguish  write/read operation .  But we  could't guarantee every span contains `cache.key` and `cache.op`.
The  next  question is  which span should be analyzed ? 
I  think : 
When the span contains  `op ` , we  generate  response time , cpm ,sla ,  etc for write/read operation  respectively 
When the span contains `key` , we  generate TopN , we could't  generate Write-TopN ,Read-TopN , as the `op ` maybe not exist . If  we  want Write-TopN ,Read-TopN , we should analysis the complete span (which contains  op and key ),because it's meaningful that show  the slow keys

**Comment by wu-sheng** [comment]
Slow read and write are meaningful. We should use op and key as the samplrd statement.

We could only analysis this when relative tags existing

**Comment by pg-yang** [comment]
make sense  to me

**Comment by pg-yang** [comment]
I don't know  how to  test with  UI  , there  is any doc ?

**Comment by wu-sheng** [comment]
Do you have virtual cache layer in the backend? Once you added, you could use customer dashboard to set up dashboards for the new layer.

Docs are here. https://skywalking.apache.org/docs/main/next/en/ui/readme/

Also this PR is a good place to learn for new dashboard setup steps, https://github.com/apache/skywalking/pull/9432

**Comment by pg-yang** [comment]
I  have already created following json config  in backend 
* ui-initialized-templates/virtual_cache/virtual-cache-root.json
* ui-initialized-templates/virtual_cache/virtual-cache-service.json

In  UI  
added to `general.ts`: 

```  javascript
      {
        path: "/cache",
        name: "VirtualCache",
        meta: {
          title: "VirtualCache",
          exact: true,
        },
        component: () =>
          import(/* webpackChunkName: "layer" */ "@/views/Layer.vue"),
      },
      {
        path: "/cache/tab/:activeTabIndex",
        name: "VirtualCacheActiveTabIndex",
        meta: {
          notShow: true,
        },
        component: () =>
          import(/* webpackChunkName: "layer" */ "@/views/Layer.vue"),
      }
```
added to `data.ts`
``` javascript
export const RoutesMap: { [key: string]: string } = {
  VirtualCache: "VIRTUAL_CACHE",
  VirtualCacheActiveTabIndex: "VIRTUAL_CACHE"
}
```

But `Please  set  a root dashboard for  VIRTUAL_CACHE` when I visit page

**Comment by pg-yang** [comment]
![image](https://user-images.githubusercontent.com/3917424/189524721-71e6f67c-aee8-4394-aa83-ad466687e547.png)

**Comment by wu-sheng** [comment]
The dashboard of `virtual-cache-root` should be set as root at the dashboard management page. I am not sure how you wrote these JSONs, generally, they are exported from the dashboard management page too.

**Comment by pg-yang** [comment]
Because browser cache. It work now. 

![image](https://user-images.githubusercontent.com/3917424/189573558-17c08709-c6e5-4f33-85ae-24b18e1f97fb.png)

**Comment by wu-sheng** [comment]
Do you set the key as a or key on purpose? After we have this in the  codebase, we need to update showcase. So, we need to set keys in the demo services clearly, as well as e2e

**Comment by wu-sheng** [comment]
Is read/write success related to error status only?

**Comment by pg-yang** [comment]
> Is read/write success related to error status only?

Yes
```
cache_write_sla = from(VirtualCacheWrite.*).percent(status == true);
cache_read_sla = from(VirtualCacheRead.*).percent(status == true);
```

> Do you set the key as a or key on purpose? After we have this in the codebase, we need to update showcase. So, we need to set keys in the demo services clearly, as well as e2e

The [showcase](http://demo.skywalking.apache.org/) is crash now ,  I would provide clearly test data after writing unit test .

**Comment by wu-sheng** [comment]
Showcase could run locally on KinD and DockerCompose. demo is just another host.

**Comment by wu-sheng** [comment]
Showcase could run locally on KinD and DockerCompose. demo is just another host.

**Comment by pg-yang** [comment]
Showcase means [skywalking-showcase]( https://github.com/apache/skywalking-showcase) repo? 
And should I provide e2e-test? I have consulted some e2e-test in OAP . I think my e2e-test should integrate with agent  , but I could't found similar test .May I misunderstand the e2e in OAP

**Comment by wu-sheng** [comment]
e2e has cases with agents. What do you mean?

**Comment by wu-sheng** [comment]
Showcase could be done after e2e. Because e2e is checking features, because we are confident to merge.
Yes, showcase is the repo.

**Comment by pg-yang** [comment]
> e2e has cases with agents. What do you mean?

I'm  confused that  if e2e has java-agent case ,I  should could search some file by keyword `-javaagent`  . 
Now, I think I have  found the correct entrance about e2e . 
1. The env `JAVA_TOOL_OPTIONS` is set to docker image `ghcr.io/apache/skywalking-java/skywalking-java`
2. I should update `e2e-service-consumer` , `e2e-service-provider` to add redis test code 
3. Then create  `e2e.yaml` (maybe need to extend `base-compose.yml`)  to trigger,verify my data 
 
 Right ?

**Comment by wu-sheng** [comment]
You may not need to change <3>, instead, you should adjust metrics verification and service list in existing e2e. Once <2> is done, the analysis would be done automatically.

**Comment by wu-sheng** [comment]
You could use an in-memory cache, if a redis service is why you thought you should change `base-compose.yml`

**Comment by pg-yang** [comment]
```shell
➜  skywalking git:(feature/vitrual-cache) ✗  /Users/HOME/GolandProjects/skywalking-infra-e2e/bin/darwin/e2e run -c test/e2e-v2/cases/meter/e2e.yaml
INFO load the e2e config successfully
Pulling oap (skywalking/oap:latest)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]pull access denied for skywalking/oap, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR Local Docker compose exited abnormally whilst running docker-compose: [--env-file /Users/HOME/ideaProjects/skywalking/test/e2e-v2/script/env up -d]. exit status 1
```

I couldn't  found `skywalking/oap` in docker hub .  I don't understand  where  the image docker would download .

**Comment by wu-sheng** [comment]
It is not on docker hub, they are here, https://github.com/orgs/apache/packages?repo_name=skywalking

**Comment by pg-yang** [comment]
It looks like download image  from docker hub . I just execute above shell . Maybe  I  loss some  step

**Comment by wu-sheng** [comment]
Latest is your local build based on the latest code.

**Comment by pg-yang** [comment]
> You could use an in-memory cache, if a redis service is why you thought you should change `base-compose.yml`

in-memory cache (e.g. guava-cache, ehcache) plugin is optional . I would add redis docker image to `base-compose.yml`.
It's OK ?

**Comment by pg-yang** [comment]
It's better that  updating   `docker-compose.yml` in e2e-test case  rather than `base-compose.yml`

**Comment by wu-sheng** [comment]
Please don't do that. e2e only has 3U8G for the whole env, another server(redis) would impact the stability.

An optional plugin is able to activate. Is there any issue to do so? Showcase also includes optional plugin activation, such as Spring Gateway.

**Comment by pg-yang** [comment]
OK, I would study how to activate optional plugin  in e2e

**Comment by pg-yang** [comment]
I wrote TopNCacheReadCommand.java  like `TopNDatabaseStatement` , It extend `TopN ` too  
BTW `TopN extend Record`. 

https://github.com/apache/skywalking/blob/96faed0185aceefdc30fcd2fb2d9291ff2959ca2/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/analysis/manual/database/TopNDatabaseStatement.java#L37

I use this  command  to  get  topN record 

```shell
swctl --display yaml --base-url=http://127.0.0.1:12800/graphql metrics top   --start=-60m --name=top_n_cache_read_command  --service-id=R3VhdmFDYWNoZS1sb2NhbA==.0
```
`top_n_cache_read_command` is index(table)name , defined in `TopNCacheReadCommand`
And OAP cause exception 

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ENTITY_ID" not found; SQL statement:
select * from (select avg(latency) result,entity_id from top_n_cache_read_command where time_bucket >= ? and time_bucket <= ? and service_id=? group by entity_id)  as T order by result desc limit 5 [42122-212]
```

I have confirm TopN class  don't  define `ENTITY_ID` , But Metrics class defined  . I could'n find other example about TopN metrics .
So , I'm not  sure  the error is caused by swctl command  or my code

The  complete error stack in OAP 
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ENTITY_ID" not found; SQL statement:
select * from (select avg(latency) result,entity_id from top_n_cache_read_command where time_bucket >= ? and time_bucket <= ? and service_id=? group by entity_id)  as T order by result desc limit 5 [42122-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:244) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.expression.ExpressionColumn.optimizeOther(ExpressionColumn.java:226) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:213) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.query.Select.prepareExpressions(Select.java:1170) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.table.DerivedTable.<init>(DerivedTable.java:41) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.query.Query.toTable(Query.java:1004) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.readDerivedTableWithCorrelation(Parser.java:1936) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.readTablePrimary(Parser.java:1816) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.readTableReference(Parser.java:2359) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2810) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseSelect(Parser.java:2917) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQueryPrimary(Parser.java:2800) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQueryTerm(Parser.java:2667) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQueryExpressionBody(Parser.java:2646) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQueryExpressionBodyAndEndOfQuery(Parser.java:2639) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQueryExpression(Parser.java:2632) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parseQuery(Parser.java:2593) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parsePrepared(Parser.java:724) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parse(Parser.java:691) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.parse(Parser.java:661) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.command.Parser.prepareCommand(Parser.java:568) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92) ~[h2-2.1.212.jar:2.1.212]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288) ~[h2-2.1.212.jar:2.1.212]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318) ~[HikariCP-3.1.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-3.1.0.jar:?]
	at org.apache.skywalking.oap.server.library.client.jdbc.hikaricp.JDBCHikariCPClient.executeQuery(JDBCHikariCPClient.java:119) ~[classes/:?]
	at org.apache.skywalking.oap.server.storage.plugin.jdbc.h2.dao.H2AggregationQueryDAO.sortMetrics(H2AggregationQueryDAO.java:70) ~[classes/:?]
	at org.apache.skywalking.oap.server.core.query.AggregationQueryService.sortMetrics(AggregationQueryService.java:63) ~[classes/:?]
	at org.apache.skywalking.oap.query.graphql.resolver.MetricsQuery.sortMetrics(MetricsQuery.java:151) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_321]
	at graphql.kickstart.tools.resolver.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:280) ~[graphql-java-tools-12.0.2.jar:?]
```
The http info

```
.b...B&.POST /graphql HTTP/1.1
Host: 127.0.0.1:12800
User-Agent: Go-http-client/1.1
Content-Length: 1241
Accept: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip

{"query":"# Licensed to Apache Software Foundation (ASF) under one or more contributor\n# license agreements. See the NOTICE file distributed with\n# this work for additional information regarding copyright\n# ownership. Apache Software Foundation (ASF) licenses this file to you under\n# the Apache License, Version 2.0 (the \"License\"); you may\n# not use this file except in compliance with the License.\n# You may obtain a copy of the License at\n#\n#     http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing,\n# software distributed under the License is distributed on an\n# \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n# KIND, either express or implied.  See the License for the\n# specific language governing permissions and limitations\n# under the License.\n\nquery ($condition:TopNCondition!, $duration: Duration!) {\n    result: sortMetrics(condition: $condition, duration: $duration) {\n        name\n        value\n    }\n}\n","variables":{"condition":{"name":"top_n_cache_read_command","parentService":"GuavaCache-local","normal":false,"scope":"Service","topN":5,"order":"DES"},"duration":{"start":"2022-09-13 1853","end":"2022-09-13 1923","step":"MINUTE"}}}

19:53:18.719900 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    localhost.12800 > localhost.51771: Flags [.], cksum 0xfe28 (incorrect -> 0xe9c6), seq 221, ack 2608, win 6338, options [nop,nop,TS val 2269259431 ecr 3479306895], length 0
E..4..@.@...........2..;.u....XH.....(.....
.B&..b..
19:53:18.738493 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 200, bad cksum 0 (->3c2e)!)
    localhost.12800 > localhost.51771: Flags [P.], cksum 0xfebc (incorrect -> 0xe882), seq 221:369, ack 2608, win 6338, options [nop,nop,TS val 2269259450 ecr 3479306895], length 148
E.....@.@...........2..;.u....XH...........
.B&..b..HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 196
server: Armeria/1.18.0
date: Tue, 13 Sep 2022 11:53:18 GMT
```

**Comment by pg-yang** [comment]
UI  invoke `readSampledRecords` method in  OAP . it's different with `swctl `

**Comment by wu-sheng** [comment]
Have you checked the UI about what the slow SQL statement actually requests? 

There are several concepts you missed.
1. `TopN` is not a metric type, it is a record.
2. [Sorted metrics](https://github.com/apache/skywalking-query-protocol/blob/2c541beae657306127f07af127d179492a1d7cf9/metrics-v2.graphqls#L150), which you are using, is not [sampled record](https://github.com/apache/skywalking-query-protocol/blob/2c541beae657306127f07af127d179492a1d7cf9/metrics-v2.graphqls#L158). The latter is what you should use.
3. Slow statement is nearly impossible to test in the e2e cases. Take a look at `TopNWorker` mechanism, it is reported perioedly, which is controlled through `SW_CORE_TOPN_REPORT_PERIOD`.(10min default) You most likely face timeout if you want to test this in the e2e actually. We prefer you do manually testing locally.

**Comment by pg-yang** [comment]
Got it  .  my shell  is incorrect  . I  misunderstood the subcommand `top `
```
swctl --display yaml --base-url=http://127.0.0.1:12800/graphql metrics -h

  top                                 query the top <n> entities sorted by the specified metrics

```

This  top  don't  mean  `TopN record `.  emmm

**Comment by pg-yang** [comment]
If  set `SW_CORE_TOPN_REPORT_PERIOD `  small enough , Doesn't  e2e work correctly  ?

**Comment by pg-yang** [comment]
Actually , I  modified the code  about  `SW_CORE_TOPN_REPORT_PERIOD ` on  my  PC  , for  test  TopN .

**Comment by wu-sheng** [comment]
> If set `SW_CORE_TOPN_REPORT_PERIOD ` small enough , Doesn't e2e work correctly ?

It could be, just be careful about the settings, if you generate too many traffics, and this period is too small, the storage could be overload easily.

**Comment by pg-yang** [comment]
I have finished the most work of this issue , I  think . 

Are  you  ready for `virtual-cache ` doc ? 

https://github.com/apache/skywalking-java/pull/303#issuecomment-1240112282

**Comment by wu-sheng** [comment]
> Did you prepare virtual-cache doc ?
https://github.com/apache/skywalking-java/pull/303#issuecomment-1240112282

What do you mean `I prepare`? Do you want to me to write that up?

**Comment by wu-sheng** [comment]
>Sorry , I thought you want prepare it .

If you face any trouble to write one, I would help. If not, I think it should be good to be written by you. After all, this is your PR :)

**Comment by pg-yang** [comment]
> 

No trouble , I misunderstood your mean  .  Haha  .

**Comment by wu-sheng** [comment]
BTW, I think CLI doesn't support querying the sampled record. You and @yswdqz (Slow SQL - MySQL server statistic https://github.com/apache/skywalking/pull/9575) noticed this issue today.

@yswdqz told me he may want to try this, but he is not familiar with golang much. How about your golang skill? @pg-yang

**Comment by pg-yang** [comment]
not familiar with golang  either .
I  read https://github.com/apache/skywalking-infra-e2e simply .  The code is not a lot 。

**Comment by wu-sheng** [comment]
> not familiar with golang either . I read https://github.com/apache/skywalking-infra-e2e simply . The code is not a lot. I debugged this project for my test case today .

swctl is actually from https://github.com/apache/skywalking-cli. infra-e2e is just a scheduler to push the tests forward step by step. SkyWalking has a lot of sub-projects, sorry.

**Comment by wu-sheng** [comment]
@mrproliu @kezhenxu94 If you have time to help on the CLI part, it would be easier.

**Comment by pg-yang** [comment]
> SkyWalking has a lot of sub-projects

I realized it .


e2e for  trigger , verify ,etc 
skywalking-cli  for  interaction with OAP .

I  would like support this feature , but  i'm golang newer too .  It may take some time to  familiarize these projects

**Comment by mrproliu** [comment]
> 

Sure, I can handle it. I will add `metrics sorted` and `metrics sampled-record` commands to split the queries.

**Comment by wu-sheng** [comment]
@pg-yang @yswdqz https://github.com/apache/skywalking-cli/pull/163 This has been done. You could update the commit ID of the swctl.

**Comment by pg-yang** [comment]
Ask for  help  . my  e2e test  case  failure  .

error  message 
```
 WARNING  failed to verify case[swctl --display yaml --base-url=http://${oap_host}:${oap_12800}/graphql metrics sampled-record  --name=top_n_cache_read_command    --service-id=R3VhdmFDYWNoZS1sb2NhbA==.0 |  yq e 'to_entries | with(.[] ; .value=(.value | to_entries))' -
          ], retried 30 time(s):
 DETAILS  failed to verify the output: swctl --display yaml --base-url=http://${oap_host}:${oap_12800}/graphql metrics sampled-record  --name=top_n_cache_read_command    --service-id=R3VhdmFDYWNoZS1sb2NhbA==.0 |  yq e 'to_entries | with(.[] ; .value=(.value | to_entries))' -
          , error:
          failed to execute template: template: test:21:23: executing "test" at <.value>: wrong type for value; expected string; got interface {}

 SUMMARY  10 passed
          1 failed
          8 skipped
```

actual  data 

```
- key: 0
  value:
    - key: name
      value: getIfPresent user_1
    - key: id
      value: ""
    - key: value
      value: "5"
    - key: refid
      value: null
- key: 1
  value:
    - key: name
      value: getIfPresent user_1
    - key: id
      value: ""
    - key: value
      value: "1"
    - key: refid
      value: null
- key: 2
  value:
    - key: name
      value: getIfPresent user_1
    - key: id
      value: ""
    - key: value
      value: "1"
    - key: refid
      value: null
- key: 3
  value:
    - key: name
      value: getIfPresent user_1
    - key: id
      value: ""
    - key: value
      value: "1"
    - key: refid
      value: null
- key: 4
  value:
    - key: name
      value: getIfPresent user_1
    - key: id
      value: ""
    - key: value
      value: "0"
    - key: refid
      value: null
```

expect data :

```yaml
{{- contains . }}
- key: 0
  value:
  {{- contains .value }}
  - key: name
    value: {{ notEmpty .value}}
  - key: id
    value:
  - key: value
    value: {{ notEmpty .value}}
  - key: refid
    value: null
  {{- end }}
- key: 1
  value:
  {{- contains .value }}
  - key: name
    value: {{ notEmpty .value}}
  - key: id
    value:
  - key: value
    value: {{ notEmpty .value}}
  - key: refid
    value: null
  {{- end }}
- key: 2
  value:
  {{- contains .value }}
  - key: name
    value: {{ notEmpty .value}}
  - key: id
    value:
  - key: value
    value: {{ notEmpty .value}}
  - key: refid
    value: null
  {{- end }}
- key: 3
  value:
  {{- contains .value }}
  - key: name
    value: {{ notEmpty .value}}
  - key: id
    value:
  - key: value
    value: {{ notEmpty .value}}
  - key: refid
    value: null
  {{- end }}
- key: 4
  value:
  {{- contains .value }}
  - key: name
    value: {{ notEmpty .value}}
  - key: id
    value:
  - key: value
    value: {{ notEmpty .value}}
  - key: refid
    value: null
  {{- end }}
{{- end }}

```
e2e golang stack

![image](https://user-images.githubusercontent.com/3917424/190406027-e21da2f7-63ec-477c-a2e2-debcbeda4cf7.png)
